<?php
    $this->layout ('base');
    $this->start ('style');
?>
<!--tempat css/style-->

<link href="public/assets/bootstrap-tagsinput-latest/dist/bootstrap-tagsinput.css" rel="stylesheet"/>
<link href="public/assets/date-picker/css/bootstrap-datepicker.min.css" rel="stylesheet"/>
<link href="public/assets/select2/css/select2.min.css" rel="stylesheet"/>
<?php
    $this->stop ();
    $this->start ('navbar');
    $this->insert ('admin/navbar');
    $this->stop ();
    $this->start ('contents');
?>
<!--tempat konten-->
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line">Input Berita Tender</h4>
            </div>
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Form Berita Tender
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <form role="form" action="" method="post">
                                    <div class="form-group registration-date">
                                        <label>Tanggal Mulai</label>
                                        <div class="input-group date registration-date-time">
                                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
                                            <input class="form-control" type="text" name="tanggalmulai" required>
                                        </div>
                                    </div>
                                    <div class="form-group registration-date">
                                        <label>Tanggal Selesai</label>
                                        <div class="input-group date registration-date-time">
                                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
                                            <input class="form-control date-picker"type="text" name="tanggalselesai" required>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Judul</label>
                                        <input class="form-control" name="judul" required>
                                    </div>
                                    <div class="form-group"  data-toggle="tooltip" data-placement="right" title="Pilih Penyelenggara dari daftar yang tersedia. untuk menambahkan penyelenggara tekan tombol (+) di samping">
                                        <label>Penyelenggara</label>
                                        <div class="input-group">
                                            <select class="form-control penyelenggara" name="penyelenggara" required></select>
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="button">Button</button>
                                            </span>
                                        </div>
                                    </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Lokasi</label>
                                    <input class="form-control" name="lokasi">
                                </div>
                                <div class="form-group">
                                    <label>Link Website</label>
                                    <input class="form-control" placeholder="www.example.com" name="link" required>
                                </div>

                                <div class="form-group" data-toggle="tooltip" data-placement="left" title="Untuk memassukkan lebih dari satu dokumen persyaratan, dapat dipisahkan dengan koma (,)">
                                    <label>Dokumen Persyaratan</label>
                                    <input class="tags-input form-control" type="text" name="informasi" placeholder="NPWP, SIUP, Bank Garansi">
                                    <p class="help-block">Syarat Dokumen-dokumen harus diisi</p>
                                </div>
                                <button type="submit" class="btn btn-default" name="insert">Submit Button</button>
                                <button type="reset" class="btn btn-default">Reset Button</button>
                                </form>

                            </div>
                            <!-- /.col-lg-6 Masih Kosong -->
                            <div class="col-lg-6">
                                <p></p>

                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
</div>

<!-- /.row -->
<!--akhir tempat konten-->
<?php
    $this->stop ();
    $this->start ('js');
?>
<!--tempat js-->
<script type="text/javascript" src="public/assets/bootstrap-tagsinput-latest/dist/bootstrap-tagsinput.min.js"></script>
<script type="text/javascript" src="public/assets/date-picker/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript" src="public/assets/date-picker/locales/bootstrap-datepicker.id.min.js"></script>
<script type="text/javascript" src="public/assets/select2/js/select2.full.min.js"></script>
<script>
    $(document).ready(function () {
        $('.registration-date-time').datepicker({
            todayBtn:true,
            autoclose:true,
            format:"d MM yyyy",
            zIndexOffset:10000000,
            todayHighlight:true,
            language:'id',
        });

        $('.tags-input').tagsinput();
        $('.tags-input').on('itemAdded', function(event) {
            var $field = $(this).siblings('.bootstrap-tagsinput').find('input')
            setTimeout(function(){
                $field.val('');
            }, 1);
        });

        $('.penyelenggara').select2();
    });
</script>
<?php $this->stop () ?>
