<!DOCTYPE html>
<html lang="en"  class="fuelux">
    <head>
        <base href="<?= $this->basePath () ?>/">
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>E-Admin Tender</title>
        <link href="public/assets/css/bootstrap.css" rel="stylesheet"/>
        <link href="public/assets/css/font-awesome.css" rel="stylesheet"/>
        <link href="public/assets/css/style.css" rel="stylesheet"/>
        <link href="public/assets/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
        <link href="public/assets/fuelux/css/fuelux.min.css" rel="stylesheet"/>
        <?= $this->section ('style') ?>
    </head>
    <body>

        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <strong>Email: </strong>ryanhadiw@yahoo.com
                        &nbsp;&nbsp;
                        <strong>Support: </strong>+08-214-017-7480
                    </div>

                </div>
            </div>
        </header>

        <div class="navbar navbar-inverse set-radius-zero">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html">

                        <img src="public/assets/img/logo1.png " height="70px" width="175px"/>
                    </a>

                </div>

                <div class="left-div">
                    <div class="user-settings-wrapper">
                        <ul class="nav">

                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                                    <img class="dropdown-toggle img-circle img-responsive img-thumbnail" src="public/assets/img/64-64.jpg">
                                </a>
                                <div class="dropdown-menu dropdown-settings">
                                    <div class="media">
                                        <a class="media-left" href="#">
                                            <img src="public/assets/img/64-64.jpg" alt="" class="img-rounded"/>
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading">Jhon Deo Alex </h4>
                                            <h5>Developer & Designer</h5>
                                        </div>
                                    </div>
                                    <hr/>
                                    <h5><strong>Personal Bio : </strong></h5>
                                    Anim pariatur cliche reprehen derit.
                                    <hr/>
                                    <a href="profil.html" class="btn btn-info btn-sm">Full Profile</a>&nbsp;
                                    <a href="edit-profil.html" class="btn btn-danger btn-sm">Edit Profil</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <?= $this->section ('navbar') ?>
        <?= $this->section ('contents') ?>

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        &copy; 2017 YourCompany | By : Ryanhadiw</a>
                    </div>

                </div>
            </div>
        </footer>
        <script src="public/assets/js/jquery.min.js"></script>
        <script src="public/assets/js/bootstrap.js"></script>
        <script src="public/assets/fuelux/js/fuelux.min.js"></script>
        <script src="public/assets/datatable/datatables/media/js/jquery.dataTables.min.js"></script>
        <script src="public/assets/datatable/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
        <?= $this->section ('js') ?>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })
        </script>
    </body>
</html>