<html lang="en">

<head>
	<base href="<?= $uri->getBasePath() ?>/">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>E-Tender Login</title>

	<!-- CSS -->
	<!--link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500"-->
	<link rel="stylesheet" href="public/assetslogin/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="public/assetslogin/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="public/assetslogin/css/form-elements.css">
	<link rel="stylesheet" href="public/assetslogin/css/style.css">

	<!-- Favicon and touch icons -->
	<link rel="shortcut icon" href="public/assetslogin/ico/favicon.png">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/assetslogin/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="public/assetslogin/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="public/assetslogin/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="public/assetslogin/ico/apple-touch-icon-57-precomposed.png">

</head>

<body>

<!-- Top content -->
<div class="top-content">
	<div class="inner-bg">
		<div class="container">
			<div class="row">
				<div class="col-sm-8 col-sm-offset-2 text">
					<img src="public/assetslogin/img/logo-TEI-putih.png" class="center-block img-rounded" height="80" width="200" alt="Brand"></a>
					<h1><strong>Admin E-Tender</strong> Login Form</h1>
					<div class="description">
						<p>
							Harap Isi Terlebih Dahulu
						</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3 form-box">
					<div class="form-top">
						<div class="form-top-left">
							<h3>Login to our site</h3>
							<p>Enter your username and password to log on:</p>
						</div>
						<div class="form-top-right">
							<i class="fa fa-lock"></i>
						</div>
					</div>

					<div class="form-bottom">
						<form role="form" action="<?= $router->pathFor('doLogin') ?>" method="post" class="login-form">
							<?= if($authError){ ?>
							<div class="alert alert-dismissible alert-danger">
								<button type="button" class="close" data-dismiss="alert">&times;</button>
								<strong>Oh snap!</strong> <a href="#" class="alert-link">Change a few things up</a> and try submitting again.
							</div>
							<?= } ?>
							<div class="form-group">
								<label class="sr-only" for="form-username">username</label>
								<input type="text" name="username" placeholder="Username" class="form-username form-control" id="form-username">
							</div>
							<div class="form-group">
								<label class="sr-only" for="form-password">password</label>
								<input type="password" name="password" placeholder="Password" class="form-password form-control" id="form-password">
							</div>
							<button type="submit" class="btn" name="login" > Sign in! </button>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>


<!-- Javascript -->
<script src="public/assetslogin/js/jquery-1.11.1.min.js"></script>
<script src="public/assetslogin/bootstrap/js/bootstrap.min.js"></script>
<script src="public/assetslogin/js/jquery.backstretch.min.js"></script>
<script src="public/assetslogin/js/scripts.js"></script>

<!--[if lt IE 10]>
<script src="public/assetslogin/js/placeholder.js"></script>
<![endif]-->

</body>

</html>