<?php
/**
 * Copyright (c) 2017.
 */

$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/plugins/FixedColumns-3.2.2/css/fixedColumns.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/plugins/Select-1.2.2/css/select.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/bootstrap3-editable/css/bootstrap-editable.css"/>
    <style>
        td.wrap {
            word-wrap: break-word;
        }
        table.dataTable tbody th,
        table.dataTable tbody td {
            white-space: nowrap;
        }
        div.dataTables_wrapper {
            width: 800px;
            margin: 0 auto;
        }
        .DTFC_LeftBodyLiner {
            overflow-x: hidden;
        }
    </style>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Approval BOQ Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><i class="icon mdi mdi-link"></i> <?= $tender['link_website'] ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Dokumen Persyaratan</label>
                        <div class="well well-sm aside-well">
                            <?php foreach (explode('|', $tender['upload']) as $dokumen) { ?>
                                <span class="label label-default"><?= $dokumen ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Upload</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Status Approval</label>
                        <div class="well well-sm aside-well">
                            <?php $approval_direktur = json_decode($tender['direktur_approval'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <button type="button" class="btn btn-color btn-success">
                                    <i class="icon mdi mdi-check-circle"></i>
                                </button>
                                <button type="button" class="btn btn-success">
                                    Direktur
                                </button>
                                <button type="button" class="btn btn-default"><?= $this->indDateTime($approval_direktur['waktu']) ?></button>
                            </div>
                            <?php $approval_manager = json_decode($tender['manajer_approval'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <button type="button" class="btn btn-color btn-success">
                                    <i class="icon mdi mdi-check-circle"></i>
                                </button>
                                <button type="button" class="btn btn-success">
                                    Manajer
                                </button>
                                <button type="button" class="btn btn-default"><?= $this->indDateTime($approval_manager['waktu']) ?></button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Dokumen RKS</label>
                        <div class="well well-sm aside-well">
                            <?php $dok_rks = json_decode($tender['rks'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <a href="public/content/rks/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-default">
                                    <?= substr($dok_rks['file'], 0, 20) ?>...<?= substr($dok_rks['file'], -4) ?>
                                </a>
                                <a href="public/content/rks/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-color btn-social btn-primary">
                                    <i class="icon mdi mdi-eye"></i> Lihat
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Dokumen RKS</label>
                        <div class="well well-sm aside-well">
                            <?php $dok_rks = json_decode($tender['berita_acara'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <a href="public/content/berita-acara/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-default">
                                    <?= substr($dok_rks['file'], 0, 20) ?>...<?= substr($dok_rks['file'], -4) ?>
                                </a>
                                <a href="public/content/berita-acara/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-color btn-social btn-primary">
                                    <i class="icon mdi mdi-eye"></i> Lihat
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar BOQ
                <div class="tools">
                    <div class="btn-group btn-space">
                        <button type="button" class="btn btn-success mass-terima" disabled>
                            <i class="icon mdi mdi-check" style="color: white"></i> Terima
                        </button>
                        <?php if (in_array ($active_user_data[ 'previledge' ], ['2'])): ?>
                        <button type="button" class="btn btn-danger mass-tolak" disabled>
                            <i class="icon mdi mdi-close" style="color: white"></i> Tolak
                        </button>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <table id="unit-kerja" class="table table-borderless table-fw-widget" style="width: 100% !important;">
                    <thead>
                        <tr>
                            <th width="5%">
                            </th>
                            <th>No</th>
                            <th>Vendor / Barang</th>
                            <th>Harga / Jumlah / total</th>
                            <th>Diajukan Oleh</th>
                            <th>Status</th>
                            <th>Approval</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--akhir tempat konten-->
    <!--Modal Approve terima Single-->
    <div id="approval-terima" class="modal-container full-width  colored-header modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Setujui BOQ</h3>
            </div>
            <div class="modal-body">
                <div role="alert" class="alert alert-warning alert-icon alert-icon-border alert-dismissible">
                    <div class="icon"><span class="mdi mdi-info-outline"></span></div>
                    <div class="message">
                        <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>
                        <strong>Info</strong> Klik <strong>TEKS</strong> untuk mengubah data BOQ
                    </div>
                </div>
                <div class="tempat-table" style="overflow:scroll;height:200px;width:100%;overflow:auto"></div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn modal-close modal-ok">Setujui</button>
                <button type="button" data-dismiss="modal" class="btn btn-default modal-close modal-cancel">Batal</button>
            </div>
        </div>
    </div>
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/dataTables.rowsGroup.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/FixedColumns-3.2.2/js/dataTables.fixedColumns.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/Select-1.2.2/js/dataTables.select.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/currency.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/bootstrap3-editable/js/bootstrap-editable.min.js" type="text/javascript"></script>
    <script>
        var tBOQ;
        function populateTable(repopulate) {
            if(repopulate){
                tBOQ.destroy()
            }
            if ( $.fn.dataTable.isDataTable( '#unit-kerja' ) == false ) {
                tBOQ = $('#unit-kerja').DataTable({
                    sort: false,
                    ajax:"<?= $this->pathFor('getBOQTender', ['id_tender'=>$tender['id_tender']]) ?>",
                    columns:[
                        {
                            data: "id_penawaran",
                            render: function (data, type, row, meta) {
                                return meta.row + meta.settings._iDisplayStart + 1;
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, row, meta) {
                                delete data.rowData;
//                                var datas =  {
//                                    id_penawaran:data.id_penawaran,
//                                    nama_vendor:data.nama_vendor,
//                                    nama_barang:data.nama_barang,
//                                    harga_persatuan:data.harga_persatuan,
//                                    volume_barang:data.volume_barang,
//                                    ukuran_satuan:data.ukuran_satuan,
//                                    pegawai:data.pegawai,
//                                    total:data.total,
//                                }
                                return  '<div class="be-checkbox be-checkbox-sm">'+
                                    '   <input id="check'+data.id_penawaran+'" class="mass-check" type="checkbox" value=\''+JSON.stringify(data)+'\'>'+
                                    '   <label for="check'+data.id_penawaran+'"></label>'+
                                    '</div>'
                            }
                        },
                        {
                            data: null,
                            className: "cell-detail",
                            render: function (data, type, row, meta) {
                                return '<span>'+data.nama_vendor+'</span><span class="cell-detail-description"><strong>'+data.nama_barang+'</strong></span>'
                            }
                        },
                        {
                            data:{
                                _:null,
                                sort:"volume_barang"
                            },
                            className: "cell-detail",
                            render: function (data, type, row, meta) {
                                return '<span> Rp. '+parseInt(data.harga_persatuan).formatMoney(0)+'</span><span class="cell-detail-description"><strong>'+data.volume_barang+' '+data.ukuran_satuan+'</strong></span><span> Rp. '+parseInt(data.total).formatMoney(0)+'</span>'
                            }
                        },
                        {
                            data: {
                                _:"pegawai",
                                sort:'pegawai.who.id_user'
                            },
                            className: 'user-avatar cell-detail user-info',
                            render: function (data, type, row, meta) {
                                var waktu = moment(data.time).fromNow()
                                return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + data.who.nama + '</span><span class="cell-detail-description">' + waktu + '</span>';
                            },
                        },
                        {
                            data: null,
                            className: 'text-center',
                            render: function (data, type, row, meta) {
                                var dtStatusCol = Twig.twig({
                                    href: "app/views/approval/boq/dt-status-col.twig",
                                    async: false,
                                })
                                return  dtStatusCol.render(data.approval)
                            }
                        },
                        {
                            data: null,
                            className: 'text-center',
                            render: function (data, type, row, meta) {
                                delete data.rowData;
                                data.active_user_priv = <?= $active_user_data[ 'previledge' ] ?>;
                                var approvalColTmp = Twig.twig({
                                    href: "app/views/approval/boq/dt-approval-col.twig",
                                    async: false,
                                });
                                return approvalColTmp.render({rowData:data})
                            }
                        },
                    ],
                    initComplete: function(settings, json) {
                        tBOQ.rows().every( function ( rowIdx, tableLoop, rowLoop ) {
                            var data = this.data();
                            if(data.inputan_manajer){
//                                tBOQ.row(rowIdx).nodes().to$().addClass('online')
                                data.inputan_manajer.pegawai.time = moment(data.inputan_manajer.pegawai.time).fromNow()
                                data.inputan_manajer.approval = JSON.parse(data.inputan_manajer.approval)
                                data.inputan_manajer.active_user_priv = <?= $active_user_data[ 'previledge' ] ?>;
                                var rowChildTmp = Twig.twig({
                                    href: "app/views/approval/boq/custom-render-child.twig",
                                    async: false,
                                })
                                tBOQ.row(rowIdx).child($(rowChildTmp.render(data))).show()
                            }
                        });
                    }
                });
            }
            var numFormat = $.fn.dataTable.render.number( '\,', '.', 2, 'Rp.' ).display;

            $('#unit-kerja tbody').on('click', 'td .btn-terima', function () {
                var rowData = $(this).data('rowdata');
                approvalModal({rowData:[rowData]}, 'diterima', populateTable);
            });
            $('#unit-kerja tbody').on('click', 'td .btn-tolak', function () {
                var rowData = $(this).data('rowdata');
                var activeUser = <?= $active_user_data[ 'previledge' ] ?>;
                if(activeUser == '3'){
                    approvalModal({rowData:[rowData]}, 'ditolak', populateTable, true);
                }else{
                    approvalModal({rowData:[rowData]}, 'ditolak', populateTable);
                }
            });
            $('#unit-kerja tbody').on('change', 'input[type="checkbox"]', function(){
                var row = tBOQ.row( $(this).parents('tr') )
                if(row.child.isShown()){
                    row.child().find('input[type="checkbox"]').prop('checked', false);
                }else{
                    var parent = $(this).data('parent');
                    if(parent){
                        $('#unit-kerja tbody #check'+parent).prop('checked', false);
                    }
                }
                if($('#unit-kerja tbody input[type="checkbox"]:checked').length){
                    $('.mass-terima').prop('disabled', false)
                    $('.mass-tolak').prop('disabled', false)
                }else{
                    $('.mass-terima').prop('disabled', true)
                    $('.mass-tolak').prop('disabled', true)
                }
            });
            $('.mass-terima').on('click', function () {
                var selectedData = []
                $('#unit-kerja tbody input[type="checkbox"]:checked').each(function () {
                    selectedData.push(JSON.parse($(this).val()));
                })
                approvalModal({rowData:selectedData}, 'diterima');
            })
            $('.mass-tolak').on('click', function () {
                var selectedData = []
                var activeUser = <?= $active_user_data[ 'previledge' ] ?>;
                $('#unit-kerja tbody input[type="checkbox"]:checked').each(function () {
                    selectedData.push(JSON.parse($(this).val()));
                })
                if(activeUser == 3){
                    approvalModal({rowData:selectedData}, 'ditolak', true);
                }else{
                    approvalModal({rowData:selectedData}, 'ditolak');
                }
            })
            $.getJSON('<?= $this->pathFor('getBOQTender', ['id_tender'=>$tender['id_tender']]) ?>', function (data) {

            });
        }
        function approvalModal(rowData, type, populateTable, isManajer){
            console.log(rowData)
            var approvalTableTmp = Twig.twig({
                href: "app/views/approval/boq/table-approval-preview.twig",
                async: false,
            });
            var approvalTableEditableTmp = Twig.twig({
                href: "app/views/approval/boq/table-approval-editable.twig",
                async: false,
            });
            $('#approval-terima').niftyModal({
                beforeOpen: function( modal ){
                    if(type == 'diterima'){
                        $(modal.modalEl).removeClass('colored-header-danger');
                        $(modal.modalEl).addClass('colored-header-success');
                        $(modal.modalEl).find('.modal-title').html('Setujui BOQ di bawah ini ?');
                        $(modal.modalEl).find('.modal-ok').html('Setujui');
                        $(modal.modalEl).find('.modal-ok').removeClass('btn-danger')
                        $(modal.modalEl).find('.modal-ok').addClass('btn-success')
                    }else{
                        $(modal.modalEl).removeClass('colored-header-success');
                        $(modal.modalEl).addClass('colored-header-danger');
                        $(modal.modalEl).find('.modal-title').html('Tolak BOQ di bawah ini ?');
                        $(modal.modalEl).find('.modal-ok').html('Tolak');
                        $(modal.modalEl).find('.modal-ok').removeClass('btn-success')
                        $(modal.modalEl).find('.modal-ok').addClass('btn-danger')
                    }
                    if(typeof isManajer === 'undefined'){
                        $(modal.modalEl).find('.tempat-table').html(approvalTableTmp.render(rowData));
                        $(modal.modalEl).find('.alert').addClass('hidden')
                    }else{
                        $(modal.modalEl).find('.tempat-table').html(approvalTableEditableTmp.render(rowData));
                        $(modal.modalEl).find('#boq-editable a.editable-revisi').editable({
                            type: 'text',
                        });
                        $(modal.modalEl).find('#boq-editable a[data-name="harga_persatuan"]').on('save', function(e, params) {
                            var total = $(modal.modalEl).find('#boq-editable a[data-name="volume_barang"]').editable('getValue', true)*params.newValue
                            $(modal.modalEl).find('#boq-editable a[data-name="total"]').editable('setValue', total)
                        });
                        $(modal.modalEl).find('#boq-editable a[data-name="volume_barang"]').on('save', function(e, params) {
                            var total = $(modal.modalEl).find('#boq-editable a[data-name="harga_persatuan"]').editable('getValue', true)*params.newValue
                            $(modal.modalEl).find('#boq-editable a[data-name="total"]').editable('setValue', total)
                        });
                        $(modal.modalEl).find('.alert').removeClass('hidden')
                    }
//                    approvalTableTmp.render(data);
                },
                buttons: [
                    {
                        class: 'modal-ok',
                        callback: function ( btn, modal, event ) {
                            if(typeof isManajer != 'undefined'){
                                var dataRev = [];
                                dataRev.push($(modal.modalEl).find('#boq-editable a.editable-revisi').editable('getValue', false));
                                console.log(dataRev)
                                $.post("<?= $this->pathFor("ApprovalBOQTender") ?>", {data:dataRev, status:type}, function(data){
                                    populateTable(true);
                                }, 'json')
                            }else{
//                                console.log(rowData)
                                $.post("<?= $this->pathFor("ApprovalBOQTender") ?>", {data:rowData.rowData, status:type}, function(data){
                                    populateTable(true);
                                }, 'json')
                            }
                        }
                    },
                    {
                        class: 'modal-cancel',
                        callback: function ( btn, modal, event ) {

                        }
                    }
                ],
            });
        }
        $(document).ready(function () {
            $.fn.editable.defaults.mode = 'inline';
            Number.prototype.formatMoney = function(c, d, t){
                var n = this,
                    c = isNaN(c = Math.abs(c)) ? 2 : c,
                    d = d == undefined ? "." : d,
                    t = t == undefined ? "," : t,
                    s = n < 0 ? "-" : "",
                    i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))),
                    j = (j = i.length) > 3 ? j % 3 : 0;
                return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
            };
            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });
            //We use this to apply style to certain elements
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada data BOQ</h4>' +
                    '<button class="btn btn-rounded btn-space btn-primary btn-sm" data-toggle="modal" data-target="#form-unitkerja"><i class="mdi mdi-shopping-cart-plus"></i>&nbsp; Tambah BOQ </button>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });
            populateTable()
        })
    </script>
<?php $this->stop() ?>