<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Dokumen Master Administrasi
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Dokumen Administrasi
                <div class="tools">
                    <button class="btn btn-space btn-primary btn-sm add-dok">
                        <i class="mdi mdi-file-plus"></i>
                        &nbsp; Tambah Dokumen Administrasi
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="dokumen-master" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="35%">Nama Dokumen & Alias</th>
                            <th width="20%">File</th>
                            <th width="20%">Diupload Oleh</th>
                            <th width="10%"class="action"></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="add-dok" class="modal-container colored-header colored-header-primary modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Tambah Dokumen Master</h3>
            </div>
            <div class="modal-body">
                <div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible">
                    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
                    <div class="message">
                        <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>
                        Mohon isi Nama Dokumen dan pilih File Dokumen
                    </div>
                </div>
                <form method="post" action="<?= $this->pathFor('dokumenMaster_add') ?>" enctype="multipart/form-data">
                    <div class="form-group">
                        <label>Nama Dokumen</label>
                        <select multiple="" class="tags" name="nama_dokumen[]"  data-error="Wajib di isi" required></select>
                    </div>
                    <div class="form-group">
                        <label>File Dokumen</label>
                        <div class="input-group xs-mb-15">
                            <input type="text" class="form-control" name="file_name" readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-primary modal-close input-file">Pilih File</button>
                            </span>
                        </div>
                        <input type="file"  name="file_dokumen" placeholder="File Dokumen" class="form-control hidden" accept="application/pdf" hidden>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default btn-cancel modal-close">Cancel</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary btn-ok modal-close">Tambah</button>
            </div>
        </div>
    </div>
    <div id="edit-dok" class="modal-container colored-header colored-header-primary modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Edit Dokumen Master</h3>
            </div>
            <div class="modal-body">
                <div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible">
                    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
                    <div class="message">
                        <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>
                        Mohon isi Nama Dokumen dan pilih File Dokumen
                    </div>
                </div>
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="form-group">
                        <label>Nama Dokumen</label>
                        <select multiple="" class="tags" name="nama_dokumen[]"  data-error="Wajib di isi" required></select>
                    </div>
                    <div class="form-group">
                        <label>File Dokumen</label>
                        <div class="input-group xs-mb-15">
                            <input type="text" class="form-control" name="file_name" readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-primary modal-close input-file">Pilih File</button>
                            </span>
                        </div>
                        <input type="file"  name="file_dokumen" placeholder="File Dokumen" class="form-control hidden" accept="application/pdf" hidden>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default btn-cancel modal-close">Cancel</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary btn-ok modal-close">Simpan</button>
            </div>
        </div>
    </div>
    <div id="delete-dok" class="modal-container modal-effect-8" style="perspective: 1300px; height: 382px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <span class="modal-main-icon mdi mdi-delete text-danger"></span>
                    <h3>Hapus!</h3>
                    <p>Apakah anda yakin akan menghapus dokumen <strong></strong>?</p>
                    <div class="xs-mt-50">
                        <button type="button" data-dismiss="modal" class="btn btn-default btn-space modal-close">Batal</button>
                        <button type="button" data-dismiss="modal" class="btn btn-danger btn-space btn-delete modal-close">Hapus</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
    <div class="modal-overlay"></div>

    <!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/dropzone/dist/min/dropzone.min.js" type="text/javascript"></script>
    <script src="public/assets/js/jquery.form.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada data Dokumen Kelengkapan Tender</h4>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });

            var dokumen_master = $('#dokumen-master').DataTable({
                ajax: "<?= $this->pathFor('dokumenMaster_get') ?>",
                columns: [
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: 'nama_dokumen',
                        render: function (data, type, row, meta) {
                            var nama = data.split('|');
                            var nama_html = '';
                            $.each(nama, function (key, val) {
                                nama_html = nama_html + '<span class="label label-default">'+val+'</span> ';
                            });
                            return nama_html;
                        }
                    },
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return "<a target='_blank' href='public/content/dokumen/"+data.file_dokumen+"'>"+data.file_dokumen.substr(0, 60)+"</a>";
                        }
                    },
                    {
                        data: null,
                        className: ' user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            var waktu = moment(data.waktu).fromNow();
                            return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + (data.who.id_user == active_user.user_id ? 'Anda Sendiri' : data.who.nama) + '</span><span class="cell-detail-description">' + waktu + '</span><span class="cell-detail-description">' + (data.who.unit_kerja ? data.who.unit_kerja.penugasan : '' ) + '</span>';
                        }
                    },
                    {
                        data: null,
                        className: 'text-right',
                        render: function (data, type, row, meta) {
                            delete data.rowData;
                            return  '   <div class="btn-group">'+
                                    '      <button type="button" class="btn btn-primary btn-edit" data-rowdata=\'' + JSON.stringify(data) + '\'><i class="icon icon-left mdi mdi-edit"></i></button>'+
                                    '      <button class="btn btn-danger btn-delete"  data-rowdata=\'' + JSON.stringify(data) + '\'><i class="icon icon-left mdi mdi-delete"></i></button>'+
                                    '   </div>'
                        }
                    },
                ],
            });
            $('#dokumen-master tbody').on('click', '.btn-edit', function () {
                var rowData = $(this).data('rowdata');
                $('#add-dok').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('select').select2({
                            placeholder: "Nama Dokumen dan Aliasnya",
                            multiple: true,
                            tags: true,
                            width: '100%',
                            data: rowData.nama_dokumen.split('|')
                        });
                        console.log(rowData.nama_dokumen.split('|'));
                        modal.find('select').val(rowData.nama_dokumen.split('|')).trigger('change')
                        modal.find('.alert').addClass('hidden');
                        modal.find('input[name="file_dokumen"]').val('');
                        modal.find('input[name="file_name"]').val(rowData.file_dokumen);
                    },
                    afterOpen: function( modal ){
                        var modal = $(modals.modalEl);
                        modal.find('select').on('change', function () {
                            $(this).valid();
                        });
                    },
                    buttons: [
                        {
                            class: 'input-file',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                modal.find('input[name="file_dokumen"]').click();
                                modal.find('input[name="file_dokumen"]').on('change', function () {
                                    modal.find('input[name="file_name"]').val($(this).val().replace(/C:\\fakepath\\/i, ''))
                                });
                                return false
                            }
                        },{
                            class: 'btn-ok',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                var ret = true;
                                modal.find('form').ajaxSubmit({
                                    clearForm: true,
                                    url: '<?= $this->pathFor('dokumenMaster_edit', ['id_dokumen'=>'']) ?>'+rowData.id_dokumen_master,
                                    dataType: 'json',
                                    beforeSubmit:function (formData, jqForm, options) {
                                        var file = modal.find('input[name="file_name"]').fieldValue();
                                        var name = modal.find('select').fieldValue();
                                        if(!file[0] || !name[0]){
                                            modal.find('.alert').removeClass('hidden');
                                            ret = false;
                                            return false;
                                        }
                                    },
                                    success: function (res, statusText, xhr, $form) {
                                        if(res.status == 'success'){
                                            dokumen_master.ajax.reload();
                                        }
                                    },
                                });
                                return ret;
                            }
                        }
                    ],
                });
            });

            $('#dokumen-master tbody').on('click', '.btn-delete', function () {
                var rowData = $(this).data('rowdata');
                $('#delete-dok').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        var modal = $(modals.modalEl);
                        modal.find('p strong').html(rowData.nama_dokumen.replace(/\|/g, " / "));
                    },
                    buttons: [
                        {
                            class: 'btn-delete',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                if(modal.find('input[name="nama_dokumen"]').val() !== ""){
                                    $.getJSON("<?= $this->pathFor('dokumenMaster_delete') ?>/"+rowData.id_dokumen_master, function(data){
                                        if(data.status == "success"){
                                            dokumen_master.ajax.reload();
                                            return true;
                                        }
                                    });
                                }else{
                                    return false;
                                }
                            }
                        }
                    ]
                });
            });

            $('.add-dok').on('click', function(){
                $('#add-dok').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('select').select2({
                            placeholder: "Nama Dokumen dan Aliasnya",
                            tags: true,
                            width: '100%'
                        });
                        modal.find('.alert').addClass('hidden');
                        modal.find('select').select2('val', 'All');
                        modal.find('input[name="file_dokumen"]').val('');
                        modal.find('input[name="file_name"]').val('');
                    },
                    afterOpen: function( modal ){
                        var modal = $(modals.modalEl);
                        modal.find('select').on('change', function () {
                            $(this).valid();
                        });
                    },
                    buttons: [
                        {
                            class: 'input-file',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                modal.find('input[name="file_dokumen"]').click();
                                modal.find('input[name="file_dokumen"]').on('change', function () {
                                    modal.find('input[name="file_name"]').val($(this).val().replace(/C:\\fakepath\\/i, ''))
                                });
                                return false
                            }
                        },{
                            class: 'btn-ok',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                var ret = true;
                                modal.find('form').ajaxSubmit({
                                    clearForm: true,
                                    dataType: 'json',
                                    beforeSubmit:function (formData, jqForm, options) {
                                        var file = modal.find('input[name="file_dokumen"]').fieldValue();
                                        var name = modal.find('select').fieldValue();
                                        if(!file[0] || !name[0]){
                                            modal.find('.alert').removeClass('hidden');
                                            ret = false;
                                            return false;
                                        }
                                    },
                                    success: function (responseText, statusText, xhr, $form) {
                                        if(res.status == 'success'){
                                            dokumen_master.ajax.reload();
                                        }
                                    },
                                });
                                return ret;
                            }
                        }
                    ],
                });
            });
        })
    </script>
<?php $this->stop() ?>