<?php
/**
 * Copyright (c) 2017.
 */

$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/plugins/FixedColumns-3.2.2/css/fixedColumns.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/plugins/Select-1.2.2/css/select.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/bootstrap3-editable/css/bootstrap-editable.css"/>
    <style>
        td.wrap {
            word-wrap: break-word;
        }
        table.dataTable tbody th,
        table.dataTable tbody td {
            white-space: nowrap;
        }
        div.dataTables_wrapper {
            width: 800px;
            margin: 0 auto;
        }
        .DTFC_LeftBodyLiner {
            overflow-x: hidden;
        }
    </style>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Approval BOQ Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Berita Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><?= substr($tender['link_website'], 0, 35) ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Diupload Oleh</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
                <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div>
            </div>
        </div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar BOQ
                <div class="tools">
                    <button class="btn btn-space btn-primary open-modal-cetak">
                        <i class="mdi mdi-print"></i>
                        &nbsp; Cetak
                    </button>
                    <div class="btn-group btn-space">
                        <button type="button" class="btn btn-success mass-terima" disabled>
                            <i class="icon mdi mdi-check" style="color: white"></i> Terima
                        </button>
                        <button type="button" class="btn btn-danger mass-tolak" disabled>
                            <i class="icon mdi mdi-close" style="color: white"></i> Tolak
                        </button>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <table id="unit-kerja" class="table table-borderless table-fw-widget" style="width: 100% !important;">
                    <thead>
                        <tr>
                            <th width="5%">
                            </th>
                            <th>No</th>
                            <th>Vendor / Barang</th>
                            <th>Harga / Jumlah / Jasa / Total</th>
                            <th>Diajukan Oleh</th>
                            <th>Status</th>
                            <th>Approval</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--akhir tempat konten-->
    <!--Modal Approve terima Single-->
    <div id="approval-terima" class="modal-container full-width  colored-header modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Setujui BOQ</h3>
            </div>
            <div class="modal-body">
                <div role="alert" class="alert alert-warning alert-icon alert-icon-border alert-dismissible">
                    <div class="icon"><span class="mdi mdi-info-outline"></span></div>
                    <div class="message">
                        <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button>
                        <strong>Info</strong> Klik <strong>TEKS</strong> untuk mengubah data BOQ
                    </div>
                </div>
                <div class="tempat-table" style="overflow:scroll;height:200px;width:100%;overflow:auto"></div>
                <textarea class="form-control keterangan hidden" rows="3" placeholder="Tambahkan keterangan kenapa anda menolak"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn modal-close modal-ok">Setujui</button>
                <button type="button" data-dismiss="modal" class="btn btn-default modal-close modal-cancel">Batal</button>
            </div>
        </div>
    </div>
    <div id="modal-cetak" class="modal-container full-width modal-effect-9" style="perspective: none; max-height: 95%">
        <div class="modal-content">
            <div class="modal-body row" style="padding-top: 20px !important;">
                <div class="col-md-10 pdf-preview">
<!--                    <object data='--><?//= $this->pathFor('BOQTender_print', ['id_tender'=>$tender['id_tender']]) ?><!--#scrollbar=0&toolbar=0&statusbar=0&messages=0&navpanes=0' type='application/pdf' width='100%' height='562mm' style="border: 1px solid black;"></object>-->
                </div>
                <div class="col-md-2">
                    <button type="button" class="close modal-close"><span class="mdi mdi-close"></span></button>
                    <div style="width: 100%;">
                        <h4>Pengaturan Cetak</h4>
                        <div class="be-checkbox">
                            <input id="approved" type="checkbox" checked="">
                            <label for="approved">Disetujui</label>
                        </div>
                        <span class="help-block" style="padding-left: 30px;">
                            Hanya tampilkan item yang telah disetujui.
                        </span>
                        <hr>
                        <button class="btn btn-space btn-primary btn-big  modal-close btn-print"><i class="icon mdi mdi-print"></i> Cetak </button>
                        <a href="<?= $this->pathFor('BOQTender_print', ['id_tender'=>$tender['id_tender'], 'download'=>true]) ?>?approved" class="btn btn-space btn-success btn-big"><i class="icon mdi mdi-download"></i> Unduh </a>
                    </div>
                </div>
            </div>
<!--            <div class="modal-footer">-->
<!--                <button type="button" class="btn btn-primary modal-close btn-simpan">Tambahkan</button>-->
<!--                <button type="button" class="btn btn-default modal-close">Batal</button>-->
<!--            </div>-->
        </div>
    </div>

    <div class="modal-overlay"></div>
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/dataTables.rowsGroup.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/FixedColumns-3.2.2/js/dataTables.fixedColumns.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/Select-1.2.2/js/dataTables.select.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/currency.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/bootstrap3-editable/js/bootstrap-editable.min.js" type="text/javascript"></script>
    <script src="public/assets/js/print.min.js" type="text/javascript"></script>
    <script>
        var tBOQ;
        function populateTable(repopulate) {
            if(repopulate){
                tBOQ.destroy()
            }
            if ( $.fn.dataTable.isDataTable( '#unit-kerja' ) == false ) {
                tBOQ = $('#unit-kerja').DataTable({
                    sort: false,
                    ajax:"<?= $this->pathFor('BOQTender_get', ['id_tender'=>$tender['id_tender']]) ?>",
                    columns:[
                        {
                            data: "id_penawaran",
                            render: function (data, type, row, meta) {
                                return meta.row + meta.settings._iDisplayStart + 1;
                            }
                        },
                        {
                            data: null,
                            render: function (data, type, row, meta) {
                                delete data.rowData;
                                return  '<div class="be-checkbox be-checkbox-sm">'+
                                    '   <input id="check'+data.id_penawaran+'" class="mass-check" type="checkbox" value=\''+JSON.stringify(data)+'\'>'+
                                    '   <label for="check'+data.id_penawaran+'"></label>'+
                                    '</div>'
                            }
                        },
                        {
                            data: null,
                            className: "cell-detail",
                            render: function (data, type, row, meta) {
                                return '<span>'+data.nama_vendor+'</span><span class="cell-detail-description"><strong>'+data.nama_barang+'</strong></span>'
                            }
                        },
                        {
                            data:{
                                _:null,
                                sort:"volume_barang"
                            },
                            className: "cell-detail",
                            render: function (data, type, row, meta) {
                                return '<span> Rp. '+parseInt(data.harga_persatuan).formatMoney(0)+'</span><span class="cell-detail-description"><strong>'+data.volume_barang+' '+data.ukuran_satuan+'</strong></span><span>Rp. ' + parseInt(data.harga_jasa).formatMoney(0) + '</span><span class="cell-detail-description"> Rp. '+parseInt(data.total).formatMoney(0)+'</span>';
                            }
                        },
                        {
                            data: {
                                _:"pegawai",
                                sort:'pegawai.who.id_user'
                            },
                            className: 'user-avatar cell-detail user-info',
                            render: function (data, type, row, meta) {
                                var waktu = moment(data.time).fromNow()
                                return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + data.who.nama + '</span><span class="cell-detail-description">' + waktu + '</span>';
                            },
                        },
                        {
                            data: null,
                            className: 'text-center',
                            render: function (data, type, row, meta) {
                                var dtStatusCol = Twig.twig({
                                    href: "app/views/boq/dt-status-col.twig",
                                    async: false,
                                })
                                return  dtStatusCol.render(data.approval)
                            }
                        },
                        {
                            data: null,
                            className: 'text-center',
                            render: function (data, type, row, meta) {
                                delete data.rowData;
                                data.active_user_priv = <?= $active_user_data[ 'previledge' ] ?>;
                                var approvalColTmp = Twig.twig({
                                    href: "app/views/boq/dt-approval-col.twig",
                                    async: false,
                                });
                                return approvalColTmp.render({rowData:data})
                            }
                        },
                    ],
                    initComplete: function(settings, json) {

                    }
                });
            }
            var numFormat = $.fn.dataTable.render.number( '\,', '.', 2, 'Rp.' ).display;

            $('#unit-kerja tbody').on('click', 'td .btn-terima', function () {
                var rowData = $(this).data('rowdata');
                approvalModal({rowData:[rowData]}, 'diterima', populateTable);
            });
            $('#unit-kerja tbody').on('click', 'td .btn-tolak', function () {
                var rowData = $(this).data('rowdata');
                var activeUser = <?= $active_user_data[ 'previledge' ] ?>;
                approvalModal({rowData:[rowData]}, 'ditolak', populateTable);
            });
            $('#unit-kerja tbody').on('change', 'input[type="checkbox"]', function(){
                var row = tBOQ.row( $(this).parents('tr') )
                if(row.child.isShown()){
                    row.child().find('input[type="checkbox"]').prop('checked', false);
                }else{
                    var parent = $(this).data('parent');
                    if(parent){
                        $('#unit-kerja tbody #check'+parent).prop('checked', false);
                    }
                }
                if($('#unit-kerja tbody input[type="checkbox"]:checked').length){
                    $('.mass-terima').prop('disabled', false)
                    $('.mass-tolak').prop('disabled', false)
                }else{
                    $('.mass-terima').prop('disabled', true)
                    $('.mass-tolak').prop('disabled', true)
                }
            });
            $('.mass-terima').on('click', function () {
                var selectedData = []
                $('#unit-kerja tbody input[type="checkbox"]:checked').each(function () {
                    selectedData.push(JSON.parse($(this).val()));
                })
                approvalModal({rowData:selectedData}, 'diterima');
            })
            $('.mass-tolak').on('click', function () {
                var selectedData = []
                var activeUser = <?= $active_user_data[ 'previledge' ] ?>;
                $('#unit-kerja tbody input[type="checkbox"]:checked').each(function () {
                    selectedData.push(JSON.parse($(this).val()));
                })
                approvalModal({rowData:selectedData}, 'ditolak');
            })
            $.getJSON('<?= $this->pathFor('BOQTender_get', ['id_tender'=>$tender['id_tender']]) ?>', function (data) {

            });
        }
        function approvalModal(rowData, type, populateTable, isManajer){
            console.log(rowData)
            var approvalTableTmp = Twig.twig({
                href: "app/views/boq/table-approval-preview.twig",
                async: false,
            });
            var approvalTableEditableTmp = Twig.twig({
                href: "app/views/boq/table-approval-editable.twig",
                async: false,
            });
            $('#approval-terima').niftyModal({
                beforeOpen: function( modal ){
                    $(modal.modalEl).find('.keterangan').val(null);
                    if(type == 'diterima'){
                        $(modal.modalEl).removeClass('colored-header-danger');
                        $(modal.modalEl).addClass('colored-header-success');
                        $(modal.modalEl).find('.modal-title').html('Setujui BOQ di bawah ini ?');
                        $(modal.modalEl).find('.modal-ok').html('Setujui');
                        $(modal.modalEl).find('.modal-ok').removeClass('btn-danger');
                        $(modal.modalEl).find('.modal-ok').addClass('btn-success');
                        $(modal.modalEl).find('.keterangan').addClass('hidden');
                    }else{
                        $(modal.modalEl).removeClass('colored-header-success');
                        $(modal.modalEl).addClass('colored-header-danger');
                        $(modal.modalEl).find('.modal-title').html('Tolak BOQ di bawah ini ?');
                        $(modal.modalEl).find('.modal-ok').html('Tolak');
                        $(modal.modalEl).find('.modal-ok').removeClass('btn-success');
                        $(modal.modalEl).find('.keterangan').removeClass('hidden');
                        $(modal.modalEl).find('.modal-ok').addClass('btn-danger')
                    }
                    if(typeof isManajer === 'undefined'){
                        $(modal.modalEl).find('.tempat-table').html(approvalTableTmp.render(rowData));
                        $(modal.modalEl).find('.alert').addClass('hidden')
                    }
//                    approvalTableTmp.render(data);
                },
                buttons: [
                    {
                        class: 'modal-ok',
                        callback: function ( btn, modal, event ) {
                            var keterangan =  $(modal.modalEl).find('.keterangan').val();
                            $.post("<?= $this->pathFor("BOQTender_approval") ?>", {data:rowData.rowData, status:type, keterangan:keterangan}, function(data){
                                populateTable(true);
                            }, 'json')
                        }
                    },
                    {
                        class: 'modal-cancel',
                        callback: function ( btn, modal, event ) {

                        }
                    }
                ],
            });
        }
        $(document).ready(function () {
            $.fn.editable.defaults.mode = 'inline';
            Number.prototype.formatMoney = function(c, d, t){
                var n = this,
                    c = isNaN(c = Math.abs(c)) ? 2 : c,
                    d = d == undefined ? "." : d,
                    t = t == undefined ? "," : t,
                    s = n < 0 ? "-" : "",
                    i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))),
                    j = (j = i.length) > 3 ? j % 3 : 0;
                return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
            };
            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });
            //We use this to apply style to certain elements
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada data BOQ</h4>' +
                    '<button class="btn btn-rounded btn-space btn-primary btn-sm" data-toggle="modal" data-target="#form-unitkerja"><i class="mdi mdi-shopping-cart-plus"></i>&nbsp; Tambah BOQ </button>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });
            populateTable()
            $('.open-modal-cetak').on('click', function () {
                $('#modal-cetak').niftyModal({
                    buttons: [
                        {
                            class: 'btn-print',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                printJS(modal.find('.pdf-preview object').attr('data'));
                                return false;
                            }
                        },
                    ],
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('#approved').attr("checked", true);
                        var url = '<?= $this->pathFor('BOQTender_print', ['id_tender'=>$tender['id_tender']]) ?>';
                        var urlDownload = '<?= $this->pathFor('BOQTender_print', ['id_tender'=>$tender['id_tender'], 'download'=>true]) ?>';
                        modal.find('.pdf-preview').html(
                            '<object data="' + url + '?approved#scrollbar=0&toolbar=0&statusbar=0&messages=0&navpanes=0" type="application/pdf" width="100%" height="562mm" style="border: 1px solid black;"></object>'
                        );
                        modal.find('#approved').change(function() {
                            if (this.checked) {
                                modal.find('.pdf-preview').html(
                                    '<object data="' + url + '?approved#scrollbar=0&toolbar=0&statusbar=0&messages=0&navpanes=0" type="application/pdf" width="100%" height="562mm" style="border: 1px solid black;"></object>'
                                );
                            } else {
                                modal.find('.pdf-preview').html(
                                    '<object data="' + url + '#scrollbar=0&toolbar=0&statusbar=0&messages=0&navpanes=0" type="application/pdf" width="100%" height="562mm" style="border: 1px solid black;"></object>'
                                );
                            }
                        });
                    }
                });
            })
        })
    </script>
<?php $this->stop() ?>