<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Daftar BOQ Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><i class="icon mdi mdi-link"></i> <?= $tender['link_website'] ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Dokumen Persyaratan</label>
                        <div class="well well-sm aside-well">
                            <?php foreach (explode('|', $tender['upload']) as $dokumen) { ?>
                                <span class="label label-default"><?= $dokumen ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Upload</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Status Approval</label>
                        <div class="well well-sm aside-well">
                            <?php $approval_direktur = json_decode($tender['direktur_approval'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <button type="button" class="btn btn-color btn-success">
                                    <i class="icon mdi mdi-check-circle"></i>
                                </button>
                                <button type="button" class="btn btn-success">
                                    Direktur
                                </button>
                                <button type="button" class="btn btn-default"><?= $this->indDateTime($approval_direktur['waktu']) ?></button>
                            </div>
                            <?php $approval_manager = json_decode($tender['manajer_approval'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <button type="button" class="btn btn-color btn-success">
                                    <i class="icon mdi mdi-check-circle"></i>
                                </button>
                                <button type="button" class="btn btn-success">
                                    Manajer
                                </button>
                                <button type="button" class="btn btn-default"><?= $this->indDateTime($approval_manager['waktu']) ?></button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Dokumen RKS</label>
                        <div class="well well-sm aside-well">
                            <?php $dok_rks = json_decode($tender['rks'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <a href="public/content/rks/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-default">
                                    <?= substr($dok_rks['file'], 0, 20) ?>...<?= substr($dok_rks['file'], -4) ?>
                                </a>
                                <a href="public/content/rks/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-color btn-social btn-primary">
                                    <i class="icon mdi mdi-eye"></i> Lihat
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Dokumen RKS</label>
                        <div class="well well-sm aside-well">
                            <?php $dok_rks = json_decode($tender['berita_acara'], true); ?>
                            <div class="btn-group btn-group-xs btn-space">
                                <a href="public/content/berita-acara/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-default">
                                    <?= substr($dok_rks['file'], 0, 20) ?>...<?= substr($dok_rks['file'], -4) ?>
                                </a>
                                <a href="public/content/berita-acara/<?= $dok_rks['file'] ?>" target="_blank" class="btn btn-color btn-social btn-primary">
                                    <i class="icon mdi mdi-eye"></i> Lihat
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar BOQ
                <div class="tools">
                    <button class="btn btn-rounded btn-space btn-primary btn-sm" data-toggle="modal" data-target="#form-unitkerja">
                        <i class="mdi mdi-shopping-cart-plus"></i>
                        &nbsp; Tambah BOQ
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="unit-kerja" class="table table-striped table-hover table-fw-widget">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th>Nama Vendor</th>
                            <th>Nama Barang</th>
                            <th>Harga</th>
                            <th>Jml</th>
                            <th>Total</th>
                            <th class="text-right" width="20%">Diajukan Oleh</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="form-unitkerja" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
                    <h3 class="modal-title">Form Input BOQ</h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama Vendor</label>
                                <input type="text" placeholder="PT. XYZ" id="modal-vendor" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama Barang</label>
                                <input type="text" placeholder="GWS 55m" id="modal-barang" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="form-group">
                                <label>Harga Barang Satuan</label>
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon1">Rp</span>
                                    <input type="number" class="form-control" id="modal-harga">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Jumlah</label>
                                <input type="number" class="form-control" id="modal-volume">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Ukuran Satuan</label>
                                <select multiple="" id="modal-satuan">
                                    <optgroup label="Panjang">
                                        <option value="mm">mm</option>
                                        <option value="cm">cm</option>
                                        <option value="m">m</option>
                                        <option value="km">km</option>
                                        <option value="inch">inch(&ldquo;)</option>
                                        <option value="feet">feet</option>
                                        <option value="mile">mile</option>
                                    </optgroup>
                                    <optgroup label="Luas">
                                        <option value="mm&sup2;">mm&sup2;</option>
                                        <option value="cm&sup2;">cm&sup2;</option>
                                        <option value="m&sup2;">m&sup2;</option>
                                        <option value="km&sup2;">km&sup2;</option>
                                    </optgroup>
                                    <optgroup label="Volume">
                                        <option value="mm&sup3;">mm&sup3;</option>
                                        <option value="cm&sup3;">cm&sup3;</option>
                                        <option value="m&sup3;">m&sup3;</option>
                                        <option value="km&sup3;">km&sup3;</option>
                                    </optgroup>
                                    <optgroup label="Berat">
                                        <option value="g">g</option>
                                        <option value="ons">ons</option>
                                        <option value="kg">kg</option>
                                        <option value="pound">pound</option>
                                    </optgroup>
                                    <optgroup label="Volume Cairan">
                                        <option value="cc">cc</option>
                                        <option value="ml">ml</option>
                                        <option value="l">l</option>
                                        <option value="galon">galon</option>
                                    </optgroup>
                                    <optgroup label="Unit">
                                        <option value="Unit">Unit</option>
                                        <option value="pcs">pcs</option>
                                        <option value="lot">lot</option>
                                        <option value="dus">dus</option>
                                        <option value="kotak">kotak</option>
                                        <option value="rol">rol</option>
                                        <option value="kodi">kodi</option>
                                        <option value="rim">rim</option>
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary form-unitkerja-simpan">Tambahkan</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default md-close">Batal</button>
                </div>
            </div>
        </div>
    </div>

    <!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });

            //We use this to apply style to certain elements
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada data BOQ</h4>' +
                    '<button class="btn btn-rounded btn-space btn-primary btn-sm" data-toggle="modal" data-target="#form-unitkerja"><i class="mdi mdi-shopping-cart-plus"></i>&nbsp; Tambah BOQ </button>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });

            var unitKerja = $('#unit-kerja').DataTable({
                ajax:"<?= $this->pathFor('getBOQTender', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: "id_penawaran",
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {data:'nama_vendor'},
                    {data:'nama_barang'},
                    {
                        data:'harga_persatuan',
                        render: $.fn.dataTable.render.number( ',', '.', 2, 'Rp. ' ),
                    },
                    {
                        data:{
                            _:null,
                            sort:"volume_barang"
                        },
                        render: function (data, type, row, meta) {
                            return data.volume_barang + ' ' + data.ukuran_satuan
                        },
                    },
                    {
                        data:'total',
                        render: $.fn.dataTable.render.number( ',', '.', 2, 'Rp. ' ),
                    },
                    {
                        data: {
                            _:"pegawai",
                            sort:'pegawai.who.id_user'
                        },
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            var waktu = moment(data.time).fromNow()
                            return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + data.who.nama + '</span><span class="cell-detail-description">' + waktu + '</span>';
                        },
                    },
                ],
            });

            $('#form-unitkerja').on('show.bs.modal', function (event) {
                var mBtn = $(event.relatedTarget) // Button that triggered the modal
                var mData = mBtn.data() // Extract info from data-* attributes
                var modal = $(this)

                modal.find("#modal-satuan").select2({
                    placeholder: 'Meter',
                    width: '100%',
                    maximumSelectionLength: 1,
                    tags: true
                });

                modal.find('.form-unitkerja-simpan').on('click', function () {
                    var pegawai = modal.find('#modal-pegawai').val()
                    var penugasan = modal.find('#modal-penugasan').val()
                    $.ajax({
                        type: "POST",
                        url: '<?= $this->pathFor('setBOQTender', ['id_tender'=>$tender['id_tender']]) ?>',
                        data: {
                            nama_vendor:modal.find('#modal-vendor').val(),
                            nama_barang:modal.find('#modal-barang').val(),
                            harga_persatuan:modal.find('#modal-harga').val(),
                            volume_barang:modal.find('#modal-volume').val(),
                            ukuran_satuan:modal.find('#modal-satuan').val(),
                        },
                        success: function (result) {
                            if(result.status == 'success'){
                                unitKerja.ajax.reload();
                                modal.find('input').val('');
                                modal.find('select').val('');
                                $('#form-unitkerja').modal('hide')
                            }
                        },
                        dataType: "JSON"
                    });


                })

            })

        })

    </script>
<?php $this->stop() ?>