<html>
    <head>
        <style>
            body {
                margin:0;
                padding:20px 70px;
            }
            table{
                border-collapse: collapse;
            }
            table thead tr td{
                border: 1px solid black;
                border-bottom: 2px solid black;
                padding: 10px 5px;
                text-align: center;
            }
            table td.numbering{
                text-align: center;
            }
            table td.curency{
                text-align: right;
                padding-right: 10px;
            }
            table tbody tr td{
                border-left: 1px solid black;
                padding: 5px;
            }
            table tbody tr td:first-child{
                border-left: none;
            }
            table tfoot tr td{
                border: 1px solid black;
                padding: 5px;
            }
            table tfoot tr:first-child{
                border-top: 2px solid black;
            }
            table tfoot tr td:first-child{
                padding-left: 35px;
            }
            table tfoot tr td:last-child-child{
                text-align: right;
            }
        </style>
    </head>
    <body>
        <div style="width: 100%; text-align: center; margin-top: 10px;">
            <h3>
                BILL OF QUANTITY (BOQ)<br><br>
                Judul Tender
            </h3>
        </div>
        <table width="100%"  style="border: 2px solid black;">
            <thead>
                <tr>
                    <td width="10px">No</td>
                    <td width="500px">Uraian</td>
                    <td>Vol</td>
                    <td>Sat</td>
                    <td>Harga Material</td>
                    <td>Harga Jasa</td>
                    <td>Total</td>
                </tr>
            </thead>
            <tbody>
                <?php $i = 0; ?>
                <?php $total = 0; ?>
                <?php foreach ($BOQS as $boq): ?>
                    <tr>
                        <td class="numbering"><?= $i = $i+1 ?></td>
                        <td>
                            <strong><?= $boq['nama_vendor'] ?></strong><br>
                            <?= $boq['nama_barang'] ?>
                        </td>
                        <td class="numbering"><?= $boq['volume_barang'] ?></td>
                        <td class="numbering"><?= $boq['ukuran_satuan'] ?></td>
                        <td class="curency">Rp. <?= number_format($boq['harga_persatuan'], 2, ',', '.') ?></td>
                        <td class="curency">Rp. <?= number_format($boq['harga_jasa'], 2, ',', '.') ?></td>
                        <td class="curency">Rp. <?= number_format(($boq['harga_persatuan']*$boq['volume_barang'])+$boq['harga_jasa'], 2, ',', '.') ?></td>
                    </tr>
                    <?php $total = $total + ($boq['harga_persatuan']*$boq['volume_barang'])+$boq['harga_jasa'] ?>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Jumlah</td>
                    <td class="curency">Rp. <?= number_format($total, 2, ',', '.') ?></td>
                </tr>
                <tr>
                    <td colspan="6">PPN</td>
                    <td class="curency">Rp. <?= number_format(ceil($total*0.1), 2, ',', '.') ?></td>
                </tr>
                <tr>
                    <td colspan="6">Total</td>
                    <td class="curency">Rp. <?= number_format(ceil($total+($total*0.1)), 2, ',', '.') ?></td>
                </tr>
            </tfoot>
        </table>
    </body>
</html>