<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list
];
$this->layout ('base', $parent_data);
$this->start ('style');
?>
<link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
<!--tempat css/style-->
<?php
$this->stop ();
$this->start ('page-title');
?>
Manajemen Pengguna
<?php
$this->stop();
$this->start ('contents');
?>
<!--tempat konten-->
<div class="main-content container-fluid">
    <div class="panel panel-default panel-table">
        <div class="panel-heading">
            Daftar Pengguna
            <div class="tools">
                <a href="<?= $this->pathFor ('beritaTender_tambah') ?>" class="btn btn-space btn-primary">
                    <i class="icon icon-left mdi mdi-plus-circle-o" style="color:#fff"></i>
                    Tambah
                </a>
            </div>
        </div>
        <div class="panel-body">
            <table id="table-berita-tender" class="table table-hover table-fw-widget" style="border-top: 0px !important;">
                <thead>
                    <tr>
                        <th></th>
                        <th>Nama Pengguna</th>
                        <th>Kontak</th>
                        <th>Status</th>
                        <th>Previledge</th>
                        <th class="actions"></th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<!--akhir tempat konten-->
<?php
$this->stop ();
$this->start ('js');
?>
<!--tempat js-->

<script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
<script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        //We use this to apply style to certain elements
        $.extend( true, $.fn.dataTable.defaults, {
            dom:
            "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
            "<'row be-datatable-body'<'col-sm-12'tr>>" +
            "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
            language: {

                emptyTable: "Tidak ada data tersedia",
                lengthMenu: "Tampilkan _MENU_ data per halaman",
                "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                "info": "Hal _PAGE_ dari _PAGES_ halaman",
                "infoEmpty": "Tidak ada data tersedia",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": '<i class="mdi mdi-caret-left-circle"></i>',
                    "last": '<i class="mdi mdi-caret-right-circle"></i>',
                    "next": '<i class="mdi mdi-caret-right-circle"></i>',
                    "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                },
                "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                "searchPlaceholder": 'Cari',
            },
        });

        var userTable = $('#table-berita-tender').dataTable({
            ajax:"<?= $this->pathFor('users_get') ?>",
            columns:[
                {
                    data: "id_penawaran",
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }
                },
                {
                    data: null,
                    className: 'user-avatar cell-detail user-info',
                    render: function (data, type, row, meta) {
                        return '<img src="public/profile/' + (data.image ? data.image : 'default.png') + '" alt="Avatar"><span>' + (data.nama ? data.nama : 'Belum Mendaftar') + '</span><span class="cell-detail-description">' + (data.jabatan ? data.jabatan : 'Belum Mendaftar') + '</span>';
                    },
                },
                {
                    data:null,
                    className : "cell-detail",
                    render: function (data, type, row, meta) {
                        return  '<span>' + data.email + '</span>' +
                                '<span class="cell-detail-description">' + (data.telefon ? data.telefon : '') + '</span>'
                    },
                },
                {
                    data:'status',
                    className : "cell-detail",
                    render: function (data, type, row, meta) {
                        if(data == 1){
                            return  '<span class="label label-primary">Aktif</span>'
                        }else if(data == 0){
                            return  '<span class="label label-default">Belum Aktif</span>'
                        }
                    },
                },
                {
                    data: 'previledge',
                    className : "cell-detail",
                    render: function (data, type, row, meta) {
                        if(data == 0){
                            return  '<span class="badge">Belum Aktif</span>'
                        }else if(data == 1){
                            return  '<span class="badge badge-warning">Admin</span>'
                        }else if(data == 2){
                            return  '<span class="badge badge-primary">Direktur</span>'
                        }else if(data == 3){
                            return  '<span class="badge badge-success">Manajer</span>'
                        }else if(data == 4){
                            return  '<span class="badge badge-danger">Unit Kerja</span>'
                        }else if(data == 5){
                            return  '<span class="badge" style="color:#5f99f5 !important;">Super Admin</span>'
                        }
                    },
                },
                {
                    data:null,
                    className : "text-right",
                    render: function (data, type, row, meta) {
                        delete data.rowData;
                        return  '<button type="button" class="btn btn-danger"><i class="icon mdi mdi-delete"></i></button>'
                    },
                },
            ],
        });
    })
</script>
<?php $this->stop () ?>

