<?php
/**
 * Copyright (c) 2017.
 */

$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list
];
$this->layout ('base', $parent_data);
$this->start ('style');
?>
<link rel="stylesheet" type="text/css" href="public/assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
<style>
    div.profile-croper{
        border-radius: 10px;
        border: 3px solid #b6bcbf;
        width: 100px;
        height: 100px;
        overflow: hidden;
        margin: 10px;
        position: relative;
    }
    div.profile-croper img{
        position: absolute;
        margin: auto;
        min-height: 100%;
        min-width: 100%;


        /* For the following settings we set 100%, but it can be higher if needed
        See the answer's update */
        left: -100%;
        right: -100%;
        top: -100%;
        bottom: -100%;
    }
</style>

<!--tempat css/style-->
<?php
$this->stop ();
$this->start ('page-title');
?>
Pengaturan Pengguna
<?php
$this->stop();
$this->start ('contents');
?>
<!--tempat konten-->
<div class="main-content container-fluid">
    <div class="user-profile">
        <div class="row">
            <div class="col-md-12">
                <div class="user-display">
                    <div class="user-display-bg"><img src="public/assets/img/user-profile-display.png" alt="Profile Background"></div>
                    <div class="user-display-bottom">
                        <div class="user-display-avatar"><img src="public/profile/<?= $user['image'] ?>" alt="Avatar"></div>
                        <div class="user-display-info">
                            <div class="name"><?= $user['nama'] ?></div>
                            <div class="nick"><span class="mdi mdi-account"></span> <?= $user['username'] ?></div>
                        </div>
                    </div>
                </div>
                <div class="user-info-list panel panel-default">
                    <div class="panel-heading panel-heading-divider">
                        Pengaturan Umum
                        <div class="tools"><button class="btn btn-primary btn-sm open-common-modal">Edit</button></div>
                    </div>
                    <div class="panel-body">
                        <table class="no-border no-strip skills">
                            <tbody class="no-border-x no-border-y">
                                <tr>
                                    <td class="icon"><span class="mdi mdi-account-box-o"></span></td>
                                    <td class="item" style="width: 20%;">Foto Profil<span class="icon s7-portfolio"></span></td>
                                    <td>
                                        <div class="profile-croper">
                                            <img src="public/profile/<?= $user['image'] ?>" height="100px">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="icon"><span class="mdi mdi-pin-account"></span></td>
                                    <td class="item">Username<span class="icon s7-gift"></span></td>
                                    <td><strong><?= $user['username'] ?></strong></td>
                                </tr>
                                <tr>
                                    <td class="icon"><span class="mdi mdi-account-o"></span></td>
                                    <td class="item">Nama<span class="icon s7-phone"></span></td>
                                    <td><strong><?= $user['nama'] ?></strong></td>
                                </tr>
                                <tr>
                                    <td class="icon"><span class="mdi mdi-cake"></span></td>
                                    <td class="item">Tangal Lahir<span class="icon s7-map-marker"></span></td>
                                    <td><strong><?= $this->indDate($user['tanggal_lahir']) ?></strong></td>
                                </tr>
                                <tr>
                                    <td class="icon"><span class="mdi mdi-pin-drop"></span></td>
                                    <td class="item">Alamat<span class="icon s7-global"></span></td>
                                    <td><strong><?= $user['alamat'] ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="user-info-list panel panel-default">
                    <div class="panel-heading panel-heading-divider">
                        E-mail dan Telepon
                        <div class="tools"><button class="btn btn-primary btn-sm">Edit</button></div>
                    </div>
                    <div class="panel-body">
                        <table class="no-border no-strip skills">
                            <tbody class="no-border-x no-border-y">
                                <tr>
                                    <td class="icon"><span class="mdi mdi-email"></span></td>
                                    <td class="item" style="width: 20%;">E-mail<span class="icon s7-portfolio"></span></td>
                                    <td><strong><?= $user['email'] ?></strong></td>
                                </tr>
                                <tr>
                                    <td class="icon"><span class="mdi mdi-phone"></span></td>
                                    <td class="item">Telepon<span class="icon s7-gift"></span></td>
                                    <td><strong><?= $user['telefon'] ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="user-info-list panel panel-default">
                    <div class="panel-heading panel-heading-divider">
                        Password
                        <div class="tools"><button class="btn btn-primary btn-sm open-password-modal">Edit</button></div>
                    </div>
                    <div class="panel-body">
                        <table class="no-border no-strip skills">
                            <tbody class="no-border-x no-border-y">
                                <tr>
                                    <td class="icon"><span class="mdi mdi-key"></span></td>
                                    <td class="item" style="width: 20%;">Password<span class="icon s7-portfolio"></span></td>
                                    <td><strong><?= str_repeat ('*', strlen ($user['password'])); ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="common-modal" class="modal-container colored-header colored-header-primary modal-effect-9">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
            <h3 class="modal-title">Pengaturan Umum</h3>
        </div>
        <div class="modal-body form"  style="padding-top: 0px !important;">
            <form class="form-horizontal" method="post" action="<?= $this->pathFor('user_updateCommon'); ?>" enctype="multipart/form-data">
                <div class="form-group">
                    <label class="col-md-2 control-label" style="margin-top:40px;"><strong>Foto Profil</strong></label>
                    <div class="col-md-10">
                        <div class="profile-croper">
                            <img class="change-profile" src="public/profile/<?= $user['image'] ?>" height="100px">
                            <input type="file" name="image" hidden class="hidden" accept="image/*">
                        </div>
                        <button class="btn btn-primary change-profile" type="button" style="margin-left:16px;">Ganti Foto</button>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"><strong>Nama</strong></label>
                    <div class="col-md-10">
                        <input type="text" placeholder="Nama" value="<?= $user['nama'] ?>" name="nama" class="form-control">
                        <input type="hidden" value="<?= $user['id_user'] ?>" name="id_user">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"><strong>Tanggal Lahir</strong></label>
                    <div class="col-md-10">
                        <input class="form-control datetimepicker" value="<?= $this->indDate($user['tanggal_lahir']) ?>" type="text" style="padding-left:15px;">
                        <input id="tanggal-lahir" value="<?= $user['tanggal_lahir'] ?>" type="hidden" name="tanggal_lahir">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"><strong>Alamat</strong></label>
                    <div class="col-md-10">
                        <textarea name="alamat" cols="30" rows="3" class="form-control"><?= $user['alamat'] ?></textarea>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-default modal-close">Cancel</button>
            <button type="button" data-dismiss="modal" class="btn btn-primary btn-simpan modal-close">Simpan</button>
        </div>
    </div>
</div><div id="password-modal" class="modal-container colored-header colored-header-primary modal-effect-9">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
            <h3 class="modal-title">Pengaturan Password</h3>
        </div>
        <div class="modal-body form"  style="padding-top: 0px !important;">
            <form data-toggle="validator" class="form-horizontal" method="post" action="<?= $this->pathFor('user_updatePassword'); ?>" enctype="multipart/form-data">
                <div class="form-group has-feedback">
                    <label class="col-md-3 control-label"><strong>Password Lama</strong></label>
                    <div class="col-md-9">
                        <input type="password" placeholder="Password lama" name="old_password" class="form-control" required data-required-error="Wajib di-isi!">
                        <div class="help-block with-errors"></div>
                        <input type="hidden" value="<?= $user['id_user'] ?>" name="id_user">
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-md-3 control-label"><strong>Password Baru</strong></label>
                    <div class="col-md-9">
                        <input type="password" placeholder="Password baru" name="new_password" class="form-control" data-minlength="5" required data-minlength-error="Minimal 5 karakter!"  data-required-error="Wajib di-isi!">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group has-feedback">
                    <label class="col-md-3 control-label"><strong>Ulangi Password</strong></label>
                    <div class="col-md-9">
                        <input type="password" placeholder="Ulangi password baru" name="re_password" class="form-control" data-match='input[name="new_password"]' data-match-error="Password tidak sama!" data-required-error="Wajib di-isi!">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-default modal-close">Cancel</button>
            <button type="button" data-dismiss="modal" class="btn btn-primary btn-simpan modal-close">Simpan</button>
        </div>
    </div>
</div>
<div class="modal-overlay"></div>
<!--akhir tempat konten-->
<?php
$this->stop ();
$this->start ('js');
?>
<!--tempat js-->
<script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
<script src="public/assets/lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datetimepicker/js/locales/bootstrap-datetimepicker.id.js" type="text/javascript" charset="UTF-8"></script>
<script src="public/assets/js/jquery.form.min.js" type="text/javascript" charset="UTF-8"></script>
<script src="public/assets/js/validator.min.js" type="text/javascript" charset="UTF-8"></script>

<script>
    function previewImg(input, callback) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                callback(e.target.result)
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $(document).ready(function () {
        $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
        $.fn.niftyModal('setDefaults', {
            overlaySelector: '.modal-overlay',
            closeSelector: '.modal-close',
            classAddAfterOpen: 'modal-show',
        });

        $('.open-common-modal').on('click', function(){
            $('#common-modal').niftyModal({
                beforeOpen: function (modals) {
                    var modal = $(modals.modalEl);
                    modal.find('.change-profile').on('click', function () {
                        modal.find('input[name="image"]').click();
                        modal.find('input[name="image"]').change(function () {
                            previewImg(this, function (img) {
                                modal.find('.change-profile').attr('src', img);
                            });
                        });
                    });
                    modal.find(".datetimepicker").datetimepicker({
                        autoclose: true,
                        format: 'dd MM yyyy',
                        minView: 2,
                        componentIcon: '.mdi.mdi-calendar',
                        pickerPosition: 'top-right',
                        navIcons:{
                            rightIcon: 'mdi mdi-chevron-right',
                            leftIcon: 'mdi mdi-chevron-left'
                        },
                        language:'id',
                        linkField: "tanggal-lahir",
                        linkFormat: "yyyy-mm-dd"
                    });
                },
                buttons: [
                    {
                        class: 'btn-simpan',
                        callback: function ( btn, modals, event ) {
                            var modal = $(modals.modalEl);
                            modal.find('form').ajaxSubmit({
                                dataType: 'json',
                                success: function (res, status, xhr, $form) {
                                    console.log(res)
                                    if(res.status == 'success'){
                                        location.reload();
                                    }
                                }
                            });
                            return false;
                        }
                    }
                ],
            });
        });

        $('.open-password-modal').on('click', function() {
            $('#password-modal').niftyModal({
                buttons: [
                    {
                        class: 'btn-simpan',
                        callback: function ( btn, modals, event ) {
                            var modal = $(modals.modalEl);
                            modal.find('form').ajaxSubmit({
                                dataType: 'json',
                                beforeSubmit: function (formData, jqForm, options) {
                                    var form = jqForm[0];
                                    if(!form.old_password.value || !form.new_password.value || !form.re_password.value){
                                        modal.find('form').validator('validate');
                                        return false;
                                    }
                                },
                                success: function (res, status, xhr, $form) {
                                    console.log(res)
                                    if(res.status == 'success'){
                                        window.location.reload();
                                    }else{
                                        alert(res.reason);
                                    }
                                }
                            });
                            return false;
                        }
                    }
                ],
            })
        });



    })
</script>
<?php $this->stop () ?>

