<?php
    $parent_data = [
        'active_user_data' => $active_user_data,
        'active_notification_list' => $active_notification_list
    ];
    $this->layout ('base', $parent_data);
    $this->start ('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <!--tempat css/style-->
<?php
    $this->stop ();
    $this->start ('page-title');
?>
    Detail Berita Tender
<?php
    $this->stop ();
    $this->start ('contents');
?>
    <!--tempat konten-->
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-border-color panel-border-color-primary">
            <div class="panel-heading panel-heading-divider">
                Detail Berita Tender
                <span class="panel-subtitle"><?= $tender[ 'judul_tender' ] ?></span>
            </div>
            <div class="panel-body">
                <div class="panel panel-default panel-table">
                    <div class="panel-body">
                        <table class="table table-condensed table-hover table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <td width="20%">Tanggal</td>
                                    <td class="berita-tender-tanggal">
                                        <span class="label label-default"><?= $this->indDate ($tender[ 'tgl_mulai' ]) ?></span>
                                        s/d
                                        <span class="label label-default"><?= $this->indDate ($tender[ 'tgl_selesai' ]) ?></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Nama Penyelenggara</td>
                                    <td class="berita-tender-nama">
                                        <strong><?= $this->getNamaPenyelenggara ($tender[ 'id_penyelenggara' ]) ?></strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Judul Tender</td>
                                    <td class="berita-tender-judul">
                                        <strong><?= $tender[ 'judul_tender' ] ?></strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Link Website</td>
                                    <td class="berita-tender-link">
                                        <div class="btn-group btn-space">
                                            <a href="<?= $tender[ 'link_website' ] ?>" target="_blank" class="btn btn-color btn-social btn-twitter"><i class="icon mdi mdi-open-in-new"></i></a>
                                            <a href="<?= $tender[ 'link_website' ] ?>" target="_blank" class="btn btn-default">
                                                <?= $tender[ 'link_website' ] ?>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Lokasi</td>
                                    <td class="berita-tender-wilayah">
                                        <strong><?= $tender[ 'wilayah' ] ?></strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Dokumen Peryaratan</td>
                                    <td class="berita-tender-syarat">
                                        <?php foreach (explode ('|', $tender[ 'upload' ]) as $dokumen) { ?>
                                            <span class="label label-default"><?= $dokumen ?></span>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Unit Kerja</td>
                                    <td class="berita-tender-unit-kerja">
                                        <table class="table">
                                            <tbody>
                                                <tr>
                                                    <td class="user-avatar">
                                                        <img src="public/assets/img/avatar6.png" alt="Avatar">
                                                        <strong>Penelope Thornton</strong>
                                                    </td>
                                                    <td>Initial commit</td>
                                                </tr>
                                                <tr>
                                                    <td class="user-avatar">
                                                        <img src="public/assets/img/avatar4.png" alt="Avatar">
                                                        <strong>Benji Harper</strong>
                                                    </td>
                                                    <td>Main structure markup</td>
                                                </tr>
                                                <tr>
                                                    <td class="user-avatar">
                                                        <img src="public/assets/img/avatar5.png" alt="Avatar">
                                                        <strong>Justine Myranda</strong>
                                                    </td>
                                                    <td>Left sidebar adjusments</td>
                                                </tr>
                                                <tr>
                                                    <td class="user-avatar">
                                                        <img src="public/assets/img/avatar3.png" alt="Avatar">
                                                        <strong>Sherwood Clifford</strong>
                                                    </td>
                                                    <td>Topbar dropdown style</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Dokumen Persyaratan RKS</td>
                                    <td class="berita-tender-dokumen-syarat-rks">1.580</td>
                                </tr>
                                <tr>
                                    <td>Tanggal Upload</td>
                                    <td class="berita-tender-dibuat">
                                        <table class="table">
                                            <tr>
                                                <td class="user-avatar">
                                                    <img src="public/assets/img/<?= $this->getUserUpload ($tender[ 'id_user' ])[ 'image' ] ?>" alt="Avatar">
                                                    <span class="label label-primary"><?= $this->getUserUpload ($tender[ 'id_user' ])[ 'nama' ] ?></span>
                                                    Pada
                                                    <span class="label label-default">
                                                        <?= $this->indDateTime ($tender[ 'tgl_upload' ]) ?>
                                                    </span>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Status Approval</td>
                                    <td class="berita-tender-status-approval">
                                        <?php
                                            $approval_direktur = json_decode ($tender[ 'direktur_approval' ], true);
                                            $approval_manager = json_decode ($tender[ 'manajer_approval' ], true);
                                        ?>
                                        <div class="btn-group btn-space">
                                            <?php if ($approval_direktur == null) { ?>
                                                <button type="button" class="btn btn-color btn-default">
                                                    <i class="icon mdi mdi-circle-o"></i>
                                                </button>
                                                <button type="button" class="btn btn-default">Direktur</button>
                                                <?php if($active_user_data['previledge'] == '2') { ?>
                                                    <a href="<?= $this->pathFor('approvalBeritaTender', ['id_tender'=>$tender[ 'id_tender' ]]) ?>" class="btn btn-primary">Approve Sekarang</a>
                                                <?php }else{ ?>
                                                    <button type="button" class="btn btn-default active">Belum</button>
                                                <?php } ?>
                                            <?php } elseif ($approval_direktur[ 'status' ] == 'diterima') { ?>
                                                <button type="button" class="btn btn-color btn-success">
                                                    <i class="icon mdi mdi-check-circle"></i>
                                                </button>
                                                <button type="button" class="btn btn-success">Direktur</button>
                                                <button type="button" class="btn btn-default"><?= $this->indDateTime ($approval_direktur[ 'waktu' ]) ?></button>
                                            <?php } else { ?>
                                                <button type="button" class="btn btn-color btn-danger">
                                                    <i class="icon mdi mdi-close-circle-o"></i>
                                                </button>
                                                <button type="button" class="btn btn-danger">Direktur</button>
                                                <button type="button" class="btn btn-default"><?= $this->indDateTime ($approval_direktur[ 'waktu' ]) ?></button>
                                            <?php } ?>
                                        </div>
                                        <br>
                                        <div class="btn-group btn-space">
                                            <?php if ($approval_manager == null) { ?>
                                                <button type="button" class="btn btn-color btn-default">
                                                    <i class="icon mdi mdi-circle-o"></i>
                                                </button>
                                                <button type="button" class="btn btn-default">Manajer</button>
                                                <?php if($active_user_data['previledge'] == '3') { ?>
                                                    <a href="<?= $this->pathFor('approvalBeritaTender', ['id_tender'=>$tender[ 'id_tender' ]]) ?>" class="btn btn-primary">Approve Sekarang</a>
                                                <?php }else{ ?>
                                                <button type="button" class="btn btn-default active">Belum</button>
                                                <?php } ?>
                                            <?php } elseif ($approval_manager[ 'status' ] == 'diterima') { ?>
                                                <button type="button" class="btn btn-color btn-success">
                                                    <i class="icon mdi mdi-check-circle"></i>
                                                </button>
                                                <button type="button" class="btn btn-success">Manajer</button>
                                                <button type="button" class="btn btn-default"><?= $this->indDateTime ($approval_manager[ 'waktu' ]) ?></button>
                                            <?php } else { ?>
                                                <button type="button" class="btn btn-color btn-danger">
                                                    <i class="icon mdi mdi-close-circle-o"></i>
                                                </button>
                                                <button type="button" class="btn btn-danger">Manajer</button>
                                                <button type="button" class="btn btn-default"><?= $this->indDateTime ($approval_manager[ 'waktu' ]) ?></button>
                                            <?php } ?>
                                        </div>
                                        <br>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Status Dokumen</td>
                                    <td class="berita-tender-status-dokumen">
                                        <button class="btn btn-space btn-default btn-big col-md-12">
                                            <div class="progress">
                                                <div style="width: 70%" class="progress-bar progress-bar-primary progress-bar-striped active">
                                                    Animated 70%
                                                </div>
                                            </div>
                                            Lihat Daftar Dokumen
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!--akhir tempat konten-->
<?php
    $this->stop ();
    $this->start ('js');
?>
    <!--tempat js-->

    <script>
        $(document).ready(function () {

        })
    </script>
<?php $this->stop () ?>