<?php
    $parent_data = [
        'active_user_data' => $active_user_data,
        'active_notification_list' => $active_notification_list
    ];
    $this->layout ('base', $parent_data);
    $this->start ('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <!--tempat css/style-->
<?php
    $this->stop ();
    $this->start ('page-title');
?>
    Detail Berita Tender
<?php
    $this->stop ();
    $this->start ('contents');
?>
<?php $approve = json_decode($tender['approval'], true) ?>
    <!--tempat konten-->
    <div class="main-content container-fluid">
        <?php if($tender['deleted']): ?>
        <div role="alert" class="alert alert-danger alert-icon alert-dismissible">
            <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
            <div class="message">
                Berita Tender ini tidak aktif karena telah <b class="text-danger">dihapus</b>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($approval): ?>
            <div role="alert" class="alert alert-primary alert-icon alert-icon-colored ">
                <div class="icon"><span class="mdi mdi-info-outline"></span></div>
                <div class="message">
                    <span style="margin-top:660px;">
                        <strong>Approval!</strong>
                        Lakukan Approval terhadap berita tender ini
                    </span>
                    <div aria-label="Close" class="close" style="top:20px; opacity: 1;">
                        <button data-toggle="modal" data-target="#mod-approval" class="btn btn-rounded btn-space btn-sm btn-success" <?= $approve[$this->thisPriviledge()]['status'] == 'diterima' ? 'disabled' : '' ?> data-type="diterima" data-id="<?= $tender['id_tender'] ?>" data-judul="<?= $this->e($tender['judul_tender']) ?>">
                            <i class="icon icon-left mdi mdi-check"></i>
                            Setujui
                        </button>
                        <button data-toggle="modal" data-target="#mod-approval" class="btn btn-rounded btn-space btn-sm btn-danger" <?= $approve[$this->thisPriviledge()]['status'] == 'ditolak' ? 'disabled' : '' ?>  data-type="ditolak" data-id="<?= $tender['id_tender'] ?>" data-judul="<?= $this->e($tender['judul_tender']) ?>">
                            <i class="icon icon-left mdi mdi-close"></i>
                            Tolak
                        </button>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-6">
                <div class="user-info-list panel panel-default panel-border-color panel-border-color-primary">
                    <div class="panel-heading panel-heading-divider">
                        <div class="tools">
                            <a href="<?= $this->pathFor('beritaTender_edit', ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-space btn-primary" <?= $tender['deleted'] ? 'disabled' : '' ?>>
                                <i class="icon icon-left mdi mdi-edit" style="color:#fff;"></i>
                                Ubah
                            </a>
                        </div>
                        Berita Tender
                        <span class="panel-subtitle">
                            Informasi Pokok Berita Tender
                        </span>
                    </div>
                    <div class="panel-body">
                        <table class="no-border no-strip skills">
                            <tbody class="no-border-x no-border-y">
                                <tr>
                                    <td class="icon" valign="top"><span class="mdi mdi-info-outline"></span></td>
                                    <td class="item" valign="top" style="width:25%"><strong>Judul Tender</strong></td>
                                    <td><?= $tender[ 'judul_tender' ] ?></td>
                                </tr>
                                <tr>
                                    <td class="icon" valign="top"><span class="mdi mdi-city-alt"></span></td>
                                    <td class="item" valign="top"><strong>Penyelenggara</strong></td>
                                    <td><?= $this->getNamaPenyelenggara ($tender[ 'id_penyelenggara' ]) ?></td>
                                </tr>
                                <tr>
                                    <td class="icon" valign="top"><span class="mdi mdi-pin"></span></td>
                                    <td class="item" valign="top"><strong>Wilayah</strong></td>
                                    <td><?= $tender[ 'wilayah' ] ?></td>
                                </tr>
                                <tr>
                                    <td class="icon" valign="top"><span class="mdi mdi-calendar-check"></span></td>
                                    <td class="item" valign="top"><strong>Waktu</strong></td>
                                    <td>
                                        <span class="label label-default"><?= $this->indDate ($tender[ 'tgl_mulai' ]) ?></span>
                                        s/d
                                        <span class="label label-default"><?= $this->indDate ($tender[ 'tgl_selesai' ]) ?></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="icon" valign="top"><span class="mdi mdi-link"></span></td>
                                    <td class="item" valign="top"><strong>Website</strong></td>
                                    <td>
                                        <a href="<?= $tender[ 'link_website' ] ?>" target="_blank"><?= substr($tender[ 'link_website' ], 0, 50) ?></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" align="center" style="padding-top:20px;">
                                        <strong>Persetujuan</strong>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="col-md-6" align="center">
                            <b>Direktur</b>
                            <br>
                            <p style="padding: 10px 0 0 0;">
                                <i class="icon mdi <?= $approve['direktur']['status'] == '' ? 'mdi-circle-o text-muted' : ($approve['direktur']['status'] == 'diterima' ? 'mdi-check-circle text-success' : 'mdi-close-circle-o text-danger') ?>" style="font-size: 5em;"></i>
                            </p>
                            <br>
                            <ins><b><?= $this->getDirektur()['nama'] ?></b></ins><br>
                            <span><?= $approve['direktur']['waktu'] == '' ? 'Belum Melakukan Approval' : $this->indDate ($approve['direktur']['waktu']) ?></span><br>
                        </div>
                        <div class="col-md-6" align="center">
                            <b>Manajer</b>
                            <br>
                            <p style="padding: 10px 0 0 0;">
                                <i class="icon mdi <?= $approve['manajer']['status'] == '' ? 'mdi-circle-o text-muted' : ($approve['manajer']['status'] == 'diterima' ? 'mdi-check-circle text-success' : 'mdi-close-circle-o text-danger') ?>" style="font-size: 5em;"></i>
                            </p>
                            <br>
                            <ins><b><?= $this->getManajer()['nama'] ?></b></ins><br>
                            <span><?= $approve['manajer']['waktu'] == '' ? 'Belum Melakukan Approval' : $this->indDate ($approve['manajer']['waktu']) ?></span><br>
                        </div>
                    </div>
                </div>
                <div class="panel panel-contrast panel-table">
                    <div class="panel-heading panel-heading-contrast">
                        Dokumen Kelengkapan
                        <!--                        <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>-->
                        <span class="panel-subtitle">
                            Daftar dokumen persyaratan tender
                        </span>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-borderless">
                            <thead>
                                <tr>
                                    <th class="actions"></th>
                                    <th style="width:60%;">Nama Dokumen</th>
                                    <th style="width:40%;">Status</th>
                                </tr>
                            </thead>
                            <tbody class="no-border-x">
                                <?php foreach ($tender['dokumen_syarat'] as $key => $dokumen): ?>
                                    <?php $dokumen['approval'] = json_decode($dokumen['approval'], true); ?>
                                    <tr>
                                        <td><?= $key+1 ?></td>
                                        <td class="cell-detail">
                                            <span><?= $dokumen['nama_dokumen'] ?></span>
                                            <?php if($dokumen['dokumen_syarat'] == '0'): ?>
                                                <span class="cell-detail-description">Dokumen Tambahan</span>
                                            <?php endif; ?>
                                        </td>
                                        <td class="milestone">
                                            <span class="version"><?= !$dokumen['file_dokumen'] ? 'Menunggu Upload' : (!$dokumen['approval'] ? 'Menuggu Approval' : ($dokumen['approval']['manajer']['status'] == '' && $dokumen['approval']['direktur']['status'] == '' ? 'Menuggu Approval' : ($dokumen['approval']['manajer']['status'] == '' || $dokumen['approval']['direktur']['status'] == '' ? 'Kurang Satu Approval' : 'Selesai' ) )) ?></span>
                                            <div class="progress">
                                                <?php
                                                $progress = 1;
                                                if($dokumen['file_dokumen']){
                                                    $progress=$progress+33;
                                                    if($dokumen['approval'] and $dokumen['approval']['direktur']['status'] != ''){
                                                        $progress = $progress + 33;
                                                    }
                                                    if($dokumen['approval'] and $dokumen['approval']['manajer']['status'] != ''){
                                                        $progress = $progress + 33;
                                                    }
                                                }
                                                ?>
                                                <div style="width: <?= $progress ?>%" class="progress-bar progress-bar-primary"></div>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-contrast panel-table">
                    <div class="panel-heading panel-heading-contrast panel-heading-divider">
                        Infromasi Berita Tender
                        <!--                        <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>-->
                        <span class="panel-subtitle">
                            Daftar informasi tambahan berita tender
                        </span>
                    </div>
                    <div class="panel-body">
                        <table class="table table-borderless">
                            <tbody class="no-border-x">
                                <tr>
                                    <td width="35%"><b>Ditambahkan Oleh</b></td>
                                    <td class="user-avatar cell-detail user-info" colspan="3">
                                        <img src="public/profile/<?= $this->getUserUpload ($tender[ 'id_user' ])[ 'image' ] ?>" alt="Avatar">
                                        <span><?= ($tender[ 'id_user' ] == $active_user_data['id_user'] ? 'Anda Sendiri' : $this->getUserUpload ($tender[ 'id_user' ])[ 'nama' ]) ?></span>
                                        <span class="cell-detail-description"><?= $this->indDateTime ($tender[ 'tgl_upload' ]) ?></span>
                                    </td>
                                </tr>
                                <?php if($tender['last_edit']): ?>
                                    <tr>
                                        <td width="35%"><b>Terakhir Diubah Oleh</b></td>
                                        <td class="user-avatar cell-detail user-info" colspan="3">
                                            <img src="public/profile/<?= $this->getUserUpload ($tender['last_edit'][ 'id_user' ])[ 'image' ] ?>" alt="Avatar">
                                            <span><?= ($tender['last_edit'][ 'id_user' ] == $active_user_data['id_user'] ? 'Anda Sendiri' : $this->getUserUpload ($tender['last_edit'][ 'id_user' ])[ 'nama' ]) ?></span>
                                            <span class="cell-detail-description"><?= $this->indDateTime ($tender['last_edit'][ 'waktu' ]) ?></span>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <tr>
                                    <td style="vertical-align: top !important;"><b>Dokumen RKS</b></td>
                                    <td colspan="3">
                                        <?php $rks = json_decode($tender['rks'], true) ?>
                                        <?php if($rks['file']): ?>
                                            <div class="embed-responsive embed-responsive-16by9">
                                                <iframe class="embed-responsive-item" src="public/content/dokumen/<?= $rks['file'] ?>"></iframe>
                                            </div>
                                        <?php else: ?>
                                            <span class="text-muted">Belum Ditambahkan</span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="vertical-align: top !important;"><b>Berita Acara</b></td>
                                    <td colspan="3">
                                        <?php $berita_acara = json_decode($tender['berita_acara'], true) ?>
                                        <?php if($berita_acara['file']): ?>
                                            <div class="embed-responsive embed-responsive-16by9">
                                                <iframe class="embed-responsive-item" src="public/content/dokumen/<?= $berita_acara['file'] ?>"></iframe>
                                            </div>
                                        <?php else: ?>
                                            <span class="text-muted">Belum Ditambahkan</span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel panel-contrast panel-table">
                    <div class="panel-heading panel-heading-contrast">
                        Unit Kerja
                        <!--                        <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>-->
                        <span class="panel-subtitle">
                            Daftar unit kerja dan penugasan-nya
                        </span>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped table-borderless">
                            <thead>
                                <tr>
                                    <th class="actions"></th>
                                    <th style="width:60%;">Unit Kerja</th>
                                    <th style="width:40%;">Penugasan</th>
                                </tr>
                            </thead>
                            <tbody class="no-border-x">
                                <?php foreach ($tender['unit_kerja'] as $key => $unit_kerja): ?>
                                    <tr>
                                        <td><?= $key+1 ?></td>
                                        <td class="user-avatar">
                                            <img src="public/profile/<?= $this->getUserUpload ($unit_kerja[ 'id_user' ])[ 'image' ] ?>" alt="Avatar">
                                            <?= $this->getUserUpload ($unit_kerja[ 'id_user' ])[ 'nama' ] ?>
                                        </td>
                                        <td><span class="label label-primary"><?= $unit_kerja['penugasan'] ?></span></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <ul class="timeline timeline-variant mod">
                    <li class="timeline-month"><span>History Perubahan</span></li>
                    <?php foreach ($tender['history'] as $history): ?>
                        <li class="timeline-item right">
                            <div class="timeline-content timeline-type file">
                                <div class="timeline-icon"><i class="icon mdi mdi-file"></i></div>
                                <div class="timeline-avatar"><img src="public/profile/<?= $this->getUserUpload ($history[ 'id_user' ])[ 'image' ] ?>" alt="Avatar" class="circle"></div>
                                <div class="timeline-header"><span class="timeline-autor"><?= $this->getUserUpload ($history[ 'id_user' ])[ 'nama' ] ?></span>
                                    <p class="timeline-activity">
                                        <?php switch($history['perubahan']):
                                            case 'u_tender': ?>
                                                Mengubah berita tender
                                                <a href="<?= $this->pathFor('beritaTender_detail', ['id_tender'=>$tender['id_tender']]) ?>">
                                                    <?= $history['detail']['judul_tender'] ?>
                                                </a>
                                                <?php break;?>
                                        <?php endswitch; ?>
                                    </p>
                                    <span class="timeline-time"><?= $this->indDateTime ($history['waktu']) ?></span>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="col-md-12 <?= $tender['deleted'] ? 'hidden' : '' ?>">
                <div class="panel panel-border-color panel-border-color-danger">
                    <div class="panel-heading">
                        Hapus Berita Tender
                        <span class="panel-subtitle">Menghapus Berita Tender ini juga akan menghapus semua data dan informasi yang berhubungan dengan berita tender ini </span>
                    </div>
                    <div class="panel-body">
                        <button class="btn btn-space btn-danger hover"  data-toggle="modal" data-target="#modal-hapus">
                            <i class="icon icon-left mdi mdi-delete"></i>
                            Hapus
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="mod-approval" tabindex="-1" role="dialog" style="display: none;" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <div class="mod-icon"><span class="modal-main-icon mdi mdi-check"></span></div>
                        <h3>Awesome!</h3>
                        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>Fusce ultrices euismod lobortis.</p>
                        <div class="xs-mt-50">
                            <button type="button" data-dismiss="modal" class="btn btn-space btn-action">Proceed</button>
                            <button type="button" data-dismiss="modal" class="btn btn-space btn-default">Batal</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
    <div id="form-unitkerja" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
                    <h3 class="modal-title">Form Input BOQ</h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama Vendor</label>
                                <input type="text" placeholder="PT. XYZ" id="modal-vendor" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nama Barang</label>
                                <input type="text" placeholder="GWS 55m" id="modal-barang" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="form-group">
                                <label>Harga Barang Satuan</label>
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon1">Rp</span>
                                    <input type="number" class="form-control" id="modal-harga">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Jumlah</label>
                                <input type="number" class="form-control" id="modal-volume">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Ukuran Satuan</label>
                                <select multiple="" id="modal-satuan">
                                    <optgroup label="Panjang">
                                        <option value="mm">mm</option>
                                        <option value="cm">cm</option>
                                        <option value="m">m</option>
                                        <option value="km">km</option>
                                        <option value="inch">inch(&ldquo;)</option>
                                        <option value="feet">feet</option>
                                        <option value="mile">mile</option>
                                    </optgroup>
                                    <optgroup label="Luas">
                                        <option value="mm&sup2;">mm&sup2;</option>
                                        <option value="cm&sup2;">cm&sup2;</option>
                                        <option value="m&sup2;">m&sup2;</option>
                                        <option value="km&sup2;">km&sup2;</option>
                                    </optgroup>
                                    <optgroup label="Volume">
                                        <option value="mm&sup3;">mm&sup3;</option>
                                        <option value="cm&sup3;">cm&sup3;</option>
                                        <option value="m&sup3;">m&sup3;</option>
                                        <option value="km&sup3;">km&sup3;</option>
                                    </optgroup>
                                    <optgroup label="Berat">
                                        <option value="g">g</option>
                                        <option value="ons">ons</option>
                                        <option value="kg">kg</option>
                                        <option value="pound">pound</option>
                                    </optgroup>
                                    <optgroup label="Volume Cairan">
                                        <option value="cc">cc</option>
                                        <option value="ml">ml</option>
                                        <option value="l">l</option>
                                        <option value="galon">galon</option>
                                    </optgroup>
                                    <optgroup label="Unit">
                                        <option value="Unit">Unit</option>
                                        <option value="pcs">pcs</option>
                                        <option value="lot">lot</option>
                                        <option value="dus">dus</option>
                                        <option value="kotak">kotak</option>
                                        <option value="rol">rol</option>
                                        <option value="kodi">kodi</option>
                                        <option value="rim">rim</option>
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary form-unitkerja-simpan">Tambahkan</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default md-close">Batal</button>
                </div>
            </div>
        </div>
    </div>
    <div id="modal-hapus" tabindex="-1" role="dialog" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <div class="text-danger"><span class="modal-main-icon mdi mdi-delete"></span></div>
                        <h3>Hapus Berita Tender!</h3>
                        <p>Apakah anda yakin akan menghapus tender <strong><?= $tender['judul_tender']; ?></strong>?</p>
                        <p>Menghapus tender akan menghapus semua progress terhadap tender ini.</p>
                        <div class="xs-mt-50">
                            <button type="button" data-dismiss="modal" class="btn btn-space btn-default">Cancel</button>
                            <button type="button" data-dismiss="modal" class="btn btn-space btn-danger btn-hapus">Hapus</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
    <!--akhir tempat konten-->
<?php
    $this->stop ();
    $this->start ('js');
?>
    <!--tempat js-->

    <script>
        $(document).ready(function () {
            $('#modal-hapus').on('show.bs.modal', function (event) {
                var modal = $(this);
                modal.find('.btn-hapus').on('click', function(){
                    $.post('<?= $this->pathFor('beritaTender_hapus') ?>', {'id_tender':'<?= $tender['id_tender']; ?>'}, function(data){
                        if(data.status == 'success'){
                            window.location.replace('<?= $this->pathFor('beritaTender_daftar') ?>');
                        }
                    }, 'json');
                })

            });
            $('#mod-approval').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget);
                var modData = button.data();
                var modal = $(this);
                modal.find('p').html(modData.judul);
                if(modData.type == 'diterima'){
                    modal.find('h3').html("Setujui Berita Tender Ini ?");
                    modal.find('.mod-icon').addClass('text-success');
                    modal.find('.mod-icon').removeClass('text-danger');
                    modal.find('.btn-action').addClass('btn-success');
                    modal.find('.btn-action').removeClass('btn-danger');
                    modal.find('.btn-action').html('Setujui');
                }
                if(modData.type == 'ditolak'){
                    modal.find('h3').html("Tolak Berita Tender Ini ?");
                    modal.find('.mod-icon').removeClass('text-success');
                    modal.find('.mod-icon').addClass('text-danger');
                    modal.find('.btn-action').removeClass('btn-success');
                    modal.find('.btn-action').addClass('btn-danger');
                    modal.find('.btn-action').html('Tolak');
                }
                modal.find('.btn-action').on('click', function () {
                    var who = '';
                    if(active_user.previledge == '2'){
                        who = 'direktur'
                    }else if(active_user.previledge == '3'){
                        who = 'manajer'
                    }
                    $.post(
                        '<?= $this->pathFor('beritaTender_approval', ['id_tender'=>$tender['id_tender']]) ?>',
                        {
                            who:who,
                            status:modData.type
                        },
                        function(data){
                            if(data.status == 'success'){
                                location.reload();
                            }
                        },
                        "json"
                    )
                });
            });
        })
    </script>
<?php $this->stop () ?>