<ul class="timeline timeline-variant <?= $full ? '' : 'mod' ?>">
    <li class="timeline-month"><span>History Perubahan</span></li>
    <?php $count = 0; ?>
    <?php $id_tender = ''; ?>
    <?php $month_group = ''; ?>
    <?php foreach ($histories as $history): ?>
        <?php $id_tender = $history['id_tender']; ?>
        <?php if($full and $this->indMonthYear($history['waktu']) <> $month_group):?>
            <?php $month_group = $this->indMonthYear($history['waktu']); ?>
            <li class="timeline-month"><span><?= $month_group ?></span></li>
        <?php endif; ?>
        <li class="timeline-item <?= $full && $count % 2 == 0 ? 'left' : 'right' ?>">
            <?php if($history['perubahan'] == 'i_tender'): ?>
                    <div class="timeline-content timeline-type file">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Membuat berita tender ini
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'e_tender'): ?>
                    <div class="timeline-content timeline-type comment">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengubah berita tender ini
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'd_tender'): ?>
                    <div class="timeline-content timeline-type quote">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menghapus berita tender ini
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'a_tender'): ?>
                    <div class="timeline-content timeline-type gallery">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Melakukan approval terhadap berita tender ini
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <?php $a_tender_meta = json_decode($history['meta'], true); ?>
                            <div role="alert" class="alert <?= $a_tender_meta['status'] == 'diterima' ? 'alert-success' : 'alert-danger' ?> alert-icon alert-icon-border alert-dismissible">
                                <div class="icon"><span class="mdi <?= $a_tender_meta['status'] == 'diterima' ? 'mdi-check' : 'mdi-close-circle-o' ?>"></span></div>
                                <div class="message">
                                    <strong><?= ucfirst($a_tender_meta['status']) ?></strong><br><?= $a_tender_meta['keterangan'] ?>
                                </div>
                            </div>
                        </div>
                    </div>


            <?php elseif($history['perubahan'] == 'i_rks'): ?>
                    <div class="timeline-content timeline-type file">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengupload dokumen RKS&nbsp;
                                <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                    <?= json_decode($history['detail']['rks'], true)['file'] ?>
                                </a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'e_rks'): ?>
                    <div class="timeline-content timeline-type comment">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengganti dokumen RKS&nbsp;
                                <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                    <?= json_decode($history['detail']['rks'], true)['file'] ?>
                                </a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'a_rks'): ?>
                    <div class="timeline-content timeline-type gallery">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Melakukan approval dokumen RKS&nbsp;
                                <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                    <?= json_decode($history['detail']['rks'], true)['file'] ?>
                                </a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <?php $r_tender_meta = json_decode($history['meta'], true); ?>
                            <div role="alert" class="alert <?= $r_tender_meta['status'] == 'diterima' ? 'alert-success' : 'alert-danger' ?> alert-icon alert-icon-border alert-dismissible">
                                <div class="icon"><span class="mdi <?= $r_tender_meta['status'] == 'diterima' ? 'mdi-check' : 'mdi-close-circle-o' ?>"></span></div>
                                <div class="message">
                                    <strong><?= ucfirst($r_tender_meta['status']) ?></strong><br><?= $r_tender_meta['keterangan'] ?>
                                </div>
                            </div>
                        </div>
                    </div>


            <?php elseif($history['perubahan'] == 'i_acara'): ?>
                    <div class="timeline-content timeline-type file">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengupload dokumen Berita Acara&nbsp;
                                <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                    <?= json_decode($history['detail']['rks'], true)['file'] ?>
                                </a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'e_acara'): ?>
                    <div class="timeline-content timeline-type comment">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengganti dokumen Berita Acara&nbsp;
                                <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                    <?= json_decode($history['detail']['rks'], true)['file'] ?>
                                </a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>


            <?php elseif($history['perubahan'] == 'i_unit'): ?>
                    <div class="timeline-content timeline-type file">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menugaskan
                                <a href="<?= $this->pathFor('unitKerja_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $this->user_detail($history['detail']['id_user'])['nama'] ?></a>
                                dengan tugas
                                <span class="text-primary"><?= $history['detail']['penugasan'] ?></span>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <td>Nama</td>
                                        <td>Penugasan</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="user-avatar">
                                            <img src="public/profile/<?= $this->userDetailHelper($history['extra']['id_user'])['image'] ?>" alt="Avatar">
                                            <?= $this->userDetailHelper($history['extra']['id_user'])['nama'] ?>
                                        </td>
                                        <td><?= $history['extra']['penugasan'] ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'd_unit'): ?>
                    <div class="timeline-content timeline-type quote">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menghapus
                                <a href="<?= $this->pathFor('unitKerja_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $this->user_detail($history['detail']['id_user'])['nama'] ?></a>
                                dari tugas
                                <span class="text-primary"><?= $history['detail']['penugasan'] ?></span>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <td>Nama</td>
                                        <td>Penugasan</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="user-avatar">
                                            <img src="public/profile/<?= $this->userDetailHelper($history['extra']['id_user'])['image'] ?>" alt="Avatar">
                                            <?= $this->userDetailHelper($history['extra']['id_user'])['nama'] ?>
                                        </td>
                                        <td><?= $history['extra']['penugasan'] ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>


                
            <?php elseif($history['perubahan'] == 'i_dok'): ?>
                    <div class="timeline-content timeline-type file">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menambahkan dokumen
                                <a href="<?= $this->pathFor('dokumenTender_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $history['detail']['nama_dokumen'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'u_dok'): ?>
                    <div class="timeline-content timeline-type quote">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengupload
                                <span class="text-primary"><?= $history['detail']['file_dokumen'] ?></span>
                                sebagai dokumen
                                <a href="<?= $this->pathFor('dokumenTender_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $history['detail']['nama_dokumen'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'e_dok'): ?>
                    <div class="timeline-content timeline-type comment">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengubah dokumen
                                <a href="<?= $this->pathFor('dokumenTender_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $history['detail']['nama_dokumen'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'd_dok'): ?>
                    <div class="timeline-content timeline-type quote">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menghapus dokumen
                                <a href="<?= $this->pathFor('dokumenTender_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $this->user_detail($history['detail']['id_user'])['nama'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'a_dok'): ?>
                <div class="timeline-content timeline-type gallery">
                    <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                    <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                    <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                        <p class="timeline-activity">
                            Melakukan approval dokumen RKS&nbsp;
                            <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                <?= $history['detail']['file_dokumen'] ?>
                            </a>
                        </p>
                        <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                    </div>
                    <div class="timeline-summary">
                        <?php $d_tender_meta = json_decode($history['meta'], true); ?>
                        <div role="alert" class="alert <?= $d_tender_meta['status'] == 'diterima' ? 'alert-success' : 'alert-danger' ?> alert-icon alert-icon-border alert-dismissible">
                            <div class="icon"><span class="mdi <?= $d_tender_meta['status'] == 'diterima' ? 'mdi-check' : 'mdi-close-circle-o' ?>"></span></div>
                            <div class="message">
                                <strong><?= ucfirst($d_tender_meta['status']) ?></strong><br><?= $d_tender_meta['keterangan'] ?>
                            </div>
                        </div>
                    </div>
                </div>



            <?php elseif($history['perubahan'] == 'i_boq'): ?>
                    <div class="timeline-content timeline-type file">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menambahkan penawaran BOQ
                                <a href="<?= $this->pathFor('unitKerja_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $history['detail']['nama_vendor'] ?> - <?= $history['detail']['nama_barang'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <table class="table">
                                <tr>
                                    <td width="50%"><?= $history['extra']['nama_vendor'] ?></td>
                                    <td width="50%"><?= $history['extra']['nama_barang'] ?></td>
                                </tr>
                                <tr>
                                    <td width="50%">Rp. <?= $history['extra']['harga_persatuan'] ?>/<?= $history['extra']['ukuran_satuan'] ?></td>
                                    <td width="50%"><?= $history['extra']['volume_barang'] ?><?= $history['extra']['ukuran_satuan'] ?></td>
                                </tr>
                            </table>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'e_boq'): ?>
                    <div class="timeline-content timeline-type comment">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Mengubah penawaran BOQ
                                <a href="<?= $this->pathFor('unitKerja_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $history['detail']['nama_vendor'] ?> - <?= $history['detail']['nama_barang'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <table class="table">
                                <tr>
                                    <td width="50%"><?= $history['extra']['nama_vendor'] ?></td>
                                    <td width="50%"><?= $history['extra']['nama_barang'] ?></td>
                                </tr>
                                <tr>
                                    <td width="50%">Rp. <?= $history['extra']['harga_persatuan'] ?>/<?= $history['extra']['ukuran_satuan'] ?></td>
                                    <td width="50%"><?= $history['extra']['volume_barang'] ?><?= $history['extra']['ukuran_satuan'] ?></td>
                                </tr>
                            </table>
                        </div>
                    </div>
            <?php elseif($history['perubahan'] == 'd_boq'): ?>
                    <div class="timeline-content timeline-type quote">
                        <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                        <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                        <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                            <p class="timeline-activity">
                                Menghapus penawaran BOQ
                                <a href="<?= $this->pathFor('unitKerja_detail', ['id_tender'=>$history['id_tender']]) ?>"><?= $history['detail']['nama_vendor'] ?> - <?= $history['detail']['nama_barang'] ?></a>
                            </p>
                            <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                        </div>
                        <div class="timeline-summary">
                            <table class="table">
                                <tr>
                                    <td width="50%"><?= $history['extra']['nama_vendor'] ?></td>
                                    <td width="50%"><?= $history['extra']['nama_barang'] ?></td>
                                </tr>
                                <tr>
                                    <td width="50%">Rp. <?= $history['extra']['harga_persatuan'] ?>/<?= $history['extra']['ukuran_satuan'] ?></td>
                                    <td width="50%"><?= $history['extra']['volume_barang'] ?><?= $history['extra']['ukuran_satuan'] ?></td>
                                </tr>
                            </table>
                        </div>
                    </div>

            <?php elseif($history['perubahan'] == 'a_boq'): ?>
                <div class="timeline-content timeline-type gallery">
                    <div class="timeline-icon"><i class="icon mdi mdi-assignment"></i></div>
                    <div class="timeline-avatar"><img src="public/profile/<?= $this->user_detail($history['id_user'], 'image') ?>" alt="Avatar" class="circle"></div>
                    <div class="timeline-header"><span class="timeline-autor"><?= $this->user_detail($history['id_user'], 'nama') ?></span>
                        <p class="timeline-activity">
                            Melakukan approval penawaran BOQ&nbsp;
                            <a href="<?= $this->pathFor('rksAcara_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                <?= $history['detail']['nama_vendor'] ?> - <?= $history['detail']['nama_barang'] ?>
                            </a>
                        </p>
                        <span class="timeline-time"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                    </div>
                    <div class="timeline-summary">
                        <table class="table">
                            <tr>
                                <td width="50%"><?= $history['extra']['nama_vendor'] ?></td>
                                <td width="50%"><?= $history['extra']['nama_barang'] ?></td>
                            </tr>
                            <tr>
                                <td width="50%">Rp. <?= $history['extra']['harga_persatuan'] ?>/<?= $history['extra']['ukuran_satuan'] ?></td>
                                <td width="50%"><?= $history['extra']['volume_barang'] ?><?= $history['extra']['ukuran_satuan'] ?></td>
                            </tr>
                        </table>
                        <?php $b_tender_meta = json_decode($history['meta'], true); ?>
                        <div role="alert" class="alert <?= $b_tender_meta['status'] == 'diterima' ? 'alert-success' : 'alert-danger' ?> alert-icon alert-icon-border alert-dismissible">
                            <div class="icon"><span class="mdi <?= $b_tender_meta['status'] == 'diterima' ? 'mdi-check' : 'mdi-close-circle-o' ?>"></span></div>
                            <div class="message">
                                <strong><?= ucfirst($b_tender_meta['status']) ?></strong><br><?= $b_tender_meta['keterangan'] ?>
                            </div>
                        </div>
                    </div>
                </div>


            <?php endif; ?>
        </li>
        <?php $count++ ?>
        <?php if(!$full && $count == 5){
            break;
        } ?>
    <?php endforeach; ?>
    <?php if($histories && !$full): ?>
        <li class="timeline-item timeline-loadmore"><a href="<?= $this->pathFor('beritaTender_history', ['id_tender'=>$id_tender]) ?>" class="load-more-btn">Lihat Lainnya</a></li>
    <?php endif; ?>
</ul>