<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list
];
$this->layout ('base', $parent_data);
$this->start ('style');
?>
<link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
<!--tempat css/style-->
<?php
$this->stop ();
$this->start ('page-title');
?>
Daftar Approval Dokumen RKS Berita Tender
<?php
$this->stop();
$this->start ('contents');
?>
<!--tempat konten-->
<div class="main-content container-fluid">
    <div role="alert" class="alert alert-primary alert-simple alert-dismissible">
        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true" class="mdi mdi-close"></span>
        </button>
        <span class="icon mdi mdi-info-outline"></span>
        <strong>info!</strong> Status Aprroval &nbsp;
        <div class="btn-group btn-space">
            <a class="btn btn-default btn-xs"><i class="icon mdi mdi-circle-o" style="margin-right: 0 !important; color: #646464"></i> </a>
            <a class="btn btn-default btn-xs">Belum Approval</a>
        </div>
        <div class="btn-group btn-space">
            <a class="btn btn-success btn-xs"><i class="icon mdi mdi-check-circle" style="margin-right: 0 !important;"></i></a>
            <a class="btn btn-default btn-xs">Diterima</a>
        </div>
        <div class="btn-group btn-space">
            <a class="btn btn-danger btn-xs"><i class="icon mdi mdi-close-circle-o" style="margin-right: 0 !important;"></i></a>
            <a class="btn btn-default btn-xs">Ditolak</a>
        </div>
    </div>
    <div class="panel panel-default panel-table">
        <div class="panel-body">
            <table id="table-berita-tender" class="table table-hover table-fw-widget" style="border-top: 0px !important;">
                <thead>
                <tr>
                    <th></th>
                    <th width="50%">Judul</th>
                    <th width="10%">Mulai</th>
                    <th width="10%">Selesai</th>
                    <th width="10%">Penyelenggara</th>
                    <th width="10%">Status</th>
                    <th width="10%" class="text-center">Approval Anda</th>
                </tr>
                </thead>
                <tbody>
                <?php $i=1; ?>
                <?php foreach(array_reverse($beritaTender) as $tender): ?>
                    <?php $RKS = json_decode ($tender[ 'rks' ], true); ?>
                    <?php if(is_array($RKS)): ?>
                        <tr class="<?= ($this->dateAboveNow($tender['tgl_selesai']) ? null : 'text-muted') ?>">
                            <td><?= $i ?></td>
                            <td onclick="document.location = '<?= $this->pathFor('detailBeritaTender' , ['id_tender'=>$tender['id_tender']]) ?>'" style="cursor: pointer;">
                                <?= $tender['judul_tender'] ?>
                            </td>
                            <td><?= $this->indDate($tender['tgl_mulai']) ?></td>
                            <td><?= $this->indDate($tender['tgl_selesai']) ?></td>
                            <td><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></td>
                            <td class="milestone text-center">
                                <span class="completed">
                                    Direktur<br>
                                    <?php if ($RKS['approval']['direktur']['status'] == ''): ?>
                                        <button type="button" class="btn btn-default btn-xs"><i class="icon mdi mdi-circle-o"></i> </button>
                                    <?php elseif ($RKS['approval']['direktur']['status'] == 'diterima'): ?>
                                        <button type="button" class="btn btn-success btn-xs"><i class="icon mdi mdi-check-circle"></i></button>
                                    <?php else: ?>
                                        <button type="button" class="btn btn-danger btn-xs"><i class="icon mdi mdi-close-circle-o"></i></button>
                                    <?php endif; ?>
                                </span>
                                <span class="version">
                                    Manajer<br>
                                    <?php if ($RKS['approval']['manajer']['status'] == ''): ?>
                                        <button type="button" class="btn btn-default btn-xs"><i class="icon mdi mdi-circle-o"></i> </button>
                                    <?php elseif ($RKS['approval']['manajer']['status'] == 'diterima'): ?>
                                        <button type="button" class="btn btn-success btn-xs"><i class="icon mdi mdi-check-circle"></i></button>
                                    <?php else: ?>
                                        <button type="button" class="btn btn-danger btn-xs"><i class="icon mdi mdi-close-circle-o"></i></button>
                                    <?php endif; ?>
                                </span>
                            </td>
                            <td class="text-center">
                                <div class="btn-group btn-space">
                                    <?php if($active_user_data['previledge'] == '2'): ?>
                                        <?php if ($RKS['approval']['direktur']['status'] == ''): ?>
                                            <a href="<?= $this->pathFor('approvalRKSTender' , ['id_tender'=>$tender['id_tender']]) ?>"  class="btn btn-primary  btn-sm">Approve</a>
                                        <?php else: ?>
                                            <a href="<?= $this->pathFor('approvalRKSTender' , ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-default  btn-sm">Lihat</a>
                                        <?php endif; ?>
                                    <?php elseif ($active_user_data['previledge'] == '3'): ?>
                                        <?php if ($RKS['approval']['manajer']['status'] == ''): ?>
                                            <a href="<?= $this->pathFor('approvalRKSTender' , ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-primary  btn-sm">Approve</a>
                                        <?php else: ?>
                                            <a href="<?= $this->pathFor('approvalRKSTender' , ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-default  btn-sm">Lihat</a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                        <?php $i++; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!--akhir tempat konten-->
<?php
$this->stop ();
$this->start ('js');
?>
<!--tempat js-->

<script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
<script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        //We use this to apply style to certain elements
        $.extend( true, $.fn.dataTable.defaults, {
            dom:
            "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
            "<'row be-datatable-body'<'col-sm-12'tr>>" +
            "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
            language: {

                emptyTable: "Tidak ada data tersedia",
                lengthMenu: "Tampilkan _MENU_ data per halaman",
                "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                "info": "Hal _PAGE_ dari _PAGES_ halaman",
                "infoEmpty": "Tidak ada data tersedia",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": '<i class="mdi mdi-caret-left-circle"></i>',
                    "last": '<i class="mdi mdi-caret-right-circle"></i>',
                    "next": '<i class="mdi mdi-caret-right-circle"></i>',
                    "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                },
                "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                "searchPlaceholder": 'Cari',
            },
        });

        var beritaTable = $('#table-berita-tender').dataTable();


//        $('#table-berita-tender tbody tr td.detail-modal').on('click', function () {
//            alert($(this).data('id'));
//        });
    })
</script>
<?php $this->stop () ?>

