<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list
];
$this->layout ('base', $parent_data);
$this->start ('style');
?>
<link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
<!--tempat css/style-->
<?php
$this->stop ();
$this->start ('page-title');
?>
<?= $approval ? 'Approval' : '' ?> Unit Kerja
<?php
$this->stop();
$this->start ('contents');
?>
<!--tempat konten-->
<div class="main-content container-fluid">
    <div class="panel panel-default panel-table">
        <div class="panel-heading">
            Daftar Berita Tender
            <div class="tools">
                <a href="<?= $this->pathFor ('beritaTender_tambah') ?>" class="btn btn-space btn-primary">
                    <i class="icon icon-left mdi mdi-plus-circle-o" style="color:#fff"></i>
                    Tambah
                </a>
            </div>
        </div>
        <div class="panel-body">
            <table id="table-berita-tender" class="table table-hover table-fw-widget" style="border-top: 0px !important;">
                <thead>
                    <tr>
                        <th></th>
                        <th>Judul</th>
                        <th>Penyelenggara</th>
                        <th>Jml</th>
                        <th width="15%">Terbaru</th>
                        <th class="actions"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i=1; ?>
                    <?php foreach(array_reverse($beritaTender) as $tender){ ?>
                        <?php $approve = json_decode($tender['approval'], true) ?>
                        <tr class="<?= ($this->dateAboveNow($tender['tgl_selesai']) ? null : 'text-muted') ?>">
                            <td><?= $i ?></td>
                            <td class="cell-detail">
                                <span><?= $tender['judul_tender'] ?></span>
                                <span class="cell-detail-description">
                                    <?= $this->indDate($tender['tgl_mulai']) ?>
                                    &nbsp;s/d&nbsp;
                                    <?= $this->indDate($tender['tgl_selesai']) ?>
                                </span>
                            </td>
                            <td class="cell-detail">
                                <span><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></span>
                                <span class="cell-detail-description">
                                    <?= $tender['wilayah'] ?>
                                </span>
                            </td>
                            <td><?= sizeof($this->detailUnitKerja($tender['id_tender'])) ?></td>
                            <?php if(sizeof($this->detailUnitKerja($tender['id_tender'])) > 0): ?>
                                <?php $unit = $this->detailUnitKerja($tender['id_tender']) ?>
                                <?php $unit = end($unit) ?>
                                <td class="user-avatar cell-detail user-info">
                                    <img src="public/profile/<?= $this->getUserUpload($unit['id_user'])['image'] ?>" alt="Avatar">
                                    <span><?= $this->getUserUpload($unit['id_user'])['nama'] ?></span>
                                    <span class="cell-detail-description"><?= $this->indDateTime($unit['waktu']) ?></span>
                                </td>
                            <?php else: ?>
                                <td>
                                    <span>Belum Ada</span>
                                </td>
                            <?php endif; ?>
                            <td class="actions">
                                <?php if( $approval ): ?>
                                    <a href="<?= $this->pathFor('beritaTender_detailApproval' , ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-space btn-primary"><i class="icon icon-left mdi mdi-check-circle" style="color:#fff;"></i> Approve</a>
                                <?php else: ?>
                                    <a href="<?= $this->pathFor('unitKerja_detail' , ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-space btn-primary"><i class="icon icon-left mdi mdi-eye" style="color:#fff;"></i> Detail</a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!--akhir tempat konten-->
<?php
$this->stop ();
$this->start ('js');
?>
<!--tempat js-->

<script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
<script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        //We use this to apply style to certain elements
        $.extend( true, $.fn.dataTable.defaults, {
            dom:
            "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
            "<'row be-datatable-body'<'col-sm-12'tr>>" +
            "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
            language: {

                emptyTable: "Tidak ada data tersedia",
                lengthMenu: "Tampilkan _MENU_ data per halaman",
                "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                "info": "Hal _PAGE_ dari _PAGES_ halaman",
                "infoEmpty": "Tidak ada data tersedia",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": '<i class="mdi mdi-caret-left-circle"></i>',
                    "last": '<i class="mdi mdi-caret-right-circle"></i>',
                    "next": '<i class="mdi mdi-caret-right-circle"></i>',
                    "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                },
                "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                "searchPlaceholder": 'Cari',
            },
        });

        var beritaTable = $('#table-berita-tender').dataTable();

//        $('#table-berita-tender tbody tr td.detail-modal').on('click', function () {
//            alert($(this).data('id'));
//        });
    })
</script>
<?php $this->stop () ?>

