<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list
];
$this->layout('base', $parent_data);
$this->start('style');
?>
<link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
<!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
Daftar Unit Kerja Berita Tender
<?php
$this->stop();
$this->start('contents');
?>
<!--tempat konten-->
<div class="main-content container-fluid">
    <div role="alert" class="alert alert-primary alert-simple alert-dismissible">
        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true" class="mdi mdi-close"></span>
        </button>
        <span class="icon mdi mdi-info-outline"></span>
        <strong>info!</strong> Daftar tender yang dapat ditentukan unit kerja-nya adalah tender dengan dokumen RKS yang telah disetujui oleh direktur dan manajer
    </div>
    <div class="panel panel-default panel-table">
        <div class="panel-body">
            <table id="table-berita-tender" class="table table-hover table-fw-widget" style="border-top: 0px !important;">
                <thead>
                    <tr>
                        <th></th>
                        <th width="50%">Judul</th>
                        <th width="10%">Mulai</th>
                        <th width="10%">Selesai</th>
                        <th width="10%">Penyelenggara</th>
                        <th width="20%" class="text-right">Unit Kerja</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 1; ?>
                    <?php foreach (array_reverse($beritaTender) as $tender): ?>
                        <?php $rks = json_decode($tender['rks'], true); ?>
                        <?php $approvalRKS = $rks['approval']; ?>
                        <?php if ($approvalRKS['direktur']['status'] == 'diterima' && $approvalRKS['manajer']['status'] == 'diterima'): ?>
                            <tr class="<?= ($this->dateAboveNow($tender['tgl_selesai']) ? null : 'text-muted') ?>">
                                <td><?= $i ?></td>
                                <td onclick="document.location = '<?= $this->pathFor('detailBeritaTender', ['id_tender' => $tender['id_tender']]) ?>'" style="cursor: pointer;">
                                    <?= $tender['judul_tender'] ?>
                                </td>
                                <td><?= $this->indDate($tender['tgl_mulai']) ?></td>
                                <td><?= $this->indDate($tender['tgl_selesai']) ?></td>
                                <td><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></td>
                                <td class="text-right">
                                    <div class="btn-group btn-space">
                                        <?php $dokAcara = json_decode($tender['berita_acara'], true); ?>
                                        <?php if ($this->countUnitKerja($tender['id_tender']) > 0): ?>
                                            <button type="button" class="btn btn-color btn-social btn-success btn-sm">
                                                <?= $this->countUnitKerja($tender['id_tender']) ?>
                                            </button>
                                            <a href="<?= $this->pathFor('detailTenderUnitKerja', ['id_tender' => $tender['id_tender']]) ?>" type="button" class="btn btn-success btn-sm">Ganti Unit Kerja</a>
                                        <?php else: ?>
                                            <button type="button" class="btn btn-color btn-social btn-default btn-sm">
                                                <i class="icon mdi mdi-circle-o"></i>
                                            </button>
                                            <a href="<?= $this->pathFor('detailTenderUnitKerja', ['id_tender' => $tender['id_tender']]) ?>" type="button" class="btn btn-default btn-sm">Pilih Unit Kerja</a>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <?php $i++; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
<!--tempat js-->

<script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
<script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        //We use this to apply style to certain elements
        $.extend(true, $.fn.dataTable.defaults, {
            dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
            "<'row be-datatable-body'<'col-sm-12'tr>>" +
            "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
            language: {

                emptyTable: "Tidak ada data tersedia",
                lengthMenu: "Tampilkan _MENU_ data per halaman",
                "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                "info": "Hal _PAGE_ dari _PAGES_ halaman",
                "infoEmpty": "Tidak ada data tersedia",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": '<i class="mdi mdi-caret-left-circle"></i>',
                    "last": '<i class="mdi mdi-caret-right-circle"></i>',
                    "next": '<i class="mdi mdi-caret-right-circle"></i>',
                    "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                },
                "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                "searchPlaceholder": 'Cari',
            },
        });

        var beritaTable = $('#table-berita-tender').dataTable();


//        $('#table-berita-tender tbody tr td.detail-modal').on('click', function () {
//            alert($(this).data('id'));
//        });
    })
</script>
<?php $this->stop() ?>

