<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Daftar Unit Kerja Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Berita Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><?= substr($tender['link_website'], 0, 35) ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Diupload Oleh</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
                <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div>
            </div>
        </div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Unit Kerja
                <div class="tools">
                    <button class="btn btn-rounded btn-space btn-primary btn-sm open-modal-tambah">
                        <i class="mdi mdi-account-add"></i>
                        &nbsp; Tambah Unit Kerja
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="unit-kerja" class="table table-striped table-hover table-fw-widget">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th>Nama Pegawai</th>
                            <th>Penugasan</th>
                            <th class="actions" width="10%"></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="modal-tambah" class="modal-container colored-header colored-header-primary modal-effect-9">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Form Penentuan Unit Kerja</h3>
            </div>
            <div class="modal-body form">
                <div class="form-group">
                    <label>Pengawai</label>
                    <select multiple="" id="select-pegawai">
                        <option></option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Penugasan</label>
                    <select id="input-penugasan">
                        <option value="Penawaran">Penawaran</option>
                        <option value="Lainnya">Lainnya</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary modal-close btn-simpan">Tambahkan</button>
                <button type="button" class="btn btn-default modal-close">Batal</button>
            </div>
        </div>
    </div>
    <div id="modal-hapus" class="modal-container modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="text-danger"><span class="modal-main-icon mdi mdi-delete"></span></div>
                    <h3>Hapus Unit Kerja!</h3>
                    <p>Apakah anda yakin akan menghapus unit kerja <q><strong class="nama-pegawai"></strong></q> yang ditugaskan untuk <q><strong class="penugasan"></strong></q></p>
                    <div class="xs-mt-50">
                        <button type="button" data-dismiss="modal" class="btn btn-danger btn-space modal-close btn-hapus">Hapus</button>
                        <button type="button" data-dismiss="modal" class="btn btn-default btn-space modal-close">Batal</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
    <div class="modal-overlay"></div>


    <!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
//            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });

            //We use this to apply style to certain elements
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada unit kerja</h4>' +
                    '<button class="btn btn-rounded btn-space btn-primary btn-sm open-modal-tambah"><i class="mdi mdi-account-add"></i>&nbsp; Tambah Unit Kerja </button>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });

            var unitKerja = $('#unit-kerja').DataTable({
                ajax:"<?= $this->pathFor('unitKerja_list', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: "id_unitkerja",
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: null,
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            return  '<img src="public/profile/' + data.pegawai.image + '" alt="Avatar">'+
                                    '<span>' + data.pegawai.nama + '</span>'+
                                    '<span class="cell-detail-description">' + moment(data.waktu).format('D MMMM YYYY h:mm') + '</span>'
                        }
                    },
                    {data:'penugasan'},
                    {
                        data:null,
                        className:'text-right',
                        render: function (data, type, row, meta) {
                            delete data.rowData;
                            return  '<button class="btn btn-space btn-danger open-modal-hapus" data-rowdata=\''+JSON.stringify(data)+'\'><i class="mdi mdi-delete"></i></button>'
                        }
                    }
                ],
                order: [[ 2, 'asc' ]],
            });
            $('.open-modal-tambah').on('click', function(){
                function formatState (state) {
                    if (!state.id) { return state.text; }
                    console.log(state);
                    var $state = $(
                        '<span><img class="img-circle" style="height:30px;" src="public/profile/' + state.element.dataset.image + '" class="img-flag" /> ' + state.text + '</span>'
                    );
                    return $state;
                }
                $('#modal-tambah').niftyModal({
                    buttons: [
                        {
                            class: 'btn-simpan',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                var data = {
                                    pegawai: modal.find('#select-pegawai').val(),
                                    penugasan: modal.find('#input-penugasan').val()
                                }
                                $.post('<?= $this->pathFor('unitKerja_tambah', ['id_tender'=>$tender['id_tender']]) ?>', data, function(result){
                                    if(result.status == 'success') {
                                        unitKerja.ajax.reload();
                                    }
                                }, 'json');
                                return true;
                            }
                        },
                    ],
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('#select-pegawai').html('');
                        $.getJSON('<?= $this->pathFor('unitKerja_tersedia', ['id_tender'=>$tender['id_tender']]) ?>', function (res) {
                            $.each(res, function (key, val) {
                                modal.find('#select-pegawai').append(
                                    '<option data-image="' + val.image + '" ' + (val.available ? '' : 'disabled') + ' value="' + val.id_user + '">' +
                                    (val.available ? val.nama : val.nama + '(Sudah Terdaftar)') +
                                    '</option>'
                                );
                            });
                            modal.find("#select-pegawai").select2({
                                placeholder: 'Pilih Pegawai',
                                templateResult: formatState,
                                templateSelection: formatState,
                                width: '100%',
                            });
                            modal.find("#input-penugasan").select2({
                                placeholder: 'Penugasan',
                                width: '100%',
                            });
                        });
                    }
                });
            });
            $('#unit-kerja tbody').on('click', '.open-modal-hapus', function () {
                var data = $(this).data('rowdata');
                $('#modal-hapus').niftyModal({
                    buttons: [
                        {
                            class: 'btn-hapus',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                var pData = {
                                    id_unitkerja: data.id_unitkerja,
                                    id_tender: '<?= $tender['id_tender'] ?>',
                                };
                                $.post('<?= $this->pathFor('unitKerja_hapus') ?>', pData, function (res) {
                                    if(res.status == 'success'){
                                        unitKerja.ajax.reload();
                                    }
                                }, 'json');
                                return true;
                            }
                        },
                    ],
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('.nama-pegawai').html(data.pegawai.nama);
                        modal.find('.penugasan').html(data.penugasan);
                    }
                });
            });
        })

    </script>
<?php $this->stop() ?>