<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Daftar Unit Kerja Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Berita Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><?= substr($tender['link_website'], 0, 35) ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Diupload Oleh</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
                <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div>
            </div>
        </div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Unit Kerja
                <div class="tools">
                    <button class="btn btn-rounded btn-space btn-primary btn-sm" data-toggle="modal" data-target="#form-unitkerja">
                        <i class="mdi mdi-account-add"></i>
                        &nbsp; Tambah Unit Kerja
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="unit-kerja" class="table table-striped table-hover table-fw-widget">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th>Nama Pegawai</th>
                            <th>Penugasan</th>
                            <th class="actions" width="10%"></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal-overlay"></div>
    <div id="form-unitkerja" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-primary">
        <div class="modal-dialog custom-width">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span class="mdi mdi-close"></span></button>
                    <h3 class="modal-title">Form Penentuan Unit Kerja</h3>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Pengawai</label>
                        <select multiple="" id="modal-pegawai">
                            <option></option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Penugasan</label>
                        <input type="text" placeholder="Penugasan" id="modal-penugasan" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary form-unitkerja-simpan">Tambahkan</button>
                    <button type="button" data-dismiss="modal" class="btn btn-default md-close">Batal</button>
                </div>
            </div>
        </div>
    </div>
    <div id="hapus-unitkerja" tabindex="-1" role="dialog" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <div class="text-danger"><span class="modal-main-icon mdi mdi-delete"></span></div>
                        <h3>Danger!</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>Fusce ultrices euismod lobortis.</p>
                        <div class="xs-mt-50">
                            <button type="button" data-dismiss="modal" class="btn btn-space btn-default">Cancel</button>
                            <button type="button" data-dismiss="modal" class="btn btn-space btn-danger btn-hapus">Hapus</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>

    <!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
//            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });

            //We use this to apply style to certain elements
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada unit kerja</h4>' +
                    '<button class="btn btn-rounded btn-space btn-primary btn-sm" data-toggle="modal" data-target="#form-unitkerja"><i class="mdi mdi-account-add"></i>&nbsp; Tambah Unit Kerja </button>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });

            var unitKerja = $('#unit-kerja').DataTable({
                ajax:"<?= $this->pathFor('unitKerja_list', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: "id_unitkerja",
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: null,
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            return  '<img src="public/profile/' + data.pegawai.image + '" alt="Avatar">'+
                                    '<span>' + data.pegawai.nama + '</span>'+
                                    '<span class="cell-detail-description">' + moment(data.waktu).format('D MMMM YYYY h:mm') + '</span>'
                        }
                    },
                    {data:'penugasan'},
                    {
                        data:null,
                        className:'text-right',
                        render: function (data, type, row, meta) {
                            delete data.rowData;
                            return  '<button class="btn btn-space btn-danger btn-hapus" data-toggle="modal" data-target="#hapus-unitkerja" data-rowdata=\''+JSON.stringify(data)+'\'><i class="mdi mdi-delete"></i></button>'
                        }
                    }
                ],
                order: [[ 2, 'asc' ]],
                "drawCallback": function ( settings ) {
                    var api = this.api();
                    var rows = api.rows( {page:'current'} ).nodes();
                    var last=null;
                    api.column(2, {page:'current'} ).data().each( function ( group, i ) {
                        if ( last !== group ) {
                            $(rows).eq( i ).before(
                                '<tr class="active"><td colspan="4" style="padding-top:5px;padding-bottom: 5px;" class="text-center"><span class="label label-primary"> '+group+' </span></td></tr>'
                            );

                            last = group;
                        }
                    } );
                }
            });



            $('#hapus-unitkerja').on('show.bs.modal', function (event) {
                var mBtn = $(event.relatedTarget) // Button that triggered the modal
                var mData = mBtn.data() // Extract info from data-* attributes
                var modal = $(this)
                modal.find('h3').html("Hapus Unit Kerja?");
                modal.find('p').html('Apakah anda yakin akan menghapus unit kerja <strong><mark>'+mData.rowdata.pegawai.nama+'</mark></strong> yang ditugaskan untuk <b><mark>'+mData.rowdata.penugasan+'</mark></b>');
                modal.find('.btn-hapus').on('click', function(){
                    $.post('<?= $this->pathFor('unitKerja_hapus') ?>', {
                        id_unitkerja: mData.rowdata.id_unitkerja,
                        id_tender: '<?= $tender['id_tender'] ?>',
                    }, function (res) {
                        if(res.status == 'success'){
                            unitKerja.ajax.reload();
                            modal.modal('hide');
                        }
                    }, 'json');
                    return false;
                })
            });

            $('#form-unitkerja').on('show.bs.modal', function (event) {
                var mBtn = $(event.relatedTarget) // Button that triggered the modal
                var mData = mBtn.data() // Extract info from data-* attributes
                var modal = $(this)

                function formatState (state) {
                    if (!state.id) { return state.text; }
                    console.log(state);
                    var $state = $(
                        '<span><img class="img-circle" style="height:30px;" src="public/profile/' + state.element.dataset.image + '" class="img-flag" /> ' + state.text + '</span>'
                    );
                    return $state;
                }

                $.getJSON('<?= $this->pathFor('unitKerja_tersedia', ['id_tender'=>$tender['id_tender']]) ?>', function (jData) {
                    modal.find("#modal-pegawai").html('<option></option>')
                    $.each(jData, function (i, val) {
                        var opt = $('<option></option>');
                        opt.attr('data-image', val.image)
                        opt.val(val.id_user)
                        if(val.available == false){
                            opt.attr('disabled', 'disabled')
                            opt.text(val.nama+' (sudah terdaftar)')
                        }else{
                            opt.text(val.nama)
                        }
                        modal.find("#modal-pegawai").append(opt)
                    })
                    modal.find("#modal-pegawai").select2({
                        placeholder: 'Pilih Pegawai',
                        templateResult: formatState,
                        templateSelection: formatState,
                        width: '100%',
                    });
                    modal.find('.form-unitkerja-simpan').on('click', function () {
                        var pegawai = modal.find('#modal-pegawai').val()
                        var penugasan = modal.find('#modal-penugasan').val()
                        $.ajax({
                            type: "POST",
                            url: '<?= $this->pathFor('unitKerja_tambah', ['id_tender'=>$tender['id_tender']]) ?>',
                            data: {
                                pegawai:pegawai,
                                penugasan:penugasan
                            },
                            success: function (result) {
                                if(result.status == 'success'){
                                    unitKerja.ajax.reload();
                                    modal.find('#modal-pegawai').val('');
                                    modal.find('#modal-penugasan').val('');
                                    $('#form-unitkerja').modal('hide')
                                }
                            },
                            dataType: "JSON"
                        });


                    })
                })
            })

        })

    </script>
<?php $this->stop() ?>