<?php
    $this->layout ('base', ['active_user_data' => $active_user_data]);
    $this->start ('style');
?>
<link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
<!--tempat css/style-->
<?php
    $this->stop ();
    $this->start ('contents');
?>
<!--tempat konten-->
<div class="main-content container-fluid">
    <div class="panel panel-default panel-table">
        <div class="panel-heading">Default
            <div class="tools"><span class="icon mdi mdi-download"></span><span class="icon mdi mdi-more-vert"></span></div>
        </div>
        <div class="panel-body">
            <table id="table-berita-tender" class="table table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th></th>
                        <th>Judul</th>
                        <th>Tanggal Mulai</th>
                        <th>Tanggal Selesai</th>
                        <th>Penyelenggara</th>
                        <th>Wilayah</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i=1; ?>
                    <?php foreach($beritaTender as $tender): ?>
                        <tr>
                            <td><?= $i ?></td>
                            <td><?= $tender['judul_tender'] ?></td>
                            <td><?= $this->indDate($tender['tgl_mulai']) ?></td>
                            <td><?= $this->indDate($tender['tgl_selesai']) ?></td>
                            <td><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></td>
                            <td><?= $tender['wilayah'] ?></td>
                            <td class="center"></td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!--akhir tempat konten-->
<?php
    $this->stop ();
    $this->start ('js');
?>
<!--tempat js-->

<script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
<script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
<script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        //We use this to apply style to certain elements
        $.extend( true, $.fn.dataTable.defaults, {
            dom:
            "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
            "<'row be-datatable-body'<'col-sm-12'tr>>" +
            "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
            language: {

                emptyTable: "Tidak ada data tersedia",
                lengthMenu: "Tampilkan _MENU_ data per halaman",
                "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                "info": "Hal _PAGE_ dari _PAGES_ halaman",
                "infoEmpty": "Tidak ada data tersedia",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "paginate": {
                    "first": '<i class="mdi mdi-caret-left-circle"></i>',
                    "last": '<i class="mdi mdi-caret-right-circle"></i>',
                    "next": '<i class="mdi mdi-caret-right-circle"></i>',
                    "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                },
                "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                "searchPlaceholder": 'Cari',
            },
        });

        $('#table-berita-tender').dataTable();
    })
</script>
<?php $this->stop () ?>

