<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?= $this->basePath () ?>/">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="public/assets/img/logo-fav.png">
        <title>E-Admin Tender</title>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <?= $this->section ('style') ?>
        <link rel="stylesheet" href="public/assets/css/style.css" type="text/css"/>
        <link rel="stylesheet" href="public/assets/lib/jquery.gritter/css/jquery.gritter.css" type="text/css"/>
        <style>
            .no-lr-gutter{
                padding-left:0px !important;
                padding-right:0px !important;
            }
            .no-r-gutter{
                padding-right:0px !important;
            }
            .no-l-gutter{
                padding-left:0px !important;
            }
            .aside-well{
                margin-bottom: 0px !important;
                border-radius: 0px !important;
            }
            .table tbody tr.child td:first-child{
                border-bottom: 3px solid #5f99f5;
            }
        </style>
    </head>
    <body>
        <div class="be-wrapper be-fixed-sidebar <?= (isset($aside) ? 'be-aside' : '') ?>">
            <nav class="navbar navbar-default navbar-fixed-top be-top-header">
                <div class="container-fluid">
                    <div class="navbar-header"><a href="index.html" class="navbar-brand"></a></div>
                    <div class="be-right-navbar">
                        <ul class="nav navbar-nav navbar-right be-user-nav">
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                                    <img src="public/profile/<?= $active_user_data['image'] ?>" alt="Avatar">
                                    <span class="user-name"><?= $this->e($active_user_data['nama']); ?></span>
                                </a>
                                <ul role="menu" class="dropdown-menu">
                                    <li>
                                        <div class="user-info">
                                            <div class="user-name"><?= $this->e($active_user_data['nama']); ?></div>
                                        </div>
                                    </li>
                                    <li><a href="<?= $this->pathFor('users_profile') ?>"><span class="icon mdi mdi-face"></span> Pengaturan Akun</a></li>
                                    <li><a href="<?=$this->pathFor('doLogout')?>"><span class="icon mdi mdi-power"></span> Keluar</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="page-title"><span><?= $this->section('page-title') ?></span></div>
                        <ul class="nav navbar-nav navbar-right be-icons-nav">
                            <li class="dropdown <?= !$active_user_data['token'] ? 'hidden' : '' ?>">
                                <a href="<?= $this->pathFor('users_profile') ?>" class="dropdown-toggle">
                                    <label class="label label-default"><i class="mdi mdi-alert-triangle text-warning"></i> Verifikasi E-mail</label>
                                </a>
                            </li>
                            <li class="dropdown <?= !$active_user_data['smscode'] ? 'hidden' : '' ?>">
                                <a href="<?= $this->pathFor('users_profile') ?>" class="dropdown-toggle">
                                    <label class="label label-default"><i class="mdi mdi-alert-triangle text-warning"></i> Verifikasi Nomor Telepon</label>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" role="button" aria-expanded="false" class="be-toggle-right-sidebar"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <?= $this->insert ('navbar', ['active_user_data' => $active_user_data]); ?>
            <div class="be-content">
                <?= $this->section('contents') ?>
            </div>
            <?= $this->insert ('sidebar', ['notifikasi' => $active_notification_list['notifikasi'], 'histories' => $active_notification_list['histories']]); ?>
        </div>
        <script src="public/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/js/main.js" type="text/javascript"></script>
        <script src="public/assets/js/jquery.form.min.js" type="text/javascript"></script>
        <script src="public/assets/js/validator.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/prettify/prettify.js" type="text/javascript"></script>
        <script src="public/assets/lib/moment.js/moment.js" type="text/javascript"></script>
        <script src="public/assets/lib/moment.js/locale/id.js" type="text/javascript"></script>
        <script src="public/assets/lib/mustache/mustache.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/twig/twig.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery.gritter/js/jquery.gritter.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
        <script src="public/assets/lib/jQuery-currency-master/money.jquery.js" type="text/javascript"></script>
        <script src="public/assets/js/list.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            var active_user = {
                user_id:'<?= $active_user_data['id_user'] ?>',
                previledge:'<?= $active_user_data['previledge'] ?>',
                token:'<?= $active_user_data['token'] ?>',
                smscode:'<?= $active_user_data['smscode'] ?>',
            };
            $(document).ready(function () {
                //initialize the javascript
                App.init();
                //Runs prettify
                prettyPrint();
                moment.locale('id');
                $('[data-toggle="tooltip"]').tooltip();
                var history_list = new List('history-list', {
                    valueNames:[
                        'timeline-activity',
                        {  data: ['category'] },
                        {  data: ['type'] },
                    ]
                });
                $('#history-list .history-search').keyup(function () {
                    var val = $(this).val();
                    if(val.length >= 0) {
                        history_list.search(val, 'timeline-activity');
                        $('#history-list .clear').removeClass('hidden');
                    }else{
                        $('#history-list .clear').addClass('hidden');
                        history_list.search();
                    }
                })
                $('#history-list .clear').click(function () {
                    $(this).addClass('hidden');
                    $('#history-list .history-search').val('');
                    history_list.search();
                })
            });
        </script>
        <?= $this->section ('js') ?>
    </body>
</html>