<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?= $this->basePath () ?>/">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="public/assets/img/logo-fav.png">
        <title>E-Admin Tender</title>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <?= $this->section ('style') ?>
        <link rel="stylesheet" href="public/assets/css/style.css" type="text/css"/>
        <link rel="stylesheet" href="public/assets/lib/jquery.gritter/css/jquery.gritter.css" type="text/css"/>
        <style>
            .no-lr-gutter{
                padding-left:0px !important;
                padding-right:0px !important;
            }
            .no-r-gutter{
                padding-right:0px !important;
            }
            .no-l-gutter{
                padding-left:0px !important;
            }
            .aside-well{
                margin-bottom: 0px !important;
                border-radius: 0px !important;
            }
            .table tbody tr.child td:first-child{
                border-bottom: 3px solid #5f99f5;
            }
        </style>
    </head>
    <body>
        <div class="be-wrapper be-fixed-sidebar <?= (isset($aside) ? 'be-aside' : '') ?>">
            <nav class="navbar navbar-default navbar-fixed-top be-top-header">
                <div class="container-fluid">
                    <div class="navbar-header"><a href="index.html" class="navbar-brand"></a></div>
                    <div class="be-right-navbar">
                        <ul class="nav navbar-nav navbar-right be-user-nav">
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                                    <img src="public/profile/<?= $active_user_data['image'] ?>" alt="Avatar">
                                    <span class="user-name"><?= $this->e($active_user_data['nama']); ?></span>
                                </a>
                                <ul role="menu" class="dropdown-menu">
                                    <li>
                                        <div class="user-info">
                                            <div class="user-name"><?= $this->e($active_user_data['nama']); ?></div>
                                        </div>
                                    </li>
                                    <li><a href="<?= $this->pathFor('users_profile') ?>"><span class="icon mdi mdi-face"></span> Pengaturan Akun</a></li>
                                    <li><a href="<?=$this->pathFor('doLogout')?>"><span class="icon mdi mdi-power"></span> Keluar</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="page-title"><span><?= $this->section('page-title') ?></span></div>
                        <ul class="nav navbar-nav navbar-right be-icons-nav">
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                                <ul class="dropdown-menu be-notifications">
                                    <li>
                                        <div class="title">Notifikasi<span class="badge"><?= count($active_notification_list) ?></span></div>
                                        <div class="list">
                                            <div class="be-scroller">
                                                <div class="content">
                                                    <ul>
                                                        <?php
                                                            for($i=0; $i<count($active_notification_list); $i++){
                                                                $user_detail = $this->getUserDetail($active_notification_list[$i]['by_user']);
                                                        ?>
                                                        <li class="notification <?= ($active_notification_list[$i]['status'] == null ? 'notification-unread' : '') ?>">
                                                            <a href="<?= $active_notification_list[$i]['meta'] ?>">
                                                                <div class="image">
                                                                    <img src="public/assets/img/<?= $user_detail['image'] ?>" alt="Avatar">
                                                                </div>
                                                                <div class="notification-info">
                                                                    <div class="text">
                                                                        <span class="user-name"><?= $user_detail['nama'] ?></span><br>
                                                                        <?= $active_notification_list[$i]['tentang'] ?>
                                                                    </div>
                                                                    <span class="date"><?= $this->timeElapsed($active_notification_list[$i]['waktu']) ?></span>
                                                                </div>
                                                            </a>
                                                        </li>
                                                        <?php } ?>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="footer"><a href="#">Lihat Semua Notifikasi</a></div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <?= $this->insert ('navbar', ['active_user_data' => $active_user_data]); ?>
            <div class="be-content">
                <?= $this->section('contents') ?>
            </div>
        </div>
        <script src="public/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/js/main.js" type="text/javascript"></script>
        <script src="public/assets/js/jquery.form.min.js" type="text/javascript"></script>
        <script src="public/assets/js/validator.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/prettify/prettify.js" type="text/javascript"></script>
        <script src="public/assets/lib/moment.js/moment.js" type="text/javascript"></script>
        <script src="public/assets/lib/moment.js/locale/id.js" type="text/javascript"></script>
        <script src="public/assets/lib/mustache/mustache.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/twig/twig.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery.gritter/js/jquery.gritter.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
        <script type="text/javascript">
            var active_user = {
                user_id:'<?= $active_user_data['id_user'] ?>',
                previledge:'<?= $active_user_data['previledge'] ?>',
            };
            $(document).ready(function () {
                //initialize the javascript
                App.init();
                //Runs prettify
                prettyPrint();
                moment.locale('id');
                $('[data-toggle="tooltip"]').tooltip()
            });
        </script>
        <?= $this->section ('js') ?>
    </body>
</html>