<?php
    $parent_data = [
        'active_user_data' => $active_user_data,
        'active_notification_list' => $active_notification_list
    ];
    $this->layout ('base', $parent_data);
    $this->start ('style');
?>
<link rel="stylesheet" type="text/css" href="<?= $this->asset('lib/datatables/css/dataTables.bootstrap.min.css'); ?>"/>
<!--tempat css/style-->
<?php
    $this->stop ();
    $this->start ('contents');
?>
<!--tempat konten-->
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line">Dashboard</h4>

            </div>

        </div>
        <div class="row">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Daftar Berita Tender
                        </div>
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th width="80">Tanggal</th>
                                            <th>Nama</th>
                                            <th>Penyelenggara</th>
                                            <th>Wilayah</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td width="100">01-12-2016 s/d 05-12-2016</td>
                                            <td> PENGADAAN MAINTENANCE SERVER DI DATA CENTER PT INDONESIA POWER (ULANG)
                                                <br> <a href="detail.html"> [detail..] </a> </br><br>
                                                <p> On Progress : </p>
                                                <div class="progress">
                                                    <div class="progress-bar progress-bar-striped active" role="progressbar"
                                                         aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:50%">
                                                        50%
                                                    </div>
                                                </div>
                                                </br></td>
                                            <td> PT. INDONESIA POWER</td>
                                            <td class="center"> KANTOR PUSAT</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--akhir tempat konten-->
<?php
    $this->stop ();
    $this->start ('js');
?>
<!--tempat js-->
<?php $this->stop () ?>

