<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?= $this->basePath () ?>/">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="public/assets/img/logo-fav.png">
        <title>E-Admin Tender</title>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <?= $this->section ('style') ?>
        <link rel="stylesheet" href="public/assets/css/style.css" type="text/css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
    </head>
    <body>
        <div class="be-wrapper be-nosidebar-left">
            <nav class="navbar navbar-default navbar-fixed-top be-top-header">
                <div class="container-fluid">
                    <div class="navbar-header"><a href="" class="navbar-brand" style="margin-left:10px;"></a></div>
                    <div class="be-right-navbar">
                        <ul class="nav navbar-nav navbar-right be-icons-nav">
                            <li><a href="<?= $this->pathFor('loginPage') ?>">Masuk</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="be-content">
                <div class="main-content container-fluid">
                    <div class="panel panel-default panel-table">
                        <div class="panel-body">
                            <table id="table-berita-tender" class="table table-hover table-fw-widget" style="border-top: 0px !important;">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th width="30%">Judul</th>
                                        <th width="15%">Penyelenggara / Wilayah</th>
                                        <th width="10%">Tanggal Mulai</th>
                                        <th width="10%">Tanggal Selesai</th>
                                        <th width="35%" class="actions"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach(array_reverse($beritaTender) as $key => $tender): ?>
                                        <?php $approve = json_decode($tender['approval'], true) ?>
                                        <tr class="<?= ($this->dateAboveNow($tender['tgl_selesai']) ? null : 'text-muted') ?>">
                                            <td><?= $key+1 ?></td>
                                            <td class="cell-detail milestone">
                                                <span style="font-weight: 400; line-height: 1.42857143; color: #404040; font-size: 13px;">
                                                    <?= $tender['judul_tender'] ?>
                                                </span>
                                                <span class="completed"><?= ceil($this->getProgress($tender['id_tender'])['progress']) ?>%</span><span class="version"><?= $this->getProgress($tender['id_tender'])['process'] ?></span>
                                                <div class="progress">
                                                    <div style="width: <?= $this->getProgress($tender['id_tender'])['progress'] ?>%" class="progress-bar progress-bar-primary"></div>
                                                </div>
                                            </td>
                                            <td class="cell-detail">
                                                <span><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></span>
                                                <span class="cell-detail-description">
                                                    <?= $tender['wilayah'] ?>
                                                </span>
                                            </td>
                                            <td data-filter="<?= strtotime($tender['tgl_mulai']) ?>" data-search="<?= strtotime($tender['tgl_mulai']) ?>">
                                                <?= $this->indDateFull($tender['tgl_mulai']) ?>
                                            </td>
                                            <td data-filter="<?= strtotime($tender['tgl_selesai']) ?>" data-search="<?= strtotime($tender['tgl_selesai']) ?>">
                                                <?= $this->indDateFull($tender['tgl_selesai']) ?>
                                            </td>
                                            <td class="actions">
                                                <a href="<?= $this->pathFor('beritaTender_detail' , ['id_tender'=>$tender['id_tender']]) ?>" class="btn btn-space btn-primary"><i class="icon icon-left mdi mdi-eye" style="color:#fff;"></i> Detail</a>
                                            </td>
                                        </tr>
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div>
                        <input type="hidden" id="tgl-min">
                        <input type="hidden" id="tgl-max">
                    </div>
                </div>
            </div>
        </div>
        <script src="public/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/js/main.js" type="text/javascript"></script>
        <script src="public/assets/js/jquery.form.min.js" type="text/javascript"></script>
        <script src="public/assets/js/validator.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/prettify/prettify.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
        <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
        <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
        <script src="public/assets/lib/moment.js/min/moment-with-locales.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/datetimepicker/js/locales/bootstrap-datetimepicker.id.js" type="text/javascript" charset="UTF-8"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                //initialize the javascript
                App.init();
                moment.locale('id');
                //Runs prettify
                prettyPrint();
                //We use this to apply style to certain elements
                $.extend( true, $.fn.dataTable.defaults, {
                    dom:
                    "<'row be-datatable-header'<'col-md-3'l><'col-md-9 text-right'<'pull-right'f><'pull-right date-filter'>>>" +
                    "<'row be-datatable-body'<'col-sm-12'tr>>" +
                    "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7 text-right'p>>",
                    language: {

                        emptyTable: "Tidak ada data tersedia",
                        lengthMenu: "Tampilkan _MENU_ data per halaman",
                        "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                        "info": "Hal _PAGE_ dari _PAGES_ halaman",
                        "infoEmpty": "Tidak ada data tersedia",
                        "infoFiltered": "(filtered from _MAX_ total records)",
                        "paginate": {
                            "first": '<i class="mdi mdi-caret-left-circle"></i>',
                            "last": '<i class="mdi mdi-caret-right-circle"></i>',
                            "next": '<i class="mdi mdi-caret-right-circle"></i>',
                            "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                        },
                        "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                        "searchPlaceholder": 'Cari',
                    },
                });

                $.fn.dataTable.ext.search.push(
                    function( settings, data, dataIndex ) {
                        var tgl_mulai = data[3];
                        var tgl_selesai = data[4];
                        var tgl_min = ($('#tgl-min').val().length === 0 ? moment().subtract(10, "y").format("x") : moment($('#tgl-min').val()).format("x"));
                        var tgl_max = ($('#tgl-max').val().length === 0 ? moment().add(10, "y").format("x") : moment($('#tgl-max').val()).format("x"));
                        if(tgl_mulai > tgl_min && tgl_selesai < tgl_max){
                            return true;
                        }
                        return false;
                    }
                );

                var beritaTable = $('#table-berita-tender').dataTable({
                    "initComplete": function(settings, json) {
                        table = settings.oInstance.api();
                        $('.date-filter').css('padding', '0 10px 0 0');
                        $('.date-filter').html(
                            '<div class="input-group input-group-sm">' +
                            '   <input type="text" class="form-control tgl-mulai" data-min-view="2" data-date-format="dd MM yyyy" placeholder="Tanggal Mulai">' +
                            '   <span class="input-group-btn">' +
                            '       <button type="button" class="btn btn-default">s/d</button>' +
                            '   </span>' +
                            '   <input type="text" class="form-control tgl-selesai"  data-min-view="2" data-date-format="dd MM yyyy"  placeholder="Tanggal Mulai">' +
                            '   <span class="input-group-btn hidden">' +
                            '       <button type="button" class="btn btn-primary tgl-reset">Reset</button>' +
                            '   </span>' +
                            '</div>'
                        );
                        $(".date-filter").find('.tgl-mulai').datetimepicker({
                            autoclose: true,
                            componentIcon: '.mdi.mdi-calendar',
                            navIcons:{
                                rightIcon: 'mdi mdi-chevron-right',
                                leftIcon: 'mdi mdi-chevron-left'
                            },
                            language:'id',
                            linkField: "tgl-min",
                            linkFormat: "yyyy-mm-dd"
                        }).on('changeDate', function(ev){
                            table.draw();
                            $(".date-filter").find('.tgl-reset').parent().removeClass('hidden');
                        });
                        $(".date-filter").find('.tgl-selesai').datetimepicker({
                            autoclose: true,
                            componentIcon: '.mdi.mdi-calendar',
                            navIcons:{
                                rightIcon: 'mdi mdi-chevron-right',
                                leftIcon: 'mdi mdi-chevron-left'
                            },
                            language:'id',
                            linkField: "tgl-max",
                            linkFormat: "yyyy-mm-dd"
                        }).on('changeDate', function(ev){
                            table.draw();
                            $(".date-filter").find('.tgl-reset').parent().removeClass('hidden');
                        });
                        $(".date-filter").find('.tgl-reset').on('click', function () {
                            $(this).parent().addClass('hidden');
                            $('#tgl-min').val('');
                            $('#tgl-max').val('');
                            $(".date-filter").find('.tgl-selesai').val('')
                            $(".date-filter").find('.tgl-mulai').val('')
                            table.draw()
                        })
                    }
                });
            });
        </script>
    </body>
</html>