<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?= $this->basePath() ?>/">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="public/assets/img/logo-fav.png">
        <title>E-Admin Tender</title>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="public/assets/css/style.css" type="text/css"/>
    </head>
    <body class="be-splash-screen">
        <div class="be-wrapper be-login">
            <div class="be-content">
                <div class="main-content container-fluid">
                    <div class="splash-container">
                        <div class="panel panel-default panel-border-color panel-border-color-primary">
                            <div class="panel-heading"><img src="public/assets/img/logo1.png" alt="logo" width="200" class="logo-img"><span class="splash-description">Please enter your user information.</span></div>
                            <div class="panel-body">
                                <?php if($authError){ ?>
                                <div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible">
                                    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
                                    <div class="message">
                                        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                                            <span aria-hidden="true" class="mdi mdi-close"></span>
                                        </button>
                                        <strong>Login Gagal</strong><br>
                                        <p>Username atau Password tidak tercatat pada aplikasi</p>
                                    </div>
                                </div>
                                <?php } ?>
                                <form action="<?= $router->pathFor('doLogin') ?>" method="post">
                                    <div class="form-group">
                                        <input id="username" type="text" placeholder="Username atau Email" autocomplete="off" name="username" class="form-control" required>
                                    </div>
                                    <div class="form-group">
                                        <input id="password" type="password" placeholder="Password" name="password" class="form-control" required>
                                    </div>
                                    <div class="form-group login-submit">
                                        <button data-dismiss="modal" type="submit" class="btn btn-primary btn-xl">Masuk</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="splash-footer"><span><a href="#">Lupa password? </a></span></div>
                    </div>
                </div>
            </div>
        </div>
        <script src="public/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/js/main.js" type="text/javascript"></script>
        <script src="public/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                //initialize the javascript
                App.init();
            });
        </script>
    </body>
</html>