<nav class="be-right-sidebar">
    <div class="sb-content">
        <div class="tab-navigation">
            <ul role="tablist" class="nav nav-tabs nav-justified">
                <li role="presentation" class="active"><a href="#tab-notifikasi" aria-controls="tab-notifikasi" role="tab" data-toggle="tab">Notifikasi</a></li>
                <li role="presentation"><a href="#tab-history" aria-controls="tab-history" role="tab" data-toggle="tab">History</a></li>
                <li role="presentation"><a href="#tab-coba" aria-controls="tab-coba" role="tab" data-toggle="tab">History</a></li>
            </ul>
        </div>
        <div class="tab-panel">
            <div class="tab-content">
                <div id="tab-notifikasi" role="tabpanel" class="tab-pane tab-todo active">
                    <div class="todo-container be-notifications">
                        <div class="list">
                            <div class="be-scroller">
                                <div class="content">
                                    <ul>
                                        <?php for($i=0; $i<count($notifikasi); $i++): ?>
                                            <?php $user_detail = $this->getUserDetail($notifikasi[$i]['by_user']); ?>
                                            <li class="notification <?= ($notifikasi[$i]['status'] == null ? 'notification-unread' : '') ?>">
                                                <a href="<?= $notifikasi[$i]['meta'] ?>">
                                                    <div class="image">
                                                        <img src="public/profile/<?= $user_detail['image'] ?>" alt="Avatar">
                                                    </div>
                                                    <div class="notification-info">
                                                        <div class="text">
                                                            <span class="user-name"><?= $user_detail['nama'] ?></span><br>
                                                            <?= $notifikasi[$i]['tentang'] ?>
                                                        </div>
                                                        <span class="date"><?= $this->timeElapsed($notifikasi[$i]['waktu']) ?></span>
                                                    </div>
                                                </a>
                                            </li>
                                        <?php endfor; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="tab-history" role="tabpanel" class="tab-pane tab-todo">
                    <div class="todo-container">
                        <div class="todo-wrapper">
                            <div class="be-scroller">
                                <div class="todo-content be-notifications" style="padding: 0px !important;">
                                    <ul style="padding: 0px !important; line-height: 0px !important;">
                                        <?php foreach ($histories as $history): ?>
                                            <?php if($history['perubahan'] == 'i_tender'): ?>
                                                <li class="notification">
                                                    <a href="<?= $this->pathFor('beritaTender_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                                        <div class="image"><img src="public/profile/<?= $this->userDetailHelper($history['id_user'])['image'] ?>" alt="Avatar"></div>
                                                        <div class="notification-info">
                                                            <div class="text">
                                                                <span class="user-name"><?= $this->userDetailHelper($history['id_user'])['nama'] ?></span><br>
                                                                Membuat berita tender <?= $history['detail']['judul_tender'] ?>
                                                            </div>
                                                            <span class="date"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                                                        </div>
                                                    </a>
                                                </li>
                                            <?php elseif($history['perubahan'] == 'e_tender'): ?>
                                                <li class="notification">
                                                    <a href="<?= $this->pathFor('beritaTender_detail', ['id_tender'=>$history['id_tender']]) ?>">
                                                        <div class="image"><img src="public/profile/<?= $this->userDetailHelper($history['id_user'])['image'] ?>" alt="Avatar"></div>
                                                        <div class="notification-info">
                                                            <div class="text">
                                                                <span class="user-name"><?= $this->userDetailHelper($history['id_user'])['nama'] ?></span><br>
                                                                <?= 'a' ?>
                                                            </div>
                                                            <span class="date"><?= $this->timeElapsed($history['waktu']) ?> - <?= $this->indDateTime($history['waktu']) ?></span>
                                                        </div>
                                                    </a>
                                                </li>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
<!--                    <div class="todo-container be-notifications todo-container">-->
<!--                        <div class="todo-wrapper">-->
<!--                            <div class="be-scroller">-->
<!--                                <div class="content">-->
<!---->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->

                </div>
                <div id="tab-coba" role="tabpanel" class="tab-pane tab-todo">
                    <div class="todo-container" id="history-list">
                        <div class="bottom-input">
                            <input type="text" placeholder="Cari History" class="history-search" style="border-bottom: 1px solid #d5d8de">
                            <span class="mdi mdi-close clear hidden"></span>
                        </div>
                        <div class="bottom-input filter-list">

                        </div>
                        <div class="todo-wrapper">
                            <div class="be-scroller">
                                <div class="todo-content" style="padding: 0px !important;">
                                    <ul class="timeline timeline-variant timeline-sidebar list">
                                        <?php $my_divider = '' ?>
                                        <?php foreach ($histories as $history): ?>
                                            <?php if($this->indMonthYear($history['waktu']) <> $my_divider): ?>
                                                <?php $my_divider = $this->indMonthYear($history['waktu']) ?>
                                                <li class="timeline-month"><span><?= $my_divider ?></span></li>
                                            <?php endif; ?>
                                                <?php switch($history['perubahan']):
                                                case 'i_tender': ?>
                                                    <?= $this->insert('history/i_tender', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'e_tender': ?>
                                                    <?= $this->insert('history/e_tender', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'a_tender': ?>
                                                    <?= $this->insert('history/a_tender', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'd_tender': ?>
                                                    <?= $this->insert('history/d_tender', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'i_rks': ?>
                                                    <?= $this->insert('history/i_rks', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'e_rks': ?>
                                                    <?= $this->insert('history/e_rks', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'a_rks': ?>
                                                    <?= $this->insert('history/a_rks', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'i_acara': ?>
                                                    <?= $this->insert('history/i_acara', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'e_acara': ?>
                                                    <?= $this->insert('history/e_acara', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'i_unit': ?>
                                                    <?= $this->insert('history/i_unit', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'd_unit': ?>
                                                    <?= $this->insert('history/d_unit', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'i_dok': ?>
                                                    <?= $this->insert('history/i_dok', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'u_dok': ?>
                                                    <?= $this->insert('history/u_dok', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'e_dok': ?>
                                                    <?= $this->insert('history/e_dok', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'd_dok': ?>
                                                    <?= $this->insert('history/d_dok', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'a_dok': ?>
                                                    <?= $this->insert('history/a_dok', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'i_boq': ?>
                                                    <?= $this->insert('history/i_boq', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'e_boq': ?>
                                                    <?= $this->insert('history/e_boq', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'd_boq': ?>
                                                    <?= $this->insert('history/d_boq', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php case 'a_boq': ?>
                                                    <?= $this->insert('history/a_boq', ['history'=>$history]) ?>
                                                    <?php break ?>
                                                <?php endswitch; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>