<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?= $this->basePath() ?>/">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="public/assets/img/logo-fav.png">
        <title>E-Admin Tender</title>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/><!--[if lt IE 9]>
        <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
        <!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
        <![endif]-->
        <link rel="stylesheet" href="public/assets/css/style.css" type="text/css"/>
    </head>
    <body class="be-splash-screen">
        <div class="be-wrapper be-login be-signup">
            <div class="be-content">
                <div class="main-content container-fluid">
                    <div class="splash-container sign-up">
                        <div class="panel panel-default panel-border-color panel-border-color-primary">
                            <div class="panel-heading">
                                <img src="public/assets/img/logo1.png" alt="logo" width="200" class="logo-img">
<!--                                <span class="splash-description">Please enter your user information.</span>-->
                            </div>
                            <div class="panel-body">
                                <form action="<?= $this->pathFor('doSignUp', ['token'=>$token]) ?>" method="post" data-toggle="validator" role="form">
                                    <span class="splash-title xs-pb-20">Pendaftaran</span>
                                    <div class="form-group">
                                        <input  class="form-control" type="email" name="email" value="<?= $sign_data['email'] ?>" required readonly>
                                        <input  type="hidden" name="id_user" value="<?= $sign_data['id_user'] ?>">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" type="text" name="username" placeholder="Username" autocomplete="off" data-minlength="5" pattern="^[_A-z0-9]{1,}$" required data-remote="<?= $this->pathFor('checkAuth') ?>" data-required-error="Wajib di-isi" data-remote-error="Username telah digunakan" data-minlength-error="Minimal 5 Karakter" data-pattern-error="Hanya Huruf dan Angka">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" type="tel" name="telefon" placeholder="Nomor Ponsel" autocomplete="off" data-minlength="5" pattern="^[0-9]{1,}$" required data-required-error="Wajib di-isi" data-remote-error="Username telah digunakan" data-minlength-error="Minimal 5 Karakter" data-pattern-error="Hanya Huruf dan Angka">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="form-group row signup-password">
                                        <div class="col-xs-6">
                                            <input class="form-control" type="password" name="password" placeholder="Password"  required data-minlength="5" data-required-error="Wajib di-isi" data-minlength-error="Minimal 5 Karakter">
                                            <div class="help-block with-errors"></div>
                                        </div>
                                        <div class="col-xs-6">
                                            <input class="form-control" type="password" name="repassword" placeholder="Ulangi Password" required data-match='input[name="password"]' data-match-error="Password tidak sama" data-required-error="Wajib di-isi">
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="form-group xs-pt-10">
                                        <button type="submit" class="btn btn-block btn-primary btn-xl">Daftar</button>
                                    </div>
<!--                                    <div class="form-group xs-pt-10">-->
<!--                                        <div class="be-checkbox">-->
<!--                                            <input type="checkbox" id="remember">-->
<!--                                            <label for="remember">By creating an account, you agree the <a href="#">terms and conditions</a>.</label>-->
<!--                                        </div>-->
<!--                                    </div>-->
                                </form>
                            </div>
                        </div>
                        <div class="splash-footer">&copy; <?= $this->copyDate() ?> PT. Kencana Alam Putra</div>
                    </div>
                </div>
            </div>
        </div>
        <script src="public/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/js/main.js" type="text/javascript"></script>
        <script src="public/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="public/assets/js/validator.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                //initialize the javascript
                App.init();
            });
        </script>
    </body>
</html>