<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="<?= $this->basePath () ?>/">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="public/assets/img/logo-fav.png">
        <title>E-Admin Tender | Verifikasi SMS</title>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/material-design-icons/css/material-design-iconic-font.min.css"/><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="public/assets/css/style.css" type="text/css"/>
        <link rel="stylesheet" type="text/css" href="public/assets/lib/jquery.gritter/css/jquery.gritter.css"/>
        <style>
            .input-mask {
                text-align: center !important;
            }
        </style>
    </head>
    <body class="be-splash-screen">
        <div class="be-wrapper be-login">
            <div class="be-content">
                <div class="main-content container-fluid">
                    <div class="splash-container">
                        <div class="panel panel-default panel-border-color panel-border-color-primary">
                            <div class="panel-heading">
                                <img src="public/assets/img/logo1.png" alt="logo" width="200" class="logo-img">
                                <span class="splash-description">
                                    SMS Kode verifikasi telah dikirimkan ke nomor ponsel anda.
                                    <br>
                                    Masukkan kode verifikasi pada form dibawah ini
                                </span>
                            </div>
                            <div class="panel-body">
                                <form action="<?= $this->pathFor('doVerificateSMS', ['token'=>$token]) ?>" method="post">
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-2 md-pr-5 md-pl-5"><input type="text" class="form-control input-mask" maxlength="1" tabindex="1"></div>
                                            <div class="col-md-2 md-pr-5 md-pl-5"><input type="text" class="form-control input-mask" maxlength="1" tabindex="2"></div>
                                            <div class="col-md-2 md-pr-5 md-pl-5"><input type="text" class="form-control input-mask" maxlength="1" tabindex="3"></div>
                                            <div class="col-md-2 md-pr-5 md-pl-5"><input type="text" class="form-control input-mask" maxlength="1" tabindex="4"></div>
                                            <div class="col-md-2 md-pr-5 md-pl-5"><input type="text" class="form-control input-mask" maxlength="1" tabindex="5"></div>
                                            <div class="col-md-2 md-pr-5 md-pl-5"><input type="text" class="form-control input-mask" maxlength="1" tabindex="6"></div>
                                        </div>
                                        <input type="hidden" name="smscode">
                                    </div>
                                    <div class="form-group login-submit xs-p-0">
                                        <button type="submit" class="btn btn-primary btn-xl">Verifikasi</button>
                                    </div>
                                    <div class="form-group row login-tools">
                                        <div class="col-xs-6">
                                            <button type="button" class="btn btn-success btn-resend" disabled>Kirim Kode Ulang</button>
                                        </div>
                                        <div class="col-xs-6 text-right">
                                            <button type="button" class="btn btn-default">Ganti Nomor ?</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="splash-footer"><span>Don't have an account? <a href="#">Sign Up</a></span></div>
                    </div>
                </div>
            </div>
        </div>
        <script src="public/assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
        <script src="public/assets/js/main.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery.gritter/js/jquery.gritter.js" type="text/javascript"></script>
        <script src="public/assets/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery.maskedinput/jquery.maskedinput.min.js" type="text/javascript"></script>
        <script src="public/assets/lib/jquery-autotab/js/jquery.autotab.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                //initialize the javascript
                App.init();

                <?php if($codeError): ?>
                $.gritter.add({
                    title: 'Gagal',
                    text: 'Kode yang anda masukkan salah!',
                    class_name: 'color danger'
                });
                <?php endif; ?>

                var smscode = '';
                $('.input-mask').autotab({
                    maxlength: 1,
                    uppercase: true,
                    format: 'alphanumeric',

                });
                $('.input-mask').on('change', function () {
                    smscode = '';
                    $('.input-mask').each(function (key, elm) {
                        smscode = smscode + $(elm).val();
                        console.log(smscode);
                    });
                    $('input[name="smscode"]').val(smscode);
                });
                function btnReSend() {
                    var seconds = 30;
                    $('.btn-resend').attr('disabled', 'disabled');
                    var interval = setInterval(function () {
                        seconds = seconds - 1;
                        $('.btn-resend').html('Kirim Kode Ulang (' + seconds + ')');
                        if(seconds == 0){
                            $('.btn-resend').html('Kirim Kode Ulang');
                            $('.btn-resend').removeAttr('disabled');
                            clearInterval(interval);
                        }
                    }, 1000);
                }
                btnReSend();
                $('.btn-resend').on('click', function () {
                    $.getJSON('<?= $this->pathFor('reSendVerificationSMS', ['token'=>$token, 'telefon'=>$telefon]) ?>', function (res) {
                        if(res.status == 'success'){
                            btnReSend();
                            $.gritter.add({
                                title: 'Berhasil!',
                                text: 'SMS berhasil terkirim',
                                class_name: 'color success'
                            });
                        }
                    })
                })
            });
        </script>
    </body>
</html>