<?php
/**
 * Copyright (c) 2017.
 */

$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Approval Dokumen Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Berita Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Kualifikasi</label>
                        <div class="well well-sm aside-well">
                            <?php foreach ($this->autocomplete('kualifikasi', ['id_tender'=>$tender['id_tender']]) as $kualifikasi): ?>
                                <span class="label label-default"><?= $kualifikasi ?></span>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><?= substr($tender['link_website'], 0, 35) ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Diupload Oleh</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
                <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div>
            </div>
        </div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Dokumen Tender
                <div class="tools">
                </div>
            </div>
            <div class="panel-body">
                <table id="dok-req" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="30%">Nama Dokumen</th>
                            <th width="30%">Diupload Oleh</th>
                            <th width="15%">Status Approval</th>
                            <th width="20%"class="text-center">Approval</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Dokumen Pelengkap
                <div class="tools">
                </div>
            </div>
            <div class="panel-body">
                <table id="dok-opt" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="30%">Nama Dokumen</th>
                            <th width="30%">Diupload Oleh</th>
                            <th width="15%">Status Approval</th>
                            <th width="20%"class="text-center">Approval</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="approval-terima" class="modal-container colored-header modal-effect-8" style="top:50% !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Custom Header Color</h3>
            </div>
            <div class="modal-body">
                <!-- 16:9 aspect ratio -->
                <div class="embed-responsive embed-responsive-16by9">
                    <div id="emebed-pdf" class="embed-responsive-item"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-success modal-terima modal-close hidden">Approve</button>
                <button type="button" data-dismiss="modal" class="btn btn-danger modal-tolak modal-close hidden">Tolak</button>
                <button type="button" data-dismiss="modal" class="btn btn-default modal-close">Batal</button>
            </div>
        </div>
    </div>
    <div class="modal-overlay"></div>
    <div id="preview-template" style="display: none;">
        <div class="dz-preview dz-file-preview" style="display: none;">
            <div class="dz-details" style="display: none;">
                <div class="dz-filename"><span data-dz-name></span></div>
                <div class="dz-size" data-dz-size></div>
                <img data-dz-thumbnail />
            </div>
            <div class="dz-progress" style="display: none;"><span class="dz-upload" data-dz-uploadprogress></span></div>
            <div class="dz-success-mark" style="display: none;"><span>✔</span></div>
            <div class="dz-error-mark" style="display: none;"><span>✘</span></div>
            <div class="dz-error-message" style="display: none;"><span data-dz-errormessage></span></div>
        </div>
    </div>

    <!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/dropzone/dist/min/dropzone.min.js" type="text/javascript"></script>
    <script src="public/assets/js/jquery.form.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/PDFObject/pdfobject.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });
            //We use this to apply style to certain elements
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada data Dokumen Kelengkapan Tender</h4>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });
            var dokReq = $('#dok-req').DataTable({
                ajax:"<?= $this->pathFor('dokumenTender_getRequired', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: null,
                        className:' cell-detail',
                        render: function (data, type, row, meta) {
                            if(data.file_dokumen){
                                return  '<span>'+data.nama_dokumen+'</span>'+
                                        '<a href="public/content/dokumen/'+data.file_dokumen+'" target="_blank" class="cell-detail-description">'+data.file_dokumen.substr(0, 25)+'</a>';
                            }else{
                                return  '<span>'+data.nama_dokumen+'</span>'+
                                    '<span class="cell-detail-description">Belum Diupload</span>';
                            }
//                            return data.nama_dokumen;
                        }
                    },
                    {
                        data: null,
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                var waktu = moment(data.tgl_upload).fromNow()
                                return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + (data.who.id_user == active_user.user_id ? 'Anda Sendiri' : data.who.nama) + '</span><span class="cell-detail-description">' + waktu + '</span><span class="cell-detail-description"><mark>' + (data.who.unit_kerja ? data.who.unit_kerja.penugasan : '' ) + '</mark></span>';
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className:"milestone text-center",
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                return  '<div class="btn-group btn-space btn-group-xs">'+
                                    '   <button type="button" class="btn btn-color '+(data.approval.direktur.status == '' ? 'btn-default' : (data.approval.direktur.status == 'diterima' ? 'btn-success' : 'btn-danger'))+'">'+
                                    '       <i class="icon mdi '+(data.approval.direktur.status == '' ? 'mdi-circle-o' : (data.approval.direktur.status == 'diterima' ? 'mdi-check-circle' : 'mdi-close"'))+'"></i>'+
                                    '   </button>'+
                                    '   <button type="button" class="btn btn-default">Direktur</button>'+
                                    '</div>'+
                                    '<div class="btn-group btn-space btn-group-xs">'+
                                    '   <button type="button" class="btn btn-color '+(data.approval.manajer.status == '' ? 'btn-default' : (data.approval.manajer.status == 'diterima' ? 'btn-success' : 'btn-danger'))+'">'+
                                    '       <i class="icon mdi '+(data.approval.manajer.status == '' ? 'mdi-circle-o' : (data.approval.manajer.status == 'diterima' ? 'mdi-check-circle' : 'mdi-close"'))+'"></i>'+
                                    '   </button>'+
                                    '   <button type="button" class="btn btn-default">Manajer</button>'+
                                    '</div>';
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className: "text-center",
                        render: function (data, type, row, meta) {
                            if(data.file_dokumen) {
                                return  '<div class="btn-group btn-space">' +
                                    '   <a href="public/content/dokumen/' + data.file_dokumen + '" target="_blank" class="btn btn-primary btn-lihat" data-toggle="tooltip" data-placement="top" data-original-title="Lihat Dokumen">' +
                                    '       <i class="icon mdi mdi-eye"></i>' +
                                    '   </a>' +
                                    '   <button type="button" class="btn btn-success btn-approve" '+(active_user.previledge == '3' && data.approval.manajer.status == 'diterima' ? 'disabled' : '')+(active_user.previledge == '2' && data.approval.direktur.status == 'diterima' ? 'disabled' : '')+' data-id="'+data.id_dokumen+'" data-dokumen="'+data.nama_dokumen+'" data-file="'+data.file_dokumen+'" data-type="terima" data-toggle="tooltip" data-placement="top" data-original-title="Setujui Dokumen">' +
                                    '       <i class="icon mdi mdi-check"></i>' +
                                    '   </button>' +
                                    '   <button type="button" class="btn btn-danger btn-approve" '+(active_user.previledge == '3' && data.approval.manajer.status == 'ditolak' ? 'disabled' : '')+(active_user.previledge == '2' && data.approval.direktur.status == 'ditolak' ? 'disabled' : '')+' data-id="'+data.id_dokumen+'" data-dokumen="'+data.nama_dokumen+'" data-file="'+data.file_dokumen+'" data-type="tolak" data-toggle="tooltip" data-placement="top" data-original-title="Tolak Dokumen">' +
                                    '       <i class="icon mdi mdi-close"></i>' +
                                    '   </button>' +
                                    '</div>';
                            }else{
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                ],
                createdRow: function ( row, data, index ) {
                    if(data.file_dokumen){
                        $(row).addClass('online');
                    }
                },
                initComplete: function (settings, json) {
                    $('[data-toggle="tooltip"]').tooltip()
                }
            });

            $('#dok-req tbody').on('click', '.btn-approve', function () {
                var nama_dokumen = $(this).data('dokumen');
                var file_dokumen = $(this).data('file');
                var id_dokumen = $(this).data('id');
                var type = $(this).data('type');
                $('#approval-terima').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        if(type == 'terima'){
                            modal.removeClass('colored-header-danger');
                            modal.addClass('colored-header-success');
                            modal.find('h3.modal-title').html('Approve Dokumen <strong>'+nama_dokumen+'</strong>?');
                            modal.find('.modal-terima').removeClass('hidden');
                            modal.find('.modal-tolak').addClass('hidden');
                        }else{
                            modal.addClass('colored-header-danger');
                            modal.removeClass('colored-header-success');
                            modal.find('h3.modal-title').html('Tolak Dokumen <strong>'+nama_dokumen+'</strong>?');
                            modal.find('.modal-terima').addClass('hidden');
                            modal.find('.modal-tolak').removeClass('hidden');
                        }
                        PDFObject.embed('public/content/dokumen/'+file_dokumen, modal.find('#emebed-pdf'), {height: "35rem"});
                    },
                    buttons: [
                        {
                            class: 'modal-terima',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                $.getJSON("<?= $this->pathFor('dokumenTender_Approval') ?>/"+id_dokumen+'/diterima', function(data){
                                    if(data.status == "success"){
                                        $.gritter.add({
                                            title: 'Approval Dokumen',
                                            text: 'Anda berhasil menyetujui dokumen <strong>'+nama_dokumen+'</strong>',
                                            class_name: 'color success',
                                            time: '5',
                                        });
                                        dokReq.ajax.reload();
                                        return true;
                                    }
                                });
                            }
                        },
                        {
                            class: 'modal-tolak',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                $.getJSON("<?= $this->pathFor('dokumenTender_Approval') ?>/"+id_dokumen+'/ditolak', function(data){
                                    if(data.status == "success"){
                                        $.gritter.add({
                                            title: 'Tolak Dokumen',
                                            text: 'Anda berhasil menolak dokumen <strong>'+nama_dokumen+'</strong>',
                                            class_name: 'color danger',
                                            time: '5',
                                        });
                                        dokReq.ajax.reload();
                                        return true;
                                    }
                                });
                            }
                        },
                    ],
                });
            });

            var dokOpt = $('#dok-opt').DataTable({
                ajax:"<?= $this->pathFor('dokumenTender_getOptional', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: null,
                        className:' cell-detail',
                        render: function (data, type, row, meta) {
                            return  '<span>'+data.nama_dokumen+'</span>'+
                                '<a href="public/content/dokumen/'+data.file_dokumen+'" target="_blank" class="cell-detail-description">'+data.file_dokumen.substr(0, 25)+'</a>';
//                            return data.nama_dokumen;
                        }
                    },
                    {
                        data: null,
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                var waktu = moment(data.tgl_upload).fromNow()
                                return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + (data.who.id_user == active_user.user_id ? 'Anda Sendiri' : data.who.nama) + '</span><span class="cell-detail-description">' + waktu + '</span><span class="cell-detail-description"><mark>' + (data.who.unit_kerja ? data.who.unit_kerja.penugasan : '' ) + '</mark></span>';
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className:"milestone text-center",
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                return  '<div class="btn-group btn-space btn-group-xs">'+
                                    '   <button type="button" class="btn btn-color '+(data.approval.direktur.status == '' ? 'btn-default' : (data.approval.direktur.status == 'diterima' ? 'btn-success' : 'btn-danger'))+'">'+
                                    '       <i class="icon mdi '+(data.approval.direktur.status == '' ? 'mdi-circle-o' : (data.approval.direktur.status == 'diterima' ? 'mdi-check-circle' : 'mdi-close"'))+'"></i>'+
                                    '   </button>'+
                                    '   <button type="button" class="btn btn-default">Direktur</button>'+
                                    '</div>'+
                                    '<div class="btn-group btn-space btn-group-xs">'+
                                    '   <button type="button" class="btn btn-color '+(data.approval.manajer.status == '' ? 'btn-default' : (data.approval.manajer.status == 'diterima' ? 'btn-success' : 'btn-danger'))+'">'+
                                    '       <i class="icon mdi '+(data.approval.manajer.status == '' ? 'mdi-circle-o' : (data.approval.manajer.status == 'diterima' ? 'mdi-check-circle' : 'mdi-close"'))+'"></i>'+
                                    '   </button>'+
                                    '   <button type="button" class="btn btn-default">Manajer</button>'+
                                    '</div>';
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className: "text-center",
                        render: function (data, type, row, meta) {
                            return  '<div class="btn-group btn-space">' +
                                '   <a href="public/content/dokumen/' + data.file_dokumen + '" target="_blank" class="btn btn-primary btn-lihat" data-toggle="tooltip" data-placement="top" data-original-title="Lihat Dokumen">' +
                                '       <i class="icon mdi mdi-eye"></i>' +
                                '   </a>' +
                                '   <button type="button" class="btn btn-success btn-approve" '+(active_user.previledge == '3' && data.approval.manajer.status == 'diterima' ? 'disabled' : '')+(active_user.previledge == '2' && data.approval.direktur.status == 'diterima' ? 'disabled' : '')+' data-id="'+data.id_dokumen+'" data-dokumen="'+data.nama_dokumen+'" data-file="'+data.file_dokumen+'" data-type="terima" data-toggle="tooltip" data-placement="top" data-original-title="Setujui Dokumen">' +
                                '       <i class="icon mdi mdi-check"></i>' +
                                '   </button>' +
                                '   <button type="button" class="btn btn-danger btn-approve" '+(active_user.previledge == '3' && data.approval.manajer.status == 'ditolak' ? 'disabled' : '')+(active_user.previledge == '2' && data.approval.direktur.status == 'ditolak' ? 'disabled' : '')+' data-id="'+data.id_dokumen+'" data-dokumen="'+data.nama_dokumen+'" data-file="'+data.file_dokumen+'" data-type="tolak" data-toggle="tooltip" data-placement="top" data-original-title="Tolak Dokumen">' +
                                '       <i class="icon mdi mdi-close"></i>' +
                                '   </button>' +
                                '</div>';
                        }
                    },
                ],
                createdRow: function ( row, data, index ) {
                    if(data.file_dokumen){
                        $(row).addClass('online');
                    }
                },
                initComplete: function (settings, json) {
                    $('[data-toggle="tooltip"]').tooltip()
                }
            });
            $('#dok-opt tbody').on('click', '.btn-approve', function () {
                var nama_dokumen = $(this).data('dokumen');
                var file_dokumen = $(this).data('file');
                var id_dokumen = $(this).data('id');
                var type = $(this).data('type');
                $('#approval-terima').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        if(type == 'terima'){
                            modal.removeClass('colored-header-danger');
                            modal.addClass('colored-header-success');
                            modal.find('h3.modal-title').html('Approve Dokumen <strong>'+nama_dokumen+'</strong>?');
                            modal.find('.modal-terima').removeClass('hidden');
                            modal.find('.modal-tolak').addClass('hidden');
                        }else{
                            modal.addClass('colored-header-danger');
                            modal.removeClass('colored-header-success');
                            modal.find('h3.modal-title').html('Tolak Dokumen <strong>'+nama_dokumen+'</strong>?');
                            modal.find('.modal-terima').addClass('hidden');
                            modal.find('.modal-tolak').removeClass('hidden');
                        }
                        PDFObject.embed('public/content/dokumen/'+file_dokumen, modal.find('#emebed-pdf'), {height: "35rem"});
                    },
                    buttons: [
                        {
                            class: 'modal-terima',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                $.getJSON("<?= $this->pathFor('dokumenTender_Approval') ?>/"+id_dokumen+'/diterima', function(data){
                                    if(data.status == "success"){
                                        $.gritter.add({
                                            title: 'Approval Dokumen',
                                            text: 'Anda berhasil menyetujui dokumen <strong>'+nama_dokumen+'</strong>',
                                            class_name: 'color success',
                                            time: '5',
                                        });
                                        dokOpt.ajax.reload();
                                        return true;
                                    }
                                });
                            }
                        },
                        {
                            class: 'modal-tolak',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                $.getJSON("<?= $this->pathFor('dokumenTender_Approval') ?>/"+id_dokumen+'/ditolak', function(data){
                                    if(data.status == "success"){
                                        $.gritter.add({
                                            title: 'Tolak Dokumen',
                                            text: 'Anda berhasil menolak dokumen <strong>'+nama_dokumen+'</strong>',
                                            class_name: 'color danger',
                                            time: '5',
                                        });
                                        dokOpt.ajax.reload();
                                        return true;
                                    }
                                });
                            }
                        },
                    ],
                });
            });
        })
    </script>
<?php $this->stop() ?>