<?php
$parent_data = [
    'active_user_data' => $active_user_data,
    'active_notification_list' => $active_notification_list,
    'aside' => true
];
$this->layout('base', $parent_data);
$this->start('style');
?>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/datatables/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="public/assets/lib/select2/css/select2.min.css"/>
    <!--tempat css/style-->
<?php
$this->stop();
$this->start('page-title');
?>
    Dokumen Kelengkapan Tender
<?php
$this->stop();
$this->start('contents');
?>
    <!--tempat konten-->
    <aside class="page-aside">
        <div class="be-scroller">
            <div class="nano-content">
                <div class="content">
                    <h3>Detail Berita Tender</h3><br>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Judul Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['judul_tender'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Tanggal Pelaksanaan</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-default"><?= $this->indDate($tender['tgl_mulai']) ?></span>
                            &nbsp; s/d &nbsp;
                            <span class="label label-default"><?= $this->indDate($tender['tgl_selesai']) ?></span>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Nama Penyelenggara</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $this->getNamaPenyelenggara($tender['id_penyelenggara']) ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Lokasi Tender</label>
                        <div class="well well-sm aside-well">
                            <strong><?= $tender['wilayah'] ?></strong>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Kualifikasi</label>
                        <div class="well well-sm aside-well">
                            <?php foreach ($this->autocomplete('kualifikasi', ['id_tender'=>$tender['id_tender']]) as $kualifikasi): ?>
                                <span class="label label-default"><?= $kualifikasi ?></span>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Link Website</label>
                        <div class="well well-sm aside-well">
                            <a href="<?= $tender['link_website'] ?>" target="_blank">
                                <strong><?= substr($tender['link_website'], 0, 35) ?></strong>
                            </a>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label">Diupload Oleh</label>
                        <div class="well well-sm aside-well">
                            <span class="label label-primary"><?= $this->getUserUpload($tender['id_user'])['nama'] ?></span>
                            <span class="label label-default"><?= $this->indDateTime($tender['tgl_upload']) ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
            </div>
            <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
                <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div>
            </div>
        </div>
    </aside>
    <div class="main-content container-fluid">
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Dokumen Prasyarat
                <div class="tools">
                    <button class="btn btn-space btn-primary btn-sm add-dok" data-type="required">
                        <i class="mdi mdi-file-plus"></i>
                        &nbsp; Tambah Dokumen Prasyarat
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="dok-req" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="20%">Nama Dokumen</th>
                            <th width="35%">File</th>
                            <th width="20%">Diupload Oleh</th>
                            <th width="20%"class="action"></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <div class="panel panel-default panel-table  panel-border-color panel-border-color-primary">
            <div class="panel-heading">Daftar Dokumen Pelengkap
                <div class="tools">
                    <button class="btn btn-space btn-primary btn-sm add-dok" data-type="optional">
                        <i class="mdi mdi-file-plus"></i>
                        &nbsp; Tambah Dokumen Pelengkap
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="dok-opt" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="20%">Nama Dokumen</th>
                            <th width="35%">File</th>
                            <th width="20%">Diupload Oleh</th>
                            <th width="20%" class="action"></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="modal-add-dok" class="modal-container colored-header colored-header-primary modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Tambah Dokumen Pelengkap</h3>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" action="<?= $this->pathFor('dokumenTender_add', ['id_tender'=>$tender['id_tender']]) ?>">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nama Dokumen</label>
                        <div class="col-sm-9">
                            <input type="text" name="nama_dokumen" placeholder="Nama Dokumen : SIUP" class="form-control">
                            <span class="help-block text-waring">Wajib di-isi</span>
                            <input type="hidden" name="dokumen_syarat" value="1">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">File Dokumen</label>
                        <div class="col-sm-9">
                            <div class="input-group xs-mb-15">
                                <input type="text" name="file_name" class="form-control" readonly>
                                <input type="file" name="file_dokumen" placeholder="Nama Dokumen : SIUP" accept="application/pdf"  class="hidden" hidden>
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-primary modal-close input-file"><i class="mdi mdi-file-plus"></i> Pilih File</button>
                                </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default btn-cancel modal-close">Cancel</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary btn-ok modal-close">Proceed</button>
            </div>
        </div>
    </div>
    <div id="modal-edit-dok" class="modal-container colored-header colored-header-primary modal-effect-1">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
                <h3 class="modal-title">Ubah data dokumen</h3>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" action="<?= $this->pathFor('dokumenTender_set', ['id_tender'=>$tender['id_tender']]) ?>">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nama Dokumen</label>
                        <div class="col-sm-9">
                            <input type="text" name="nama_dokumen" placeholder="Nama Dokumen : SIUP" class="form-control">
                            <input type="hidden" name="id_dokumen">
                            <span class="help-block text-waring">Wajib di-isi</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">File Dokumen</label>
                        <div class="col-sm-9">
                            <div class="input-group xs-mb-15">
                                <input type="text" name="file_name" class="form-control" readonly>
                                <input type="file" name="file_dokumen" placeholder="Nama Dokumen : SIUP" accept="application/pdf"  class="hidden" hidden>
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-primary modal-close input-file"><i class="mdi mdi-file-plus"></i> Pilih File</button>
                                </span>
                            </div>
                            <span class="help-block text-waring">untuk merubah nama dokumen, file dokumen tidak perlu di isi</span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default btn-cancel modal-close">Cancel</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary btn-ok modal-close">Proceed</button>
            </div>
        </div>
    </div>
    <div id="modal-delete-dok" class="modal-container modal-effect-8" style="perspective: 1300px; height: 382px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><span class="mdi mdi-close"></span></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <span class="modal-main-icon mdi mdi-delete text-danger"></span>
                    <h3>Hapus!</h3>
                    <p>Apakah anda yakin akan menghapus dokumen <strong></strong>?</p>
                    <div class="xs-mt-50">
                        <button type="button" data-dismiss="modal" class="btn btn-danger btn-space btn-delete modal-close">Hapus</button>
                        <button type="button" data-dismiss="modal" class="btn btn-default btn-space modal-close">Batal</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
    <div class="modal-overlay"></div>

    <!--akhir tempat konten-->
<?php
$this->stop();
$this->start('js');
?>
    <!--tempat js-->
    <script src="public/assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.html5.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.flash.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.print.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.colVis.js" type="text/javascript"></script>
    <script src="public/assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js" type="text/javascript"></script>
    <script src="public/assets/js/app-tables-datatables.js" type="text/javascript"></script>
    <script src="public/assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
    <script src="public/assets/lib/dropzone/dist/min/dropzone.min.js" type="text/javascript"></script>
    <script src="public/assets/js/jquery.form.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.fn.modal.Constructor.prototype.enforceFocus = $.noop;
            $.fn.niftyModal('setDefaults', {
                overlaySelector: '.modal-overlay',
                closeSelector: '.modal-close',
                classAddAfterOpen: 'modal-show',
            });
            $.extend(true, $.fn.dataTable.defaults, {
                dom: "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row be-datatable-body'<'col-sm-12'tr>>" +
                "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>",
                language: {

                    emptyTable: '<h4>Belum ada data Dokumen Kelengkapan Tender</h4>',
                    lengthMenu: "_MENU_ &nbsp; data per halaman",
                    "zeroRecords": "Tidak ada data yang cocok dengan pencarian anda",
                    "info": "Hal _PAGE_ dari _PAGES_ halaman",
                    "infoEmpty": "Tidak ada data tersedia",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "first": '<i class="mdi mdi-caret-left-circle"></i>',
                        "last": '<i class="mdi mdi-caret-right-circle"></i>',
                        "next": '<i class="mdi mdi-caret-right-circle"></i>',
                        "previous": '<i class="mdi mdi-caret-left-circle"></i>'
                    },
                    "search": '<i class="mdi mdi-search" style="padding-right:5px; font-size:20px"></i>',
                    "searchPlaceholder": 'Cari',
                },
            });


            var upload_url = "<?= $this->pathFor("dokumenTender_set", ['id_tender'=>$tender['id_tender']]) ?>";


            $('.add-dok').on('click', function(){
                var type = $(this).data('type')
                $('#modal-add-dok').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('.modal-title').html('Tambah Dokumen ' + (type == 'required' ? 'Prasyarat' : 'Pelengkap'))
                        modal.find('input[name="nama_dokumen"]').val('')
                        modal.find('input[name="file_dokumen"]').val('')
                        modal.find('input[name="file_name"]').val('')
                        modal.find('input[name="dokumen_syarat"]').val(type == 'required' ? '1' : '0')
                    },
                    buttons: [
                        {
                            class: 'input-file',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                modal.find('input[name="file_dokumen"]').click();
                                modal.find('input[name="file_dokumen"]').on('change', function () {
                                    modal.find('input[name="file_name"]').val($(this).val().replace(/C:\\fakepath\\/i, ''))
                                });
                                return false
                            }
                        },{
                            class: 'btn-ok',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                if(modal.find('input[name="nama_dokumen"]').val() !== ""){
                                    modal.find('form').ajaxSubmit({
                                        type:"post",
                                        dataType:"json",
                                        success: function (res, status, xhr, $form) {
                                            if(res.status == "success"){
                                                dokReq.ajax.reload();
                                                dokOpt.ajax.reload();
                                                return true;
                                            }else{
                                                return false;
                                            }
                                        }
                                    });
                                }else{
                                    return false;
                                }
                            }
                        }
                    ],
                });
            });

            var dokReq = $('#dok-req').DataTable({
                ajax:"<?= $this->pathFor('dokumenTender_getRequired', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return data.nama_dokumen;
                        }
                    },
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                return "<a target='_blank' href='public/content/dokumen/"+data.file_dokumen+"'>"+data.file_dokumen.substr(0, 60)+"</a>";
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                var waktu = moment(data.tgl_upload).fromNow()
                                return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + (data.who.id_user == active_user.user_id ? 'Anda Sendiri' : data.who.nama) + '</span><span class="cell-detail-description">' + waktu + '</span><span class="cell-detail-description">' + (data.who.unit_kerja ? data.who.unit_kerja.penugasan : '' ) + '</span>';
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className: "text-right",
                        render: function (data, type, row, meta) {
                            delete data.rowData;
                            return  '   <div class="btn-group">'+
                                    '      <button type="button" class="btn btn-' + (data.file_dokumen ? 'default' : 'primary') + ' btn-edit" data-rowdata=\'' + JSON.stringify(data) + '\'><i class="icon icon-left mdi mdi-attachment"></i> ' + (data.file_dokumen ? 'ganti' : 'upload') + '</button>'+
                                    '      <button class="btn btn-danger btn-delete"  data-rowdata=\'' + JSON.stringify(data) + '\'><i class="icon icon-left mdi mdi-delete"></i></button>'+
                                    '   </div>'
                        }
                    },
                ],
                createdRow: function ( row, data, index ) {
                    if(data.file_dokumen){
                        $(row).addClass('online');
                    }
                    $(row).find('form.form-upload').each(function () {
                        var id = $(this).data('id');
                    })
                }
            });

            function modalEdit(data) {
                $('#modal-edit-dok').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('.modal-title').html('Ubah Dokumen ' + data.nama_dokumen)
                        modal.find('input[name="nama_dokumen"]').val(data.nama_dokumen)
                        modal.find('input[name="file_dokumen"]').val('')
                        modal.find('input[name="file_name"]').val(data.file_dokumen ? data.file_dokumen : 'Belum diupload')
                        modal.find('input[name="id_dokumen"]').val(data.id_dokumen)
                    },
                    buttons: [
                        {
                            class: 'input-file',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                modal.find('input[name="file_dokumen"]').click();
                                modal.find('input[name="file_dokumen"]').on('change', function () {
                                    modal.find('input[name="file_name"]').val($(this).val().replace(/C:\\fakepath\\/i, ''))
                                });
                                return false
                            }
                        },{
                            class: 'btn-ok',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                if(modal.find('input[name="nama_dokumen"]').val() !== ""){
                                    modal.find('form').ajaxSubmit({
                                        type:"post",
                                        dataType:"json",
                                        success: function (res, status, xhr, $form) {
                                            if(res.status == "success"){
                                                dokReq.ajax.reload();
                                                dokOpt.ajax.reload();
                                                return true;
                                            }else{
                                                return false;
                                            }
                                        }
                                    });
                                }else{
                                    return false;
                                }
                            }
                        }
                    ],
                });
            }

            $('#dok-req tbody').on('click', '.btn-edit', function () {
                modalEdit($(this).data('rowdata'));
            });

            function modalDelete(data) {
                $('#modal-delete-dok').niftyModal({
                    beforeOpen: function( modals ){
                        var modal = $(modals.modalEl);
                        modal.find('p strong').html(data.nama_dokumen)
                    },
                    buttons: [
                        {
                            class: 'btn-delete',
                            callback: function ( btn, modals, event ) {
                                var modal = $(modals.modalEl);
                                if(modal.find('input[name="nama_dokumen"]').val() !== ""){
                                    $.getJSON("<?= $this->pathFor('dokumenTender_delete') ?>/"+data.id_dokumen, function(data){
                                        if(data.status == "success"){
                                            dokReq.ajax.reload();
                                            dokOpt.ajax.reload();
                                            return true;
                                        }
                                    });
                                }else{
                                    return false;
                                }
                            }
                        }
                    ]
                });
            }

            $('#dok-req tbody').on('click', '.btn-delete', function () {
                modalDelete($(this).data('rowdata'));
            })

            var dokOpt = $('#dok-opt').DataTable({
                ajax:"<?= $this->pathFor('dokumenTender_getOptional', ['id_tender'=>$tender['id_tender']]) ?>",
                columns:[
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            return data.nama_dokumen;
                        }
                    },
                    {
                        data: null,
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                return "<a target='_blank' href='public/content/dokumen/"+data.file_dokumen+"'>"+data.file_dokumen.substr(0, 60)+"</a>";
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className: 'user-avatar cell-detail user-info',
                        render: function (data, type, row, meta) {
                            if (data.file_dokumen) {
                                var waktu = moment(data.tgl_upload).fromNow()
                                return '<img src="public/profile/' + data.who.image + '" alt="Avatar"><span>' + (data.who.id_user == active_user.user_id ? 'Anda Sendiri' : data.who.nama) + '</span><span class="cell-detail-description">' + waktu + '</span><span class="cell-detail-description">' + (data.who.unit_kerja ? '<mark>'+data.who.unit_kerja.penugasan+'</mark>' : '' ) + '</span>';
                            } else {
                                return "<small class='text-muted'>Belum Diupload</small>"
                            }
                        }
                    },
                    {
                        data: null,
                        className: "text-right",
                        render: function (data, type, row, meta) {
                            delete  data.rowData;
                            return  '   <div class="btn-group">'+
                                    '      <button type="button" class="btn btn-' + (data.file_dokumen ? 'default' : 'primary') + ' btn-edit" data-rowdata=\'' + JSON.stringify(data) + '\'><i class="icon icon-left mdi mdi-attachment"></i> ' + (data.file_dokumen ? 'ganti' : 'upload') + '</button>'+
                                    '      <button class="btn btn-danger btn-delete" data-rowdata=\'' + JSON.stringify(data) + '\'><i class="icon icon-left mdi mdi-delete"></i></button>'+
                                    '   </div>'
                        }
                    },
                ],
                createdRow: function ( row, data, index ) {
                    console.log(data)
                }
            });

            $('#dok-opt tbody').on('click', '.btn-edit', function () {
                modalEdit($(this).data('rowdata'));
            })
            $('#dok-opt tbody').on('click', '.btn-delete', function () {
                modalDelete($(this).data('rowdata'));
            })

        })
    </script>
<?php $this->stop() ?>